*****************************************************************************************************;
* SOCIAL SUPPORT AND MORTALITY PH ASSUMPTION CHECK
* PI'S: KASSANDRA ALCARAZ AND SUE GAPSTUR
* ANALYST: JENNY BLASE	
* NOTE: SINCE ANALYSIS RESULTS ARE PRESENTED BY SEX/RACE GROUPS DOING PH ASSUMPTION FOR ALL CAUSE MORTALITY FOR EACH SEX/RACE GROUPS
*****************************************************************************************************;

LIBNAME SOCIAL 'D:\USER\JBLASE\Social Support\DATA';
LIBNAME LIBRARY 'D:\USER\JBLASE\Social Support\DATA';

PROC FORMAT;
VALUE MERGEVAR
	1='Age-adjusted'
	2='Fully-adjusted';
run;

*NOT INCLUDING SEX OR RACE AS COVARIATES IN MODEL SINCE STRATIFIED BY SEX/RACE GROUPS BUT IF RUN CODE FOR ENTIRE COHORT REMEMBER TO INCLUDE THOSE AS COVARIATES!*; 

*************;
*BLACK MALES*;
*************;

*****************************************************************;
*   -2LL TEST													*;
*****************************************************************;
***REDUCED MODEL;
PROC PHREG DATA=SOCIAL.BLKMALE NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
            MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82/RL; 
 
STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED REDUCED MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;

DATA RED1 (KEEP=MERGEVAR MODELR); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELR=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA RED2 (KEEP=MERGEVAR RDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
RDF=DF;
MERGEVAR=2;
RUN;

DATA REDUCED (KEEP=MERGEVAR	MODELR RDF);
MERGE RED1 RED2;
BY MERGEVAR;
PROC PRINT DATA=REDUCED NOOBS;
RUN;

***INTERACTION MODEL;
PROC PHREG DATA=SOCIAL.BLKMALE NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82 TIMEINT2 TIMEINT3 TIMEINT4 TIMEINT5/RL; 
 				
			*DEFINE INTERACTION BETWEEN SOCIAL SUPPORT INDEX AND FOLLOW-UP TIME;			
			TIMEINT2=0; TIMEINT3=0; TIMEINT4=0; TIMEINT5=0;
            IF BSINDEX=1 THEN TIMEINT2=FAILAGELIM_MO;
            ELSE IF BSINDEX=2 THEN TIMEINT3=FAILAGELIM_MO;
            ELSE IF BSINDEX=3 THEN TIMEINT4=FAILAGELIM_MO;
			ELSE IF BSINDEX=4 THEN TIMEINT5=FAILAGELIM_MO;

STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED INTERACTION MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;


DATA FULL1 (KEEP=MERGEVAR MODELF); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELF=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA FULL2 (KEEP=MERGEVAR FDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
FDF=DF;
MERGEVAR=2;
RUN;

DATA FULMOD (KEEP=MERGEVAR MODELF FDF);
MERGE FULL1 FULL2;
BY MERGEVAR;
RUN;

DATA MVTEST (KEEP=MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL); 
MERGE REDUCED FULMOD; 
BY MERGEVAR;

CHIVAL=(MODELR-MODELF);
DF=(FDF-RDF);
PVALUE=1-PROBCHI(CHIVAL,DF);
PVAL=PUT(ROUND(PVALUE,0.001),5.3);

PROC PRINT DATA=MVTEST NOOBS;
RUN;

DATA LLTEST_BLKMALE;
SET MVTEST;
format mergevar mergevar.;
PROC PRINT DATA=LLTEST_BLKMALE;
RUN;


*************;
*WHITE MALES*;
*************;

*****************************************************************;
*   -2LL TEST													*;
*****************************************************************;
***REDUCED MODEL;
PROC PHREG DATA=SOCIAL.WHTMALE NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
            MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82/RL; 
 
STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED REDUCED MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;

DATA RED1 (KEEP=MERGEVAR MODELR); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELR=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA RED2 (KEEP=MERGEVAR RDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
RDF=DF;
MERGEVAR=2;
RUN;

DATA REDUCED (KEEP=MERGEVAR	MODELR RDF);
MERGE RED1 RED2;
BY MERGEVAR;
PROC PRINT DATA=REDUCED NOOBS;
RUN;

***INTERACTION MODEL;
PROC PHREG DATA=SOCIAL.WHTMALE NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82 TIMEINT2 TIMEINT3 TIMEINT4 TIMEINT5/RL; 
 				
			*DEFINE INTERACTION BETWEEN SOCIAL SUPPORT INDEX AND FOLLOW-UP TIME;			
			TIMEINT2=0; TIMEINT3=0; TIMEINT4=0; TIMEINT5=0;
            IF BSINDEX=1 THEN TIMEINT2=FAILAGELIM_MO;
            ELSE IF BSINDEX=2 THEN TIMEINT3=FAILAGELIM_MO;
            ELSE IF BSINDEX=3 THEN TIMEINT4=FAILAGELIM_MO;
			ELSE IF BSINDEX=4 THEN TIMEINT5=FAILAGELIM_MO;

STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED INTERACTION MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;


DATA FULL1 (KEEP=MERGEVAR MODELF); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELF=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA FULL2 (KEEP=MERGEVAR FDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
FDF=DF;
MERGEVAR=2;
RUN;

DATA FULMOD (KEEP=MERGEVAR MODELF FDF);
MERGE FULL1 FULL2;
BY MERGEVAR;
RUN;

DATA MVTEST (KEEP=MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL); 
MERGE REDUCED FULMOD; 
BY MERGEVAR;

CHIVAL=(MODELR-MODELF);
DF=(FDF-RDF);
PVALUE=1-PROBCHI(CHIVAL,DF);
PVAL=PUT(ROUND(PVALUE,0.001),5.3);

PROC PRINT DATA=MVTEST NOOBS;
RUN;

DATA LLTEST_WHTMALE;
SET MVTEST;
format mergevar mergevar.;
PROC PRINT DATA=LLTEST_WHTMALE;
RUN;


***************;
*BLACK FEMALES*;
***************;

*****************************************************************;
*   -2LL TEST													*;
*****************************************************************;
***REDUCED MODEL;
PROC PHREG DATA=SOCIAL.BLKFEM NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
            MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82/RL; 
 
STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED REDUCED MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;

DATA RED1 (KEEP=MERGEVAR MODELR); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELR=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA RED2 (KEEP=MERGEVAR RDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
RDF=DF;
MERGEVAR=2;
RUN;

DATA REDUCED (KEEP=MERGEVAR	MODELR RDF);
MERGE RED1 RED2;
BY MERGEVAR;
PROC PRINT DATA=REDUCED NOOBS;
RUN;

***INTERACTION MODEL;
PROC PHREG DATA=SOCIAL.BLKFEM NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82 TIMEINT2 TIMEINT3 TIMEINT4 TIMEINT5/RL; 
 				
			*DEFINE INTERACTION BETWEEN SOCIAL SUPPORT INDEX AND FOLLOW-UP TIME;			
			TIMEINT2=0; TIMEINT3=0; TIMEINT4=0; TIMEINT5=0;
            IF BSINDEX=1 THEN TIMEINT2=FAILAGELIM_MO;
            ELSE IF BSINDEX=2 THEN TIMEINT3=FAILAGELIM_MO;
            ELSE IF BSINDEX=3 THEN TIMEINT4=FAILAGELIM_MO;
			ELSE IF BSINDEX=4 THEN TIMEINT5=FAILAGELIM_MO;

STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED INTERACTION MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;


DATA FULL1 (KEEP=MERGEVAR MODELF); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELF=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA FULL2 (KEEP=MERGEVAR FDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
FDF=DF;
MERGEVAR=2;
RUN;

DATA FULMOD (KEEP=MERGEVAR MODELF FDF);
MERGE FULL1 FULL2;
BY MERGEVAR;
RUN;

DATA MVTEST (KEEP=MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL); 
MERGE REDUCED FULMOD; 
BY MERGEVAR;

CHIVAL=(MODELR-MODELF);
DF=(FDF-RDF);
PVALUE=1-PROBCHI(CHIVAL,DF);
PVAL=PUT(ROUND(PVALUE,0.001),5.3);

PROC PRINT DATA=MVTEST NOOBS;
RUN;

DATA LLTEST_BLKFEM;
SET MVTEST;
format mergevar mergevar.;
PROC PRINT DATA=LLTEST_BLKFEM;
RUN;


***************;
*WHITE FEMALES*;
***************;

*****************************************************************;
*   -2LL TEST													*;
*****************************************************************;
***REDUCED MODEL;
PROC PHREG DATA=SOCIAL.WHTFEM NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
            MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82/RL; 
 
STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED REDUCED MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;

DATA RED1 (KEEP=MERGEVAR MODELR); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELR=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA RED2 (KEEP=MERGEVAR RDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
RDF=DF;
MERGEVAR=2;
RUN;

DATA REDUCED (KEEP=MERGEVAR	MODELR RDF);
MERGE RED1 RED2;
BY MERGEVAR;
PROC PRINT DATA=REDUCED NOOBS;
RUN;

***INTERACTION MODEL;
PROC PHREG DATA=SOCIAL.WHTFEM NOSUMMARY MULTIPASS;
CLASS BSINDEX SMOKENEW EDUNEW BMI (REF='2:18.5-<25')/REF=FIRST ORDER=INTERNAL;
MODEL FAILAGELIM_MO*ALLCAUSE(0)=BSINDEX SMOKENEW EDUNEW BMI DB82 TIMEINT2 TIMEINT3 TIMEINT4 TIMEINT5/RL; 
 				
			*DEFINE INTERACTION BETWEEN SOCIAL SUPPORT INDEX AND FOLLOW-UP TIME;			
			TIMEINT2=0; TIMEINT3=0; TIMEINT4=0; TIMEINT5=0;
            IF BSINDEX=1 THEN TIMEINT2=FAILAGELIM_MO;
            ELSE IF BSINDEX=2 THEN TIMEINT3=FAILAGELIM_MO;
            ELSE IF BSINDEX=3 THEN TIMEINT4=FAILAGELIM_MO;
			ELSE IF BSINDEX=4 THEN TIMEINT5=FAILAGELIM_MO;

STRATA AGE_INT;
TITLE 'MULIVARIATE-ADJUSTED INTERACTION MODEL';
ODS OUTPUT FITSTATISTICS=FIT GLOBALTESTS=DEG;  
RUN;


DATA FULL1 (KEEP=MERGEVAR MODELF); 
SET FIT;
IF CRITERION='-2 LOG L';
MODELF=WITHCOVARIATES;
MERGEVAR=2;
RUN;

DATA FULL2 (KEEP=MERGEVAR FDF); 
SET DEG;	
IF TEST='Likelihood Ratio';
FDF=DF;
MERGEVAR=2;
RUN;

DATA FULMOD (KEEP=MERGEVAR MODELF FDF);
MERGE FULL1 FULL2;
BY MERGEVAR;
RUN;

DATA MVTEST (KEEP=MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL); 
MERGE REDUCED FULMOD; 
BY MERGEVAR;

CHIVAL=(MODELR-MODELF);
DF=(FDF-RDF);
PVALUE=1-PROBCHI(CHIVAL,DF);
PVAL=PUT(ROUND(PVALUE,0.001),5.3);

PROC PRINT DATA=MVTEST NOOBS;
RUN;

DATA LLTEST_WHTFEM;
SET MVTEST;
format mergevar mergevar.;
PROC PRINT DATA=LLTEST_WHTFEM;
RUN;




*LINDSAY'S DEMO TEMPLATE;
ODS PATH WORK.TEMPLAT(UPDATE)
SASUSR.TEMPLAT(UPDATE) SASHELP.TMPLMST(READ);
PROC TEMPLATE;
DEFINE STYLE STYLES.DEMO;
PARENT=STYLES.MINIMAL;
STYLE TABLE /
	FRAME=HSIDES
	RULES=GROUP
	CELLPADDING=2
	CELLSPACING=10
	JUST=L;
STYLE HEADER /
	JUST=L
	CELLPADDING=5;
STYLE DATAEMPHASIS /
	FONT_FACE = "ARIAL, HELVETICA, SANS-SERIF"
	FONT_SIZE=2
	FONT_WEIGHT = BOLD;
END;  

ODS RTF FILE="D:\USER\JBLASE\Social Support\RYAN\OUTPUT\PH CHECK ALL CAUSE MORTALITY - &SYSDATE..RTF"
	STYLE=DEMO;

*BLACK MALES*;
TITLE 'SOCIAL SUPPORT SCALE AND ALL CAUSE MORTALITY IN BLACK MALES';
title2 '-2LL Test of Proportional Hazards Assumption';
PROC REPORT DATA=LLTEST_BLKMALE HEADLINE HEADSKIP CENTER
STYLE(REPORT)={JUST=CENTER} SPLIT='~';
COLUMNS MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL;
DEFINE MERGEVAR/DISPLAY LEFT " ";
DEFINE MODELR/DISPLAY LEFT "-2logL Base";
DEFINE RDF/DISPLAY LEFT "df";
DEFINE MODELF/DISPLAY LEFT "-2logL Interaction";
DEFINE FDF/DISPLAY LEFT "df";
DEFINE CHIVAL/DISPLAY LEFT "Chi-square";
DEFINE DF/DISPLAY LEFT "df";
DEFINE PVAL/DISPLAY LEFT "p-value";
RUN;

*WHITE MALES*;
TITLE 'SOCIAL SUPPORT SCALE AND ALL CAUSE MORTALITY IN WHITE MALES';
title2 '-2LL Test of Proportional Hazards Assumption';
PROC REPORT DATA=LLTEST_WHTMALE HEADLINE HEADSKIP CENTER
STYLE(REPORT)={JUST=CENTER} SPLIT='~';
COLUMNS MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL;
DEFINE MERGEVAR/DISPLAY LEFT " ";
DEFINE MODELR/DISPLAY LEFT "-2logL Base";
DEFINE RDF/DISPLAY LEFT "df";
DEFINE MODELF/DISPLAY LEFT "-2logL Interaction";
DEFINE FDF/DISPLAY LEFT "df";
DEFINE CHIVAL/DISPLAY LEFT "Chi-square";
DEFINE DF/DISPLAY LEFT "df";
DEFINE PVAL/DISPLAY LEFT "p-value";
RUN;

*BLACK FEMALES*;
TITLE 'SOCIAL SUPPORT SCALE AND ALL CAUSE MORTALITY IN BLACK FEMALES';
title2 '-2LL Test of Proportional Hazards Assumption';
PROC REPORT DATA=LLTEST_BLKFEM HEADLINE HEADSKIP CENTER
STYLE(REPORT)={JUST=CENTER} SPLIT='~';
COLUMNS MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL;
DEFINE MERGEVAR/DISPLAY LEFT " ";
DEFINE MODELR/DISPLAY LEFT "-2logL Base";
DEFINE RDF/DISPLAY LEFT "df";
DEFINE MODELF/DISPLAY LEFT "-2logL Interaction";
DEFINE FDF/DISPLAY LEFT "df";
DEFINE CHIVAL/DISPLAY LEFT "Chi-square";
DEFINE DF/DISPLAY LEFT "df";
DEFINE PVAL/DISPLAY LEFT "p-value";
RUN;

*WHITE FEMALES*;
TITLE 'SOCIAL SUPPORT SCALE AND ALL CAUSE MORTALITY IN WHITE FEMALES';
title2 '-2LL Test of Proportional Hazards Assumption';
PROC REPORT DATA=LLTEST_WHTFEM HEADLINE HEADSKIP CENTER
STYLE(REPORT)={JUST=CENTER} SPLIT='~';
COLUMNS MERGEVAR MODELR RDF MODELF FDF CHIVAL DF PVAL;
DEFINE MERGEVAR/DISPLAY LEFT " ";
DEFINE MODELR/DISPLAY LEFT "-2logL Base";
DEFINE RDF/DISPLAY LEFT "df";
DEFINE MODELF/DISPLAY LEFT "-2logL Interaction";
DEFINE FDF/DISPLAY LEFT "df";
DEFINE CHIVAL/DISPLAY LEFT "Chi-square";
DEFINE DF/DISPLAY LEFT "df";
DEFINE PVAL/DISPLAY LEFT "p-value";
RUN;

ODS RTF CLOSE;

PROC DATASETS LIB=WORK NOLIST KILL;
QUIT;
RUN;

TITLE;
TITLE2;
TITLE3;
