* ORTHOVA TPR CODE *;
*NOTE: DO NOT USE THIS FOR STANDARD THR/TKR TPR CODE, THERE ARE MANY NUANCES/SPECIFICS FOR THIS PROVIDER*;

*UPDATED 5/2 TO REMOVE FACILITIES LISTED IN EMAIL FROM MELISSA GRIFFIN*;

libname tkr_test '/ephc/ebp/backup/data/phi/tjr/va/tkr';
libname thr_test '/ephc/ebp/backup/data/phi/tjr/va/thr';
LIBNAME JENNY '/ephc/ebp/nobackup/users/blase';
options compress=yes MPRINT;


***********;
***	TKR	***;
***********;

**************************;
**ORTHO VA - ALL MARKETS**;
**************************;

*ALL VALID EPISODES FOR VA MARKET*;

DATA TKR_MARKET TKR_ORTHOVA;
SET TKR_test.VA_TKR_CASE_0714_0615_PCR_v1;

/* TKR -- VALID Flagging criteria applied here */
if 
DRG_flg=1 AND /* Exclude episodes with the correct surg proc code but incorrect DRG (i.e., 462)*/
			  /* DRG inclusion criteria for index procedure but only apply to IP episodes */
			  /* allows for ASC episodes to not be excluded b/c DRG criteria is not applicable */
ind_flg=1 AND /* index trigger occurred within designated index period exclude 2nd index trigger */
			  /* occurring during experience period but outside of index period -- ind_flg=2 */
cap_flg in (0,2) AND  /* product exclusion criteria episodes with capitation-- cap_flg=1 */
ex_dx_flg=0 AND 	/* clinical historical exclusion criteria */
dx_flg=1 AND 		/* Dx inclusion criteria */
lob_lvl_flg in (1,2,3,4) AND /* Program Participation Exclusions of MCARE and MCAID */					
enrl_flg=1 AND /* continuous enrollment criteria */
lob_flg=1 AND  /* continuous enrolllment in same plan criteria */
age_flg=1 AND  /* minimum age at index service date criteria */
WP_Primary=0 AND /* Anthem primary criteria */
blt_flg=0 AND   /* bilateral exclusion criteria */
hosp_only_flg=0; /* product exclusion criteria */

*CREATING REGIONS ACCORDING TO MELISSA GRIFFIN*;
IF COUNTY_HOPPA IN ('LYNCHBURG CITY','ROANOKE CITY','CHARLOTTESVILLE CITY','SALEM') THEN REGION=1; *LYNCHBURG*;
ELSE IF COUNTY_HOPPA IN ('HENRICO','CHESTERFIELD','HANOVER','RICHMOND CITY','HOPEWELL CITY','PRINCE WILLIAM') THEN REGION=2; *RICHMOND*;
ELSE IF COUNTY_HOPPA IN ('MANASSAS CITY','FAIRFAX','FALLS CHURCH CITY','ALEXANDRIA CITY','ARLINGTON','LOUDOUN','FAUQUIER','HAMILTON') THEN REGION=3; *NORTHERN*;

*READMISSION FLAG*;
IF READMIT_FLG=1 AND (compl_flg=1 OR revise_flg=1) THEN READMISSION=1;
ELSE READMISSION=0;

FAC_TOT=index_fac_cost_PCR+postindex_fac_cost_PCR; *TOTAL FACILITY COSTS*;
PROF_TOT=index_prof_cost_PCR+postindex_prof_cost_PCR; *TOTAL PROFESSIONAL COSTS*;

*SPECIFIC STIPULATIONS PER MELISSA G.*;
PROF_NEW=PROF_TOT;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN PROF_NEW=PROF_TOT*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC="PPO" THEN PROF_NEW=PROF_TOT*(0.99728); 

BUNDLETOT_NEW=FAC_TOT+PROF_NEW; *CALCULATING NEW TOTAL BUNDLE COST*;

*NEW SURGEON COSTS ACCOUNTING FOR RENEGOTIATION. USED FOR HISTORICAL CASE RATE*;
SURG_NEW=index_prof_SURG_PCR;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN SURG_NEW=index_prof_SURG_PCR*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC="PPO" THEN SURG_NEW=index_prof_SURG_PCR*(0.99728); 

*PER MELISSA GRIFFEN - EXCLUDE VCU (indx_SRC_BILLG_TAX_ID="541848065") FOR RICHMOND (N=0)*;
*ADDED ADVANCED ORTHOPAEDICS TIN (541025125) PER MELISSA G. - 7/12/16*;
IF SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') THEN OUTPUT TKR_ORTHOVA; *AND indx_SRC_BILLG_TAX_ID NE "541848065";
OUTPUT TKR_MARKET; 

RUN;

*CREATING MACRO VARIABLES FOR THE TOTAL NUMBER OF VALID OBSERVATIONS (TO CALCULATE PERCENTAGES) AND MARKET
COMPLICATIONS/REVISIONS/READMISSIONS.
NOTE: THESE NUMBERS WILL STAY THE SAME REGARDLESS OF RENEGOTIATIONS*;
PROC SQL;
SELECT DISTINCT 
COUNT(*)
INTO :N_ORTHOVA_TKR 
FROM TKR_ORTHOVA;

*DENOMINATOR FOR COMPLICATION/REVISION/READMISSION RATES*;
SELECT DISTINCT 
COUNT(*)
INTO :N_MARKET_TKR 
FROM TKR_MARKET;

*CALCULATING MARKET READMISSION/REVISION/COMPLICATION RATES*;
CREATE TABLE MARKET_COMPS AS
SELECT 
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_MARKET_TKR AS COMPL_PER FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_MARKET_TKR AS READMIT_PER FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_MARKET_TKR AS REVISE_PER FORMAT=PERCENT8.1
FROM TKR_MARKET;

*CALCULATING NUMBER OF INITIAL EPISODES (BEFORE EXCLUSION CRITERIA APPLIED)*;
CREATE TABLE INITIAL_EPS AS 
SELECT
/* GENERATE TOPLINE -- Initial Episodes */
SUM (IND_FLG=1 AND DRG_FLG=1 AND LOB_LVL_FLG ne 9) AS INITIAL_EPISODES
FROM TKR_test.VA_TKR_CASE_0714_0615_PCR_v1
WHERE SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534');

QUIT;

*********************************;
*RENEGOTIATION OF RICHMOND RATES*;
*********************************;

PROC SQL;
*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW)))
INTO :HIGHCAP_ORTHOVA_TKR
FROM TKR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.
FROM TKR_MARKET; 

CREATE TABLE T1 AS
SELECT 
/*NUMBER OF VALID BASELINE EPISODES*/
COUNT(*) AS ELIG_EPS,
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(BUNDLETOT_NEW) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(BUNDLETOT_NEW<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_TKR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - ADJUSTING FOR RICHMOND RENEGOTIATION*/
MEAN(SURG_NEW) AS SURG_MEAN FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_TKR AS COMPL_PER FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_TKR AS READMIT_PER FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_TKR AS REVISE_PER FORMAT=PERCENT8.1
FROM TKR_ORTHOVA;

CREATE TABLE T2 AS 
SELECT BUNDLETOT_NEW, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_TKR THEN &HIGHCAP_ORTHOVA_TKR 
ELSE BUNDLETOT_NEW
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM FORMAT=DOLLAR11.
FROM TKR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE BUNDLETOT_NEW GE 4000;

CREATE TABLE T3 AS 
SELECT DISTINCT NEWBUNDLE_SUM
FROM T2;

QUIT;

ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - TKR RENEGOTIATION - &SYSDATE..RTF"; 

TITLE 'TKR VA MARKET COMPLICATIONS, READMISSIONS AND REVISIONS';
PROC PRINT DATA=MARKET_COMPS; RUN;

TITLE 'TKR ORTHO VA INITIAL EPISODES';
PROC PRINT DATA=INITIAL_EPS; RUN;

TITLE 'TKR VA MARKET HIGH COST CAP - ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=HIGHCOST; RUN;

TITLE 'TKR ORTHO VA - ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T1; RUN;

TITLE 'TKR ORTHO VA - ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T3; RUN;

ODS RTF CLOSE;

********************************;
*NOT ADJUSTED FOR RENEGOTIATION*;
********************************;

*NOTE: WHEN RUNNING UNADJUSTED NUMBERS USE bundlecost_tot_PCR AND index_prof_SURG_PCR*;

PROC SQL;
*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(bundlecost_tot_PCR)+(2*(STD(bundlecost_tot_PCR)))
INTO :HIGHCAP_ORTHOVA_TKR
FROM TKR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(bundlecost_tot_PCR)+(2*(STD(bundlecost_tot_PCR))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.
FROM TKR_MARKET; 

CREATE TABLE T1 AS
SELECT 
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(bundlecost_tot_PCR) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(bundlecost_tot_PCR<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(bundlecost_tot_PCR>&HIGHCAP_ORTHOVA_TKR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - NOT ADJUSTED FOR RICHMOND RENEGOTIATION*/
MEAN(index_prof_SURG_PCR) AS index_prof_SURG_PCR FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_TKR AS COMPL_PER FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_TKR AS READMIT_PER FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_TKR AS REVISE_PER FORMAT=PERCENT8.1
FROM TKR_ORTHOVA;

CREATE TABLE T2 AS 
SELECT bundlecost_tot_PCR, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN bundlecost_tot_PCR>&HIGHCAP_ORTHOVA_TKR THEN &HIGHCAP_ORTHOVA_TKR 
ELSE bundlecost_tot_PCR
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM FORMAT=DOLLAR11.
FROM TKR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE bundlecost_tot_PCR GE 4000;

CREATE TABLE T3 AS 
SELECT DISTINCT NEWBUNDLE_SUM
FROM T2;

QUIT;

ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - TKR NOT ADJ RENEGOTIATION - &SYSDATE..RTF"; 

TITLE 'TKR VA MARKET HIGH COST CAP - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=HIGHCOST; RUN;

TITLE 'TKR ORTHO VA - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T1; RUN;

TITLE 'TKR ORTHO VA - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T3; RUN;

ODS RTF CLOSE;


***********;
***	THR	***;
***********;

**************************;
**ORTHO VA - ALL MARKETS**;
**************************;

*ALL VALID EPISODES FOR VA MARKET*;

DATA THR_MARKET THR_ORTHOVA;
SET THR_test.VA_THR_CASE_0714_0615_PCR_v1;

/* THR -- VALID Flagging criteria applied here */
if 
DRG_flg=1 AND /* Exclude episodes with the correct surg proc code but incorrect DRG (i.e., 462)*/
			  /* DRG inclusion criteria for index procedure but only apply to IP episodes */
			  /* allows for ASC episodes to not be excluded b/c DRG criteria is not applicable */
ind_flg=1 AND /* index trigger occurred within designated index period exclude 2nd index trigger */
			  /* occurring during experience period but outside of index period -- ind_flg=2 */
cap_flg in (0,2) AND  /* product exclusion criteria episodes with capitation-- cap_flg=1 */
ex_dx_flg=0 AND 	/* clinical historical exclusion criteria */
dx_flg=1 AND 		/* Dx inclusion criteria */
lob_lvl_flg in (1,2,3,4) AND /* Program Participation Exclusions of MCARE and MCAID */					
enrl_flg=1 AND /* continuous enrollment criteria */
lob_flg=1 AND  /* continuous enrolllment in same plan criteria */
age_flg=1 AND  /* minimum age at index service date criteria */
WP_Primary=0 AND /* Anthem primary criteria */
blt_flg=0 AND   /* bilateral exclusion criteria */
hosp_only_flg=0; /* product exclusion criteria */

IF COUNTY_HOPPA IN ('LYNCHBURG CITY','ROANOKE CITY','CHARLOTTESVILLE CITY','SALEM') THEN REGION=1; *LYNCHBURG*;
ELSE IF COUNTY_HOPPA IN ('HENRICO','CHESTERFIELD','HANOVER','RICHMOND CITY','HOPEWELL CITY','PRINCE WILLIAM') THEN REGION=2; *RICHMOND*;
ELSE IF COUNTY_HOPPA IN ('MANASSAS CITY','FAIRFAX','FALLS CHURCH CITY','ALEXANDRIA CITY','ARLINGTON','LOUDOUN','FAUQUIER','HAMILTON') THEN REGION=3; *NORTHERN*;

*READMISSION FLAG*;
IF READMIT_FLG=1 AND (compl_flg=1 OR revise_flg=1) THEN READMISSION=1;
ELSE READMISSION=0;

FAC_TOT=index_fac_cost_PCR+postindex_fac_cost_PCR; *TOTAL FACILITY COSTS*;
PROF_TOT=index_prof_cost_PCR+postindex_prof_cost_PCR; *TOTAL PROFESSIONAL COSTS*;

PROF_NEW=PROF_TOT;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN PROF_NEW=PROF_TOT*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC="PPO" THEN PROF_NEW=PROF_TOT*(0.99728); 

BUNDLETOT_NEW=FAC_TOT+PROF_NEW; *CALCULATING NEW TOTAL BUNDLE COST*;

*NEW SURGEON COSTS ACCOUNTING FOR RENEGOTIATION. USED FOR HISTORICAL CASE RATE*;
SURG_NEW=index_prof_SURG_PCR;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN SURG_NEW=index_prof_SURG_PCR*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') AND 
PROD_LVL_2_DESC="PPO" THEN SURG_NEW=index_prof_SURG_PCR*(0.99728); 

*PER MELISSA GRIFFEN - EXCLUDE VCU (indx_SRC_BILLG_TAX_ID="541848065") FOR RICHMOND (N=0)*;
*ADDED ADVANCED ORTHOPAEDICS TIN (541025125) PER MELISSA G. - 7/12/16*;
IF SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') THEN OUTPUT THR_ORTHOVA; *AND indx_SRC_BILLG_TAX_ID NE "541848065";
OUTPUT THR_MARKET; 

RUN;

*CREATING MACRO VARIABLES FOR THE TOTAL NUMBER OF VALID OBSERVATIONS (TO CALCULATE PERCENTAGES) AND MARKET
COMPLICATIONS/REVISIONS/READMISSIONS.
NOTE: THESE NUMBERS WILL STAY THE SAME REGARDLESS OF RENEGOTIATIONS*;
PROC SQL;
SELECT DISTINCT 
COUNT(*)
INTO :N_ORTHOVA_THR 
FROM THR_ORTHOVA;

*DENOMINATOR FOR COMPLICATION/REVISION/READMISSION RATES*;
SELECT DISTINCT 
COUNT(*)
INTO :N_MARKET_THR 
FROM THR_MARKET;

*CALCULATING MARKET READMISSION/REVISION/COMPLICATION RATES*;
CREATE TABLE MARKET_COMPS AS
SELECT 
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_MARKET_THR AS COMPL_MARKET FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_MARKET_THR AS READMIT_MARKET FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_MARKET_THR AS REVISE_MARKET FORMAT=PERCENT8.1,
1 AS MERGEVAR
FROM THR_MARKET;

*CALCULATING NUMBER OF INITIAL EPISODES (BEFORE EXCLUSION CRITERIA APPLIED)*;
CREATE TABLE INITIAL_EPS AS 
SELECT
/* GENERATE TOPLINE -- Initial Episodes */
SUM (IND_FLG=1 AND DRG_FLG=1 AND LOB_LVL_FLG ne 9) AS INITIAL_EPISODES LABEL='INITIAL EPISODES',
1 AS MERGEVAR
FROM THR_test.VA_THR_CASE_0714_0615_PCR_v1
WHERE SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534');

QUIT;


*********************************;
*RENEGOTIATION OF RICHMOND RATES*;
*********************************;

PROC SQL;
*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW)))
INTO :HIGHCAP_ORTHOVA_THR
FROM THR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.,
1 AS MERGEVAR
FROM THR_MARKET; 

CREATE TABLE T1 AS 
SELECT BUNDLETOT_NEW, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_THR THEN &HIGHCAP_ORTHOVA_THR 
ELSE BUNDLETOT_NEW
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM
FROM THR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE BUNDLETOT_NEW GE 4000;

*CREATING MACRO VARIABLE FOR THE SUM OF THE NEW BUNDLE TO USE BELOW*;
SELECT DISTINCT NEWBUNDLE_SUM
INTO :NEWBUNDLE_SUM
FROM T1;

CREATE TABLE T2 AS
SELECT 
/*NUMBER OF VALID BASELINE EPISODES*/
COUNT(*) AS ELIG_EPS,
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(BUNDLETOT_NEW) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(BUNDLETOT_NEW<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_THR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - ADJUSTING FOR RICHMOND RENEGOTIATION*/
MEAN(SURG_NEW) AS SURG_MEAN FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_THR AS COMPL_PROV FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_THR AS READMIT_PROV FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_THR AS REVISE_PROV FORMAT=PERCENT8.1,
/*OUTLIER ADJUSTED AMOUNT*/
CALCULATED BL_TOT-&NEWBUNDLE_SUM AS ADJ_AMT FORMAT=DOLLAR11. LABEL="OUTLIER ADJUSTED AMOUNT",
1 AS MERGEVAR
FROM THR_ORTHOVA;

QUIT;

PROC SQL;
CREATE TABLE FINAL_THR (DROP=MERGEVAR) AS
SELECT *
FROM INITIAL_EPS AS IE, T2 AS TABLE2, MARKET_COMPS AS MC, HIGHCOST AS HC 
WHERE IE.MERGEVAR=TABLE2.MERGEVAR=MC.MERGEVAR=HC.MERGEVAR
/*ORDER BY 14,1,2,3,4,5,10,6,7,8,9,11,12,13*/; 
QUIT;

ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - THR RENEGOTIATION - &SYSDATE..RTF"; 

PROC PRINT DATA=FINAL_THR; RUN;

ODS RTF CLOSE;

/*PROC FORMAT;*/
/**/
/*VALUE $FINALF "INITIAL_EPISODES"="Topline Number of Total Baseline Episodes"*/
/*				"ELIG_EPS"="Number of Valid Baseline Episodes"*/
/*				"BL_TOT"="Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)"*/
/*				"LOW_REMOVED"="Number of Low Outlier Episodes Removed"*/
/*				"HIGH_CAPPED"="Number of High Outlier Episodes Adjusted"*/
/*				"SURG_MEAN"="Historical Case Rate"*/
/*				"COMPL_PROV"="Provider Complication Rate"*/
/*				"READMIT_PROV"="Provider Readmission Rate"*/
/*				"REVISE_PROV"="Provider Revision Rate"*/
/*				"ADJ_AMT"="Outlier Adjusted Amount"*/
/*				"COMPL_MARKET"="Market Complication Rate"  */
/*				"READMIT_MARKET"="Market Readmission Rate"*/
/*				"REVISE_MARKET"="Market Revision Rate"*/
/*				"HIGHCAP_VAR_ORTHOVA"="Highcap Value";*/
/**/
/*	RUN;*/


ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - THR RENEGOTIATION - &SYSDATE..RTF"; 


ODS RTF CLOSE;

********************************;
*NOT ADJUSTED FOR RENEGOTIATION*;
********************************;

*NOTE: WHEN RUNNING UNADJUSTED NUMBERS USE bundlecost_tot_PCR AND index_prof_SURG_PCR*;

PROC SQL;
*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(bundlecost_tot_PCR)+(2*(STD(bundlecost_tot_PCR)))
INTO :HIGHCAP_ORTHOVA_THR
FROM THR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(bundlecost_tot_PCR)+(2*(STD(bundlecost_tot_PCR))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.
FROM THR_MARKET; 

CREATE TABLE T1 AS
SELECT 
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(bundlecost_tot_PCR) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(bundlecost_tot_PCR<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(bundlecost_tot_PCR>&HIGHCAP_ORTHOVA_THR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - NOT ADJUSTED FOR RICHMOND RENEGOTIATION*/
MEAN(index_prof_SURG_PCR) AS index_prof_SURG_PCR FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_THR AS COMPL_PER FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_THR AS READMIT_PER FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_THR AS REVISE_PER FORMAT=PERCENT8.1
FROM THR_ORTHOVA;

CREATE TABLE T2 AS 
SELECT bundlecost_tot_PCR, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN bundlecost_tot_PCR>&HIGHCAP_ORTHOVA_THR THEN &HIGHCAP_ORTHOVA_THR 
ELSE bundlecost_tot_PCR
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM FORMAT=DOLLAR11.
FROM THR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE bundlecost_tot_PCR GE 4000;

CREATE TABLE T3 AS 
SELECT DISTINCT NEWBUNDLE_SUM
FROM T2;

QUIT;

ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - THR NOT ADJ RENEGOTIATION - &SYSDATE..RTF"; 

TITLE 'THR VA MARKET HIGH COST CAP - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=HIGHCOST; RUN;

TITLE 'THR ORTHO VA - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T1; RUN;

TITLE 'THR ORTHO VA - NOT ADJUSTED FOR RENEGOTIATION';
PROC PRINT DATA=T3; RUN;

ODS RTF CLOSE;

*****************************;
*	PROGRAM USED 7/19/16	*;
*****************************;

*NOTE: PROGRAM ADJUSTS FOR RENEGOTIATIONS IN RICHMOND REGION*;

***********;
*** THR ***;
***********;

*ALL VALID EPISODES FOR VA MARKET*;

DATA THR_MARKET THR_ORTHOVA;
SET THR_test.VA_THR_CASE_0714_0615_PCR_v1;

/* THR -- VALID Flagging criteria applied here */
if 
DRG_flg=1 AND /* Exclude episodes with the correct surg proc code but incorrect DRG (i.e., 462)*/
			  /* DRG inclusion criteria for index procedure but only apply to IP episodes */
			  /* allows for ASC episodes to not be excluded b/c DRG criteria is not applicable */
ind_flg=1 AND /* index trigger occurred within designated index period exclude 2nd index trigger */
			  /* occurring during experience period but outside of index period -- ind_flg=2 */
cap_flg in (0,2) AND  /* product exclusion criteria episodes with capitation-- cap_flg=1 */
ex_dx_flg=0 AND 	/* clinical historical exclusion criteria */
dx_flg=1 AND 		/* Dx inclusion criteria */
lob_lvl_flg in (1,2,3,4) AND /* Program Participation Exclusions of MCARE and MCAID */					
enrl_flg=1 AND /* continuous enrollment criteria */
lob_flg=1 AND  /* continuous enrolllment in same plan criteria */
age_flg=1 AND  /* minimum age at index service date criteria */
WP_Primary=0 AND /* Anthem primary criteria */
blt_flg=0 AND   /* bilateral exclusion criteria */
hosp_only_flg=0; /* product exclusion criteria */

IF COUNTY_HOPPA IN ('LYNCHBURG CITY','ROANOKE CITY','CHARLOTTESVILLE CITY','SALEM') THEN REGION=1; *LYNCHBURG*;
ELSE IF COUNTY_HOPPA IN ('HENRICO','CHESTERFIELD','HANOVER','RICHMOND CITY','HOPEWELL CITY','PRINCE WILLIAM') THEN REGION=2; *RICHMOND*;
ELSE IF COUNTY_HOPPA IN ('MANASSAS CITY','FAIRFAX','FALLS CHURCH CITY','ALEXANDRIA CITY','ARLINGTON','LOUDOUN','FAUQUIER','HAMILTON') THEN REGION=3; *NORTHERN*;

*READMISSION FLAG*;
IF READMIT_FLG=1 AND (compl_flg=1 OR revise_flg=1) THEN READMISSION=1;
ELSE READMISSION=0;

FAC_TOT=index_fac_cost_PCR+postindex_fac_cost_PCR; *TOTAL FACILITY COSTS*;
PROF_TOT=index_prof_cost_PCR+postindex_prof_cost_PCR; *TOTAL PROFESSIONAL COSTS*;

PROF_NEW=PROF_TOT;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN PROF_NEW=PROF_TOT*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC="PPO" THEN PROF_NEW=PROF_TOT*(0.99728); 

BUNDLETOT_NEW=FAC_TOT+PROF_NEW; *CALCULATING NEW TOTAL BUNDLE COST*;

*NEW SURGEON COSTS ACCOUNTING FOR RENEGOTIATION. USED FOR HISTORICAL CASE RATE*;
SURG_NEW=index_prof_SURG_PCR;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN SURG_NEW=index_prof_SURG_PCR*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC="PPO" THEN SURG_NEW=index_prof_SURG_PCR*(0.99728); 

*PER MELISSA GRIFFEN - EXCLUDE VCU (indx_SRC_BILLG_TAX_ID="541848065") FOR RICHMOND (N=0)*;
*ADDED ADVANCED ORTHOPAEDICS TIN (541025125) PER MELISSA G. - 7/12/16*;
IF SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') THEN OUTPUT THR_ORTHOVA; *AND indx_SRC_BILLG_TAX_ID NE "541848065";
OUTPUT THR_MARKET; 

RUN;


*CREATING MACRO VARIABLES FOR THE TOTAL NUMBER OF VALID OBSERVATIONS (TO CALCULATE PERCENTAGES) AND MARKET
COMPLICATIONS/REVISIONS/READMISSIONS.
NOTE: THESE NUMBERS WILL STAY THE SAME REGARDLESS OF RENEGOTIATIONS*;
PROC SQL;
SELECT DISTINCT 
COUNT(*)
INTO :N_ORTHOVA_THR 
FROM THR_ORTHOVA;

*DENOMINATOR FOR COMPLICATION/REVISION/READMISSION RATES*;
SELECT DISTINCT 
COUNT(*)
INTO :N_MARKET_THR 
FROM THR_MARKET;

*CALCULATING RICHMOND MARKET READMISSION/REVISION/COMPLICATION RATES*;
CREATE TABLE MARKET_COMPS AS
SELECT 
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_MARKET_THR AS COMPL_MARKET FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_MARKET_THR AS READMIT_MARKET FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_MARKET_THR AS REVISE_MARKET FORMAT=PERCENT8.1,
1 AS MERGEVAR
FROM THR_MARKET;

*CALCULATING NUMBER OF INITIAL EPISODES (BEFORE EXCLUSION CRITERIA APPLIED)*;
CREATE TABLE INITIAL_EPS AS 
SELECT
/* GENERATE TOPLINE -- Initial Episodes */
SUM (IND_FLG=1 AND DRG_FLG=1 AND LOB_LVL_FLG ne 9) AS INITIAL_EPISODES LABEL='INITIAL EPISODES',
1 AS MERGEVAR
FROM THR_test.VA_THR_CASE_0714_0615_PCR_v1
WHERE SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534');

*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW)))
INTO :HIGHCAP_ORTHOVA_THR
FROM THR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.,
1 AS MERGEVAR
FROM THR_MARKET; 

CREATE TABLE T1 AS 
SELECT BUNDLETOT_NEW, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_THR THEN &HIGHCAP_ORTHOVA_THR 
ELSE BUNDLETOT_NEW
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM
FROM THR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE BUNDLETOT_NEW GE 4000;

*CREATING MACRO VARIABLE FOR THE SUM OF THE NEW BUNDLE TO USE BELOW*;
SELECT DISTINCT NEWBUNDLE_SUM
INTO :NEWBUNDLE_SUM
FROM T1;

CREATE TABLE T2 AS
SELECT 
/*NUMBER OF VALID BASELINE EPISODES*/
COUNT(*) AS ELIG_EPS,
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(BUNDLETOT_NEW) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(BUNDLETOT_NEW<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_THR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - ADJUSTING FOR RICHMOND RENEGOTIATION*/
MEAN(SURG_NEW) AS SURG_MEAN FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_THR AS COMPL_PROV FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_THR AS READMIT_PROV FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_THR AS REVISE_PROV FORMAT=PERCENT8.1,
/*OUTLIER ADJUSTED AMOUNT*/
CALCULATED BL_TOT-&NEWBUNDLE_SUM AS ADJ_AMT FORMAT=DOLLAR11. LABEL="OUTLIER ADJUSTED AMOUNT",
1 AS MERGEVAR
FROM THR_ORTHOVA;

CREATE TABLE FINAL_THR (DROP=MERGEVAR) AS
SELECT *
FROM INITIAL_EPS AS IE, T2 AS TABLE2, MARKET_COMPS AS MC, HIGHCOST AS HC 
WHERE IE.MERGEVAR=TABLE2.MERGEVAR=MC.MERGEVAR=HC.MERGEVAR
/*ORDER BY 14,1,2,3,4,5,10,6,7,8,9,11,12,13*/; 
QUIT;


*******************************************************************************;

***********;
*** TKR ***;
***********;

*ALL VALID EPISODES FOR VA MARKET*;

DATA TKR_MARKET TKR_ORTHOVA;
SET TKR_test.VA_TKR_CASE_0714_0615_PCR_v1;

/* TKR -- VALID Flagging criteria applied here */
if 
DRG_flg=1 AND /* Exclude episodes with the correct surg proc code but incorrect DRG (i.e., 462)*/
			  /* DRG inclusion criteria for index procedure but only apply to IP episodes */
			  /* allows for ASC episodes to not be excluded b/c DRG criteria is not applicable */
ind_flg=1 AND /* index trigger occurred within designated index period exclude 2nd index trigger */
			  /* occurring during experience period but outside of index period -- ind_flg=2 */
cap_flg in (0,2) AND  /* product exclusion criteria episodes with capitation-- cap_flg=1 */
ex_dx_flg=0 AND 	/* clinical historical exclusion criteria */
dx_flg=1 AND 		/* Dx inclusion criteria */
lob_lvl_flg in (1,2,3,4) AND /* Program Participation Exclusions of MCARE and MCAID */					
enrl_flg=1 AND /* continuous enrollment criteria */
lob_flg=1 AND  /* continuous enrolllment in same plan criteria */
age_flg=1 AND  /* minimum age at index service date criteria */
WP_Primary=0 AND /* Anthem primary criteria */
blt_flg=0 AND   /* bilateral exclusion criteria */
hosp_only_flg=0; /* product exclusion criteria */

IF COUNTY_HOPPA IN ('LYNCHBURG CITY','ROANOKE CITY','CHARLOTTESVILLE CITY','SALEM') THEN REGION=1; *LYNCHBURG*;
ELSE IF COUNTY_HOPPA IN ('HENRICO','CHESTERFIELD','HANOVER','RICHMOND CITY','HOPEWELL CITY','PRINCE WILLIAM') THEN REGION=2; *RICHMOND*;
ELSE IF COUNTY_HOPPA IN ('MANASSAS CITY','FAIRFAX','FALLS CHURCH CITY','ALEXANDRIA CITY','ARLINGTON','LOUDOUN','FAUQUIER','HAMILTON') THEN REGION=3; *NORTHERN*;

*READMISSION FLAG*;
IF READMIT_FLG=1 AND (compl_flg=1 OR revise_flg=1) THEN READMISSION=1;
ELSE READMISSION=0;

FAC_TOT=index_fac_cost_PCR+postindex_fac_cost_PCR; *TOTAL FACILITY COSTS*;
PROF_TOT=index_prof_cost_PCR+postindex_prof_cost_PCR; *TOTAL PROFESSIONAL COSTS*;

PROF_NEW=PROF_TOT;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN PROF_NEW=PROF_TOT*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC="PPO" THEN PROF_NEW=PROF_TOT*(0.99728); 

BUNDLETOT_NEW=FAC_TOT+PROF_NEW; *CALCULATING NEW TOTAL BUNDLE COST*;

*NEW SURGEON COSTS ACCOUNTING FOR RENEGOTIATION. USED FOR HISTORICAL CASE RATE*;
SURG_NEW=index_prof_SURG_PCR;
IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC IN ("HMO","POS") THEN SURG_NEW=index_prof_SURG_PCR*(0.94974); 
ELSE IF REGION=2 AND SURGEON_TIN IN ('540885859','202159335','541025125') 
AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') AND 
PROD_LVL_2_DESC="PPO" THEN SURG_NEW=index_prof_SURG_PCR*(0.99728); 

*PER MELISSA GRIFFEN - EXCLUDE VCU (indx_SRC_BILLG_TAX_ID="541848065") FOR RICHMOND (N=0)*;
*ADDED ADVANCED ORTHOPAEDICS TIN (541025125) PER MELISSA G. - 7/12/16*;
IF SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534') THEN OUTPUT TKR_ORTHOVA; *AND indx_SRC_BILLG_TAX_ID NE "541848065";
OUTPUT TKR_MARKET; 

RUN;

*CREATING MACRO VARIABLES FOR THE TOTAL NUMBER OF VALID OBSERVATIONS (TO CALCULATE PERCENTAGES) AND MARKET
COMPLICATIONS/REVISIONS/READMISSIONS.
NOTE: THESE NUMBERS WILL STAY THE SAME REGARDLESS OF RENEGOTIATIONS*;
PROC SQL;
SELECT DISTINCT 
COUNT(*)
INTO :N_ORTHOVA_TKR 
FROM TKR_ORTHOVA;

*DENOMINATOR FOR COMPLICATION/REVISION/READMISSION RATES*;
SELECT DISTINCT 
COUNT(*)
INTO :N_MARKET_TKR 
FROM TKR_MARKET;

*CALCULATING RICHMOND MARKET READMISSION/REVISION/COMPLICATION RATES*;
CREATE TABLE MARKET_COMPS AS
SELECT 
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_MARKET_TKR AS COMPL_MARKET FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_MARKET_TKR AS READMIT_MARKET FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_MARKET_TKR AS REVISE_MARKET FORMAT=PERCENT8.1,
1 AS MERGEVAR
FROM TKR_MARKET;

*CALCULATING NUMBER OF INITIAL EPISODES (BEFORE EXCLUSION CRITERIA APPLIED)*;
CREATE TABLE INITIAL_EPS AS 
SELECT
/* GENERATE TOPLINE -- Initial Episodes */
SUM (IND_FLG=1 AND DRG_FLG=1 AND LOB_LVL_FLG ne 9) AS INITIAL_EPISODES LABEL='INITIAL EPISODES',
1 AS MERGEVAR
FROM TKR_test.VA_TKR_CASE_0714_0615_PCR_v1
WHERE SURGEON_TIN IN ('540885859','202159335','541025125') AND billg_tax_id_hoppa NOT IN ('541779911','621113733','611272888','621777534');

*CREATING MACRO VARIABLE FOR HIGH COST*;
SELECT 
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW)))
INTO :HIGHCAP_ORTHOVA_TKR
FROM TKR_MARKET;

*CREATING VARIABLE FOR HIGH COST FOR OUTPUTTING*;
CREATE TABLE HIGHCOST AS
SELECT
/*HIGH OUTLIER CAP*/
MEAN(BUNDLETOT_NEW)+(2*(STD(BUNDLETOT_NEW))) AS HIGHCAP_VAR_ORTHOVA FORMAT=DOLLAR11.,
1 AS MERGEVAR
FROM TKR_MARKET; 

CREATE TABLE T1 AS 
SELECT BUNDLETOT_NEW, 
CASE
/*ADJUSTING COSTS TO HIGH CAP*/
WHEN BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_TKR THEN &HIGHCAP_ORTHOVA_TKR 
ELSE BUNDLETOT_NEW
END AS NEWBUNDLE_TOT,
/*Total Outlier Adjusted Allowed Dollars for Valid Episodes*/
SUM(CALCULATED NEWBUNDLE_TOT) AS NEWBUNDLE_SUM
FROM TKR_ORTHOVA
/*ONLY FOR CASES OVER $4K, IF UNDER THEY ARE EXCLUDED*/
WHERE BUNDLETOT_NEW GE 4000;

*CREATING MACRO VARIABLE FOR THE SUM OF THE NEW BUNDLE TO USE BELOW*;
SELECT DISTINCT NEWBUNDLE_SUM
INTO :NEWBUNDLE_SUM
FROM T1;

CREATE TABLE T2 AS
SELECT 
/*NUMBER OF VALID BASELINE EPISODES*/
COUNT(*) AS ELIG_EPS,
/*Total Actual Baseline Allowed Dollars for Valid Episodes (prior to outlier adjustment)*/
SUM(BUNDLETOT_NEW) AS BL_TOT FORMAT=DOLLAR11.,
/*Number of Low Outlier Episodes Removed*/
SUM(BUNDLETOT_NEW<4000) AS LOW_REMOVED,
/*Number of High Outlier Episodes Adjusted*/
SUM(BUNDLETOT_NEW>&HIGHCAP_ORTHOVA_TKR) AS HIGH_CAPPED,
/*SIMPLE HISTORICAL CASE RATE - ADJUSTING FOR RICHMOND RENEGOTIATION*/
MEAN(SURG_NEW) AS SURG_MEAN FORMAT=DOLLAR11.,
/*COMPLICATION RATE*/
SUM(COMPL_FLG)/&N_ORTHOVA_TKR AS COMPL_PROV FORMAT=PERCENT8.1,
/*READMISSION RATE*/
SUM(READMISSION)/&N_ORTHOVA_TKR AS READMIT_PROV FORMAT=PERCENT8.1,
/*REVISION RATE*/
SUM(REVISE_FLG)/&N_ORTHOVA_TKR AS REVISE_PROV FORMAT=PERCENT8.1,
/*OUTLIER ADJUSTED AMOUNT*/
CALCULATED BL_TOT-&NEWBUNDLE_SUM AS ADJ_AMT FORMAT=DOLLAR11. LABEL="OUTLIER ADJUSTED AMOUNT",
1 AS MERGEVAR
FROM TKR_ORTHOVA;

CREATE TABLE FINAL_TKR (DROP=MERGEVAR) AS
SELECT *
FROM INITIAL_EPS AS IE, T2 AS TABLE2, MARKET_COMPS AS MC, HIGHCOST AS HC 
WHERE IE.MERGEVAR=TABLE2.MERGEVAR=MC.MERGEVAR=HC.MERGEVAR
/*ORDER BY 14,1,2,3,4,5,10,6,7,8,9,11,12,13*/; 
QUIT;



ODS RTF FILE="/ephc/ebp/nobackup/users/blase/ORTHO VA - TPR RENEGOTIATION - &SYSDATE..RTF"; 

TITLE 'THR'; PROC PRINT DATA=FINAL_THR; RUN;
TITLE 'TKR'; PROC PRINT DATA=FINAL_TKR; RUN;
TITLE;

ODS RTF CLOSE;
