*****************************************************************************;
*	PROGRAMMER: JENNY BLASE 												*;
*	PROGRAM FOR CPS3 PHYSICAL ACTIVITY AND ANTHROPOMETRY DERIVATION			*;
*	LAST MODIFIED: JUNE 23, 2015											*;
*****************************************************************************;

LIBNAME CPS3DAT 'D:\CPS\CPS3';
OPTIONS MPRINT;

DATA ALL;
*RENAMING VARS TO HARMONIZE MENS AND WOMENS VERSIONS*;
MERGE CPS3DAT.allwomenr_2006_2013 (IN=ENROLL KEEP= ID VERSION HEIGHTFT HEIGHTIN WTCURR HEIGHTAGE WT18 EATDRINK WALKED15 PHYSHLTH SLEEP_WKDY 
	  SLEEP_WKEND EXER_WKDY EXER_WKEND SITTV_WKDY SITTV_WKEND OTSIT_WKDY OTSIT_WKEND STND_WKDY STND_WKEND WT10NO WT10LOSS WT10GAIN RENAME = (VERSION=VERSION_E))

	  CPS3DAT.fullenroll_bline_women (IN=BLINE_I KEEP=ID VERSION AGE_INTB Q68SLWDAY Q68SLWEND Q68EXWDAY Q68EXWEND Q68SIWDAY
		Q68SIWEND Q68OTSIWDAY Q68OTSIWEND Q68STWDAY Q68STWEND Q67WALKHR Q67WALKMO Q67JOGHR Q67JOGMO Q67RUNHR Q67RUNMO Q67BIKEHR Q67BIKEMO Q67TENHR Q67TENMO Q67SWIMHR 
		Q67SWIMMO Q67AERHR Q67AERMO Q67ELLHR Q67ELLMO Q67SPOHR Q67SPOMO Q67DANCEHR Q67DANCEMO Q67OAERHR Q67OAERMO Q67CALHR Q67CALMO Q67YOGAHR Q67YOGAMO Q67WGTTRHR 
		Q67WGTTRMO Q67YARDHR Q67YARDMO Q67WALK Q67JOG Q67RUN Q67BIKE Q67TEN Q67SWIM Q67AER Q67ELL Q67SPO Q67DANCE Q67OAER Q67CAL Q67YOGA Q67WGTTR Q67YARD Q65 Q66 
		Q71_2YRS Q71LT18 Q71_18 Q71_25 Q71_30 Q71_40 Q71_50 Q69_2YRSHR Q69_2YRSMO Q69LT18HR Q69LT18MO Q69_18HR Q69_18MO Q69_25HR Q69_25MO Q69_30HR Q69_30MO Q69_40HR Q69_40MO 
		Q69_50HR Q69_50MO Q70_2YRSHR Q70_2YRSMO Q70LT18HR Q70LT18MO Q70_18HR Q70_18MO Q70_25HR Q70_25MO Q70_30HR Q70_30MO Q70_40HR Q70_40MO Q70_50HR Q70_50MO Q68_2YRSHR_06 
		Q68_2YRSMO_06 Q68LT18HR_06 Q68LT18MO_06 Q68_18HR_06 Q68_18MO_06 Q68_25HR_06 Q68_25MO_06 Q68_30HR_06 Q68_30MO_06 Q68_40HR_06 Q68_40MO_06 Q68_50HR_06
		Q68_50MO_06 Q3FT Q3IN Q3AGE Q4WEIGHT Q5WEIGHT Q6WEIGHT Q8TIMES Q11HEALTH Q9SHAPE Q10GAIN Q7AWEIGHT Q7BWEIGHT Q7CWEIGHT Q7DWEIGHT Q7C1 Q7D1


		RENAME = (VERSION=VERSION_BL Q68SLWDAY=BL_SLWDAY Q68SLWEND=BL_SLWEND Q68EXWDAY=BL_EXWDAY Q68EXWEND=BL_EXWEND Q68SIWDAY=BL_SIWDAY 
		Q68SIWEND=BL_SIWEND Q68OTSIWDAY=BL_OTSIWDAY Q68OTSIWEND=BL_OTSIWEND Q68STWDAY=BL_STWDAY Q68STWEND=BL_STWEND Q67WALKHR=BL_WALKHR Q67WALKMO=BL_WALKMO Q67JOGHR=BL_JOGHR 
		Q67JOGMO=BL_JOGMO Q67RUNHR=BL_RUNHR Q67RUNMO=BL_RUNMO Q67BIKEHR=BL_BIKEHR Q67BIKEMO=BL_BIKEMO Q67TENHR=BL_TENHR Q67TENMO=BL_TENMO Q67SWIMHR=BL_SWIMHR Q67SWIMMO=BL_SWIMMO 
		Q67AERHR=BL_AERHR Q67AERMO=BL_AERMO Q67ELLHR=BL_ELLHR Q67ELLMO=BL_ELLMO Q67SPOHR=BL_SPOHR Q67SPOMO=BL_SPOMO Q67DANCEHR=BL_DANCEHR Q67DANCEMO=BL_DANCEMO Q67OAERHR=BL_OAERHR 
		Q67OAERMO=BL_OAERMO Q67CALHR=BL_CALHR Q67CALMO=BL_CALMO Q67YOGAHR=BL_YOGAHR Q67YOGAMO=BL_YOGAMO Q67WGTTRHR=BL_WGTTRHR Q67WGTTRMO=BL_WGTTRMO Q67YARDHR=BL_YARDHR 
		Q67YARDMO=BL_YARDMO Q67WALK=BL_WALK Q67JOG=BL_JOG Q67RUN=BL_RUN Q67BIKE=BL_BIKE Q67TEN=BL_TEN Q67SWIM=BL_SWIM Q67AER=BL_AER Q67ELL=BL_ELL Q67SPO=BL_SPORT Q67DANCE=BL_DANCE 
		Q67OAER=BL_OAER Q67CAL=BL_CAL Q67YOGA=BL_YOGA Q67WGTTR=BL_WGTTR Q67YARD=BL_YARD Q65=BL_DISAB Q66=BL_PACE Q71_2YRS=BL_WORK2YRS Q71LT18=BL_WORKLT18 Q71_18=BL_WORK18 
		Q71_25=BL_WORK25 Q71_30=BL_WORK30 Q71_40=BL_WORK40 Q71_50=BL_WORK50 Q69_2YRSHR=BL_MOD2YRSHR Q69_2YRSMO=BL_MOD2YRSMO Q69LT18HR=BL_MODLT18HR Q69LT18MO=BL_MODLT18MO 
		Q69_18HR=BL_MOD18HR Q69_18MO=BL_MOD18MO Q69_25HR=BL_MOD25HR Q69_25MO=BL_MOD25MO Q69_30HR=BL_MOD30HR Q69_30MO=BL_MOD30MO Q69_40HR=BL_MOD40HR	Q69_40MO=BL_MOD40MO 
		Q69_50HR=BL_MOD50HR Q69_50MO=BL_MOD50MO Q70_2YRSHR=BL_STREN2YRSHR Q70_2YRSMO=BL_STREN2YRSMO Q70LT18HR=BL_STRENLT18HR Q70LT18MO=BL_STRENLT18MO Q70_18HR=BL_STREN18HR 
		Q70_18MO=BL_STREN18MO Q70_25HR=BL_STREN25HR Q70_25MO=BL_STREN25MO Q70_30HR=BL_STREN30HR Q70_30MO=BL_STREN30MO Q70_40HR=BL_STREN40HR Q70_40MO=BL_STREN40MO 
		Q70_50HR=BL_STREN50HR Q70_50MO=BL_STREN50MO Q68_2YRSHR_06=BL_2YRSHR Q68_2YRSMO_06=BL_2YRSMO Q68LT18HR_06=BL_LT18HR Q68LT18MO_06=BL_LT18MO Q68_18HR_06=BL_18HR 
		Q68_18MO_06=BL_18MO Q68_25HR_06=BL_25HR Q68_25MO_06=BL_25MO Q68_30HR_06=BL_30HR Q68_30MO_06=BL_30MO Q68_40HR_06=BL_40HR Q68_40MO_06=BL_40MO Q68_50HR_06=BL_50HR
		Q68_50MO_06=BL_50MO Q7AWEIGHT=WT20_B Q7BWEIGHT=WT30_B Q7CWEIGHT=WT40_B Q7DWEIGHT=WT50_B))


	  CPS3DAT.allmenenr_2006_2013 (IN=ENROLL KEEP= ID VERSION HEIGHTFT HEIGHTIN WTCURR HEIGHTAGE WT18 EATDRINK WALKED15 PHYSHLTH SLEEP_WKDY 
	  SLEEP_WKEND EXER_WKDY EXER_WKEND SITTV_WKDY SITTV_WKEND OTSIT_WKDY OTSIT_WKEND STND_WKDY STND_WKEND WT10NO WT10LOSS WT10GAIN RENAME = (VERSION=VERSION_E))

	  CPS3DAT.fullenroll_bline_men (IN=BLINE_I KEEP=ID VERSION AGE_INTB Q43SLWDAY Q43SLWEND Q43EXWDAY Q43EXWEND Q43SIWDAY Q43SIWEND Q43OTSIWDAY Q43OTSIWEND Q43STWDAY 
		Q43STWEND Q42WALKHR Q42WALKMO Q42JOGHR Q42JOGMO Q42RUNHR Q42RUNMO Q42BIKEHR Q42BIKEMO Q42TENHR Q42TENMO Q42SWIMHR Q42SWIMMO Q42AERHR Q42AERMO Q42ELLHR Q42ELLMO 
		Q42SPOHR Q42SPOMO Q42DANCEHR Q42DANCEMO Q42OAERHR Q42OAERMO Q42CALHR Q42CALMO Q42YOGAHR Q42YOGAMO Q42WGTTRHR Q42WGTTRMO Q42YARDHR Q42YARDMO Q42WALK Q42JOG 
		Q42RUN Q42BIKE Q42TEN Q42SWIM Q42AER Q42ELL Q42SPO Q42DANCE Q42OAER Q42CAL Q42YOGA Q42WGTTR Q42YARD Q40 Q41 Q46_2YRS Q46LT18 Q46_18 Q46_25 Q46_30 Q46_40 
		Q46_50 Q44_2YRSHR Q44_2YRSMO Q44LT18HR Q44LT18MO Q44_18HR Q44_18MO Q44_25HR Q44_25MO Q44_30HR Q44_30MO Q44_40HR Q44_40MO Q44_50HR Q44_50MO Q45_2YRSHR Q45_2YRSMO 
		Q45LT18HR Q45LT18MO Q45_18HR Q45_18MO Q45_25HR Q45_25MO Q45_30HR Q45_30MO Q45_40HR Q45_40MO Q45_50HR Q45_50MO Q43_2YRSHR_06 Q43_2YRSMO_06 Q43LT18HR_06 Q43LT18MO_06 
		Q43_18HR_06 Q43_18MO_06 Q43_25HR_06 Q43_25MO_06 Q43_30HR_06 Q43_30MO_06 Q43_40HR_06 Q43_40MO_06 Q43_50HR_06 Q43_50MO_06 Q3FT Q3IN Q3AGE Q4WEIGHT Q5WEIGHT Q6WEIGHT 
		Q8TIMES Q11HEALTH Q9SHAPE Q10GAIN Q7AWEIGHT Q7BWEIGHT Q7CWEIGHT Q7DWEIGHT Q7C1 Q7D1

		RENAME = (VERSION=VERSION_BL Q43SLWDAY=BL_SLWDAY Q43SLWEND=BL_SLWEND Q43EXWDAY=BL_EXWDAY Q43EXWEND=BL_EXWEND Q43SIWDAY=BL_SIWDAY 
		Q43SIWEND=BL_SIWEND Q43OTSIWDAY=BL_OTSIWDAY Q43OTSIWEND=BL_OTSIWEND Q43STWDAY=BL_STWDAY Q43STWEND=BL_STWEND Q42WALKHR=BL_WALKHR Q42WALKMO=BL_WALKMO Q42JOGHR=BL_JOGHR 
		Q42JOGMO=BL_JOGMO Q42RUNHR=BL_RUNHR Q42RUNMO=BL_RUNMO Q42BIKEHR=BL_BIKEHR Q42BIKEMO=BL_BIKEMO Q42TENHR=BL_TENHR Q42TENMO=BL_TENMO Q42SWIMHR=BL_SWIMHR Q42SWIMMO=BL_SWIMMO 
		Q42AERHR=BL_AERHR Q42AERMO=BL_AERMO Q42ELLHR=BL_ELLHR Q42ELLMO=BL_ELLMO Q42SPOHR=BL_SPOHR Q42SPOMO=BL_SPOMO Q42DANCEHR=BL_DANCEHR Q42DANCEMO=BL_DANCEMO Q42OAERHR=BL_OAERHR 
		Q42OAERMO=BL_OAERMO Q42CALHR=BL_CALHR Q42CALMO=BL_CALMO Q42YOGAHR=BL_YOGAHR Q42YOGAMO=BL_YOGAMO Q42WGTTRHR=BL_WGTTRHR Q42WGTTRMO=BL_WGTTRMO Q42YARDHR=BL_YARDHR 
		Q42YARDMO=BL_YARDMO Q42WALK=BL_WALK Q42JOG=BL_JOG Q42RUN=BL_RUN Q42BIKE=BL_BIKE Q42TEN=BL_TEN Q42SWIM=BL_SWIM Q42AER=BL_AER Q42ELL=BL_ELL Q42SPO=BL_SPORT Q42DANCE=BL_DANCE 
		Q42OAER=BL_OAER Q42CAL=BL_CAL Q42YOGA=BL_YOGA Q42WGTTR=BL_WGTTR Q42YARD=BL_YARD Q40=BL_DISAB Q41=BL_PACE Q46_2YRS=BL_WORK2YRS Q46LT18=BL_WORKLT18 Q46_18=BL_WORK18 
		Q46_25=BL_WORK25 Q46_30=BL_WORK30 Q46_40=BL_WORK40 Q46_50=BL_WORK50 Q44_2YRSHR=BL_MOD2YRSHR Q44_2YRSMO=BL_MOD2YRSMO Q44LT18HR=BL_MODLT18HR Q44LT18MO=BL_MODLT18MO 
		Q44_18HR=BL_MOD18HR Q44_18MO=BL_MOD18MO Q44_25HR=BL_MOD25HR Q44_25MO=BL_MOD25MO Q44_30HR=BL_MOD30HR Q44_30MO=BL_MOD30MO Q44_40HR=BL_MOD40HR	Q44_40MO=BL_MOD40MO 
		Q44_50HR=BL_MOD50HR Q44_50MO=BL_MOD50MO Q45_2YRSHR=BL_STREN2YRSHR Q45_2YRSMO=BL_STREN2YRSMO Q45LT18HR=BL_STRENLT18HR Q45LT18MO=BL_STRENLT18MO Q45_18HR=BL_STREN18HR 
		Q45_18MO=BL_STREN18MO Q45_25HR=BL_STREN25HR Q45_25MO=BL_STREN25MO Q45_30HR=BL_STREN30HR Q45_30MO=BL_STREN30MO Q45_40HR=BL_STREN40HR Q45_40MO=BL_STREN40MO 
		Q45_50HR=BL_STREN50HR Q45_50MO=BL_STREN50MO Q43_2YRSHR_06=BL_2YRSHR Q43_2YRSMO_06=BL_2YRSMO Q43LT18HR_06=BL_LT18HR Q43LT18MO_06=BL_LT18MO Q43_18HR_06=BL_18HR 
		Q43_18MO_06=BL_18MO Q43_25HR_06=BL_25HR Q43_25MO_06=BL_25MO Q43_30HR_06=BL_30HR Q43_30MO_06=BL_30MO Q43_40HR_06=BL_40HR Q43_40MO_06=BL_40MO Q43_50HR_06=BL_50HR
		Q43_50MO_06=BL_50MO Q7AWEIGHT=WT20_B Q7BWEIGHT=WT30_B Q7CWEIGHT=WT40_B Q7DWEIGHT=WT50_B))
	;

BY ID;


%****************************************************************************************;
%* OVARCON MACRO	*;
%* CONVERTS ORIGINAL CHECKBOX CHARACTER VARIABLES TO NUMERIC VARIABLES	*;
%* PARAMETERS:	*;
%* WRITEIN: WHETHER THE QUESTION IS A CHECKBOX OR WRITEIN (NUMERIC) (0 CHECKBOX, 1 WRITEIN) *;
%* OLDVAR: ORIGINAL CHARACTER VARIABLE BEING CONVERTED	*;
%* NEWVAR: NEW NUMERIC VARIABLE BEING CREATED	*;
%* NUM: LENGTH OF NUMERIC VARIABLE	*;
%* BL_EN: BASELINE OR ENROLLMENT VERSION (VERSION_BL OR VERSION_E)	*;
%* VERSION: YEAR OF BASELINE OR ENROLLMENT VERSION	*;
%* VARLABEL: LABEL FOR VARIABLE	*;
%* NA: IF SURVEY WASNT ASKED ON ANY VERSIONS (1=NOT ASKED) - IF QUESTION ASKED ON EVERY SURVEY THEN LEAVE THIS BLANK*;
%****************************************************************************** **********;

%MACRO OVARCON (WRITEIN=,NEWVAR=,OLDVAR=,NUM=,BL_EN=,NA=,VERSION=,VARLABEL=);


%IF &WRITEIN=0 %THEN %DO;
	&NEWVAR=INPUT(&OLDVAR, ?? &NUM..); 
	IF &BL_EN NE ' ' AND &OLDVAR = ' ' THEN &NEWVAR=.M; 
	ELSE IF &OLDVAR='*' THEN &NEWVAR=.U;
		%IF &NA=1 %THEN %DO; 
			IF &BL_EN IN ("&VERSION") THEN &NEWVAR=.N;
		%END;	
%END;

%IF &WRITEIN=1 %THEN %DO;
	&NEWVAR=&OLDVAR;
%END;

LABEL &NEWVAR="&VARLABEL"; 

%MEND OVARCON;
**********;
*BASELINE*;
**********;

%OVARCON (WRITEIN=1, NEWVAR=HEIGHTFT_B, OLDVAR=Q3FT, BL_EN=VERSION_BL, VARLABEL=HEIGHT IN FEET - BASELINE); *HEIGHT IN FEET*;
%OVARCON (WRITEIN=1, NEWVAR=HEIGHTIN_B, OLDVAR=Q3IN, BL_EN=VERSION_BL, VARLABEL=HEIGHT IN INCHES - BASELINE); *HEIGHT IN INCHES*;
%OVARCON (WRITEIN=1, NEWVAR=HEIGHTAGE_B, OLDVAR=Q3AGE, BL_EN=VERSION_BL, VARLABEL=AGE REACHED HEIGHT - BASELINE); *AGE REACHED HEIGHT*;
%OVARCON (WRITEIN=1, NEWVAR=WTCURR_B, OLDVAR=Q4WEIGHT, BL_EN=VERSION_BL, VARLABEL=CURRENT WEIGHT - BASELINE (LBS)); *CURRENT WEIGHT*;
%OVARCON (WRITEIN=1, NEWVAR=WT18_B, OLDVAR=Q5WEIGHT, BL_EN=VERSION_BL, VARLABEL=WEIGHT AT 18 - BASELINE); *WEIGHT AT 18*;
%OVARCON (WRITEIN=1, NEWVAR=MOSTWT_B, OLDVAR=Q6WEIGHT, BL_EN=VERSION_BL, VARLABEL=MOST WEIGHED SINCE 18 - BASELINE); *MOST WEIGHED SINCE 18*;
%OVARCON (WRITEIN=1, NEWVAR=WTLOSS10_B, OLDVAR=Q8TIMES, BL_EN=VERSION_BL, VARLABEL=TIMES LOST 10 OR MORE LBS - BASELINE); *TIMES LOST 10 OR MORE LBS*;


%OVARCON (WRITEIN=0, NEWVAR=HEALTH_B, OLDVAR=Q11HEALTH, NUM=1, BL_EN=VERSION_BL, NA=1, VERSION=2010P, VARLABEL=GENERAL PHYSICAL HEALTH - BASELINE); *GENERAL PHYSICAL HEALTH*;
%OVARCON (WRITEIN=0, NEWVAR=BODYSHAPE_B, OLDVAR=Q9SHAPE, NUM=1, BL_EN=VERSION_BL, NA=, VERSION=, VARLABEL=BODY SHAPE - BASELINE); *BODY SHAPE*;
%OVARCON (WRITEIN=0, NEWVAR=WTGAIN_B, OLDVAR=Q10GAIN, NUM=1, BL_EN=VERSION_BL, NA=, VERSION=, VARLABEL=WHERE GAIN BODY WEIGHT - BASELINE); *WHERE GAIN BODY WEIGHT*;
%OVARCON (WRITEIN=0, NEWVAR=WALKPACE_B, OLDVAR=BL_PACE, NUM=1, BL_EN=VERSION_BL, NA=, VERSION=, VARLABEL=WALKING PACE OUTDOORS - BASELINE); *WALKING PACE OUTDOORS*; *JENNY-MAKE SURE THIS GOES BEFORE PA CODING SECTION*;
%OVARCON (WRITEIN=0, NEWVAR=DISABILITY_B, OLDVAR=BL_DISAB, NUM=1, BL_EN=VERSION_BL, NA=, VERSION=, VARLABEL=PHYSICAL LIMITATION - BASELINE); *PHYSICAL LIMITATION*;


************;
*ENROLLMENT*;
************;

%OVARCON (WRITEIN=1, NEWVAR=HEIGHTFT_E, OLDVAR=HEIGHTFT, BL_EN=VERSION_E, NA=1, VARLABEL=HEIGHT IN FEET - ENROLLMENT); *HEIGHT IN FEET*;
%OVARCON (WRITEIN=1, NEWVAR=HEIGHTIN_E, OLDVAR=HEIGHTIN, BL_EN=VERSION_E, NA=1, VARLABEL=HEIGHT IN INCHES - ENROLLMENT); *HEIGHT IN INCHES*;
%OVARCON (WRITEIN=1, NEWVAR=WTCURR_E, OLDVAR=WTCURR, BL_EN=VERSION_E, NA=1, VARLABEL=CURRENT WEIGHT - ENROLLMENT (LBS)); *CURRENT WEIGHT*;
%OVARCON (WRITEIN=1, NEWVAR=HEIGHTAGE_E, OLDVAR=HEIGHTAGE, BL_EN=VERSION_E, NA=1, VARLABEL=AGE REACHED HEIGHT - ENROLLMENT (YRS)); *AGE REACHED HEIGHT;
%OVARCON (WRITEIN=1, NEWVAR=WT18_E, OLDVAR=WT18, BL_EN=VERSION_E, NA=1, VARLABEL=WEIGHT AT AGE 18 - ENROLLMENT (LBS)); *WEIGHT AT 18*;

%OVARCON (WRITEIN=0, NEWVAR=EATDRINK_E, OLDVAR=EATDRINK, NUM=1, BL_EN=VERSION_E, NA=, VERSION=, VARLABEL=HOURS AGO ATE/DRANK - ENROLLMENT); *HOURS AGO ATE/DRANK*;
%OVARCON (WRITEIN=0, NEWVAR=WALKED15_E, OLDVAR=WALKED15, NUM=1, BL_EN=VERSION_E, NA=, VERSION=, VARLABEL=LAST TIME WALKED AROUND RELAY TRACK FOR 15 MINS OR MORE - ENROLLMENT); *LAST TIME WALKED AROUND RELAY TRACK FOR 15 MINS OR MORE*; 
*THE ABOVE CODE FOR WALKED15_E RECODES THE QUESTION FOR 2006 ALSO EVEN THOUGH QUESTION IS ASKED SLIGHTLY DIFFERENTLY.*;


***************************************************************;
*HAND CODING VARS THAT WERE NOT ASKED ON MULTIPLE SURVEYS (.N)*;
***************************************************************;

*GENERAL PHYSICAL HEALTH*;
HEALTH_E=INPUT(PHYSHLTH, ?? 1.); 
	IF VERSION_E NE ' ' AND PHYSHLTH = ' ' THEN HEALTH_E=.M; 
	ELSE IF PHYSHLTH='*' THEN HEALTH_E=.U;
	IF VERSION_E IN ('2006','2007','2009S') THEN HEALTH_E=.N;


*********************;
*	GRID VARIABLES	*;
*********************;

***********************;
**DAILY ACTIVITY GRID**;
***********************;


*CREATING SECTION MISSING VARIABLE FOR BASELINE*;
IF VERSION_BL NOT IN (' ','2010P') THEN DO;
	IF BL_SLWDAY = BL_SLWEND = BL_EXWDAY = BL_EXWEND = BL_SIWDAY = BL_SIWEND = BL_OTSIWDAY = BL_OTSIWEND = BL_STWDAY = BL_STWEND = ' ' THEN DA_MISS_B=1;
	ELSE DA_MISS_B=0;
END;

*INDICATOR VARIABLE FOR BASELINE DAILY ACTIVITY GRID - Q68 (WOMEN) AND Q43 (MEN), ALSO ON ENROLLMENT*;

ARRAY DA_B {*} BL_SLWDAY BL_SLWEND BL_EXWDAY BL_EXWEND BL_SIWDAY BL_SIWEND BL_OTSIWDAY BL_OTSIWEND BL_STWDAY BL_STWEND;
ARRAY DA_ORCODE_B {*} SLEEPWDAY_B SLEEPWEND_B EXERWDAY_B EXERWEND_B SITTVWDAY_B SITTVWEND_B OTHSITWDAY_B OTHSITWEND_B STNDWDAY_B STNDWEND_B; 
ARRAY DA_HR_B {*} SLEEPWDAYHR_B SLEEPWENDHR_B EXERWDAYHR_B EXERWENDHR_B SITTVWDAYHR_B SITTVWENDHR_B OTHSITWDAYHR_B OTHSITWENDHR_B STNDWDAYHR_B STNDWENDHR_B;

**********;
*BASELINE*;
**********;

*PEOPLE WHO WERE NOT ASKED THE QUESTION*;
IF VERSION_BL ='2010P' THEN DO;
	DO I = 1 TO DIM(DA_ORCODE_B);
		DA_ORCODE_B{I} = .N;
	END;
	DO I = 1 TO DIM(DA_HR_B);
		DA_HR_B{I} = .N;
	END;
END;


ELSE IF (VERSION_BL IN ('2006P','2007I','2007P')) THEN DO;  
*PEOPLE WHO WERE ASKED BUT DIDNT FILL OUT ANY OF THE SECTION (SECTION MISSING)*;
IF DA_MISS_B=1 THEN DO;
	DO I = 1 TO DIM(DA_ORCODE_B);
		DA_ORCODE_B{I} = .S;
	END;
	DO I = 1 TO DIM(DA_HR_B);
		DA_HR_B{I} = .S;
	END;
END;


*PEOPLE WHO WERE ASKED AND DID FILL IN AT LEAST 1 ANSWER - VALID OR INVALID*;
ELSE IF DA_MISS_B=0 THEN DO;
	*ORIGINAL VARIABLE RECODE*;
	DO I = 1 TO DIM(DA_ORCODE_B);
		DA_ORCODE_B{I}=INPUT(DA_B{I}, ?? 1.); 
		IF DA_B{I}='*' THEN DA_ORCODE_B{I}=.U;
		ELSE IF DA_B{I}=' ' THEN DA_ORCODE_B{I}=.M; 
	END;
	*CONVERSION TO HOURS FOR DERIVED VARIABLE*;
	DO I = 1 TO DIM(DA_HR_B);
		IF DA_ORCODE_B{I} = 1 THEN DA_HR_B{I} = 0;	*NONE*;
		ELSE IF DA_ORCODE_B{I} = 2 THEN DA_HR_B{I} = 0.5; *<1 HOUR*;
		ELSE IF DA_ORCODE_B{I} = 3 THEN DA_HR_B{I} = 1.5; *1-2 HOURS*;
		ELSE IF DA_ORCODE_B{I} = 4 THEN DA_HR_B{I} = 3.5; *3-4 HOURS*;
		ELSE IF DA_ORCODE_B{I} = 5 THEN DA_HR_B{I} = 5.5; *5-6 HOURS*;
		ELSE IF DA_ORCODE_B{I} = 6 THEN DA_HR_B{I} = 7.5; *7-8 HOURS*;
		ELSE IF DA_ORCODE_B{I} = 7 THEN DA_HR_B{I} = 9.5; *9-10 HOURS*;
		ELSE IF DA_ORCODE_B{I} = 8 THEN DA_HR_B{I} = 11; *11+ HOURS*;
		ELSE DA_HR_B{I}=DA_ORCODE_B{I}; *MISSINGS*;
	END;
END;

END;



**************************;
*WEEKEND/WEEKDAY WARRIORS*;
**************************;
*PER ALPA/PETE THESE ARE PEOPLE WHO ONLY DO CERTAIN ACTIVITIES DURING THE WEEK OR WEEKEND AND ONLY MARKED ONE OF THESE - CHANGE FROM MISSING TO 0*; 

*EXERCISE/PHYSICAL ACTIVITY*;
IF EXERWDAYHR_B = .M AND EXERWENDHR_B NOT IN (.U,.M) THEN EXERWDAYHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF EXERWDAYHR_B NOT IN (.U,.M) AND EXERWENDHR_B = .M THEN EXERWENDHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;

*SITTING WHILE WATCHING TV*;
IF SITTVWDAYHR_B = .M AND SITTVWENDHR_B NOT IN (.U,.M) THEN SITTVWDAYHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF SITTVWDAYHR_B NOT IN (.U,.M) AND SITTVWENDHR_B = .M THEN SITTVWENDHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;

*OTHER SITTING*;
IF OTHSITWDAYHR_B = .M AND OTHSITWENDHR_B NOT IN (.U,.M) THEN OTHSITWDAYHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF OTHSITWDAYHR_B NOT IN (.U,.M) AND OTHSITWENDHR_B = .M THEN OTHSITWENDHR_B = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;
     

ARRAY DA_FINAL_B {*} SLEEP_DB EXER_DB SITTV_DB SITOTH_DB STAND_DB; 
ARRAY DA_WDAY_B {*} SLEEPWDAYHR_B EXERWDAYHR_B SITTVWDAYHR_B OTHSITWDAYHR_B STNDWDAYHR_B; 
ARRAY DA_WEND_B {*} SLEEPWENDHR_B EXERWENDHR_B SITTVWENDHR_B OTHSITWENDHR_B STNDWENDHR_B; 

*ARRAY WITH FORMULA*;
DO I=1 TO DIM(DA_FINAL_B);
	IF DA_WDAY_B{I}=.U OR DA_WEND_B{I}=.U THEN DA_FINAL_B{I}=.U;
	ELSE IF DA_WDAY_B{I}=.N AND DA_WEND_B{I}=.N THEN DA_FINAL_B{I}=.N;
	ELSE IF DA_WDAY_B{I}=.S AND DA_WEND_B{I}=.S THEN DA_FINAL_B{I}=.S;
	ELSE IF DA_WDAY_B{I}=.M OR DA_WEND_B{I}=.M THEN DA_FINAL_B{I}=.M;
	ELSE DA_FINAL_B{I}=ROUND(((DA_WDAY_B{I}*5)+(DA_WEND_B{I}*2))/7,.01);	
END;


************;
*ENROLLMENT*;
************;

ARRAY DA_E {*} SLEEP_WKDY SLEEP_WKEND EXER_WKDY EXER_WKEND SITTV_WKDY SITTV_WKEND OTSIT_WKDY OTSIT_WKEND STND_WKDY STND_WKEND;

*CREATING SECTION MISSING VARIABLE FOR ENROLLMENT*;
IF VERSION_E NOT IN (' ','2006','2007','2009S') THEN DO;
	IF SLEEP_WKDY = SLEEP_WKEND = EXER_WKDY = EXER_WKEND = SITTV_WKDY = SITTV_WKEND = OTSIT_WKDY = OTSIT_WKEND = STND_WKDY = STND_WKEND = ' ' THEN DA_MISS_E=1;
	ELSE DA_MISS_E=0;
END;

ARRAY DA_ORCODE_E {*} SLEEPWDAY_E SLEEPWEND_E EXERWDAY_E EXERWEND_E SITTVWDAY_E SITTVWEND_E OTHSITWDAY_E OTHSITWEND_E STNDWDAY_E STNDWEND_E; 
ARRAY DA_HR_E {*} SLEEPWDAYHR_E SLEEPWENDHR_E EXERWDAYHR_E EXERWENDHR_E SITTVWDAYHR_E SITTVWENDHR_E OTHSITWDAYHR_E OTHSITWENDHR_E STNDWDAYHR_E STNDWENDHR_E;


*PEOPLE WHO WERE NOT ASKED THE QUESTION*;
IF VERSION_E IN ('2006','2007','2009S') THEN DO;
	DO I = 1 TO DIM(DA_ORCODE_E);
		DA_ORCODE_E{I} = .N;
	END;
	DO I = 1 TO DIM(DA_HR_E);
		DA_HR_E{I} = .N;
	END;
END;


ELSE IF (VERSION_E IN ('2008','2009','2010','2011','2012','2013')) THEN DO;
*PEOPLE WHO WERE ASKED BUT DIDNT FILL OUT ANY OF THE SECTION (SECTION MISSING)*;
IF DA_MISS_E=1 THEN DO;
	DO I = 1 TO DIM(DA_ORCODE_E);
		DA_ORCODE_E{I} = .S;
	END;
	DO I = 1 TO DIM(DA_HR_E);
		DA_HR_E{I} = .S;
	END;
END;

*PEOPLE WHO WERE ASKED AND DID FILL IN AT LEAST 1 ANSWER - VALID OR INVALID*;
ELSE IF DA_MISS_E=0 THEN DO;
	*ORIGINAL VARIABLE RECODE*;
	DO I = 1 TO DIM(DA_ORCODE_E);
		DA_ORCODE_E{I}=INPUT(DA_E{I}, ?? 1.); 
		IF DA_E{I}='*' THEN DA_ORCODE_E{I}=.U;
		ELSE IF DA_E{I}=' ' THEN DA_ORCODE_E{I}=.M; 
	END;
	*CONVERSION TO HOURS FOR DERIVED VARIABLE*;
	DO I = 1 TO DIM(DA_HR_E);
		IF DA_ORCODE_E{I} = 1 THEN DA_HR_E{I} = 0;	*NONE*;
		ELSE IF DA_ORCODE_E{I} = 2 THEN DA_HR_E{I} = 0.5; *<1 HOUR*;
		ELSE IF DA_ORCODE_E{I} = 3 THEN DA_HR_E{I} = 1.5; *1-2 HOURS*;
		ELSE IF DA_ORCODE_E{I} = 4 THEN DA_HR_E{I} = 3.5; *3-4 HOURS*;
		ELSE IF DA_ORCODE_E{I} = 5 THEN DA_HR_E{I} = 5.5; *5-6 HOURS*;
		ELSE IF DA_ORCODE_E{I} = 6 THEN DA_HR_E{I} = 7.5; *7-8 HOURS*;
		ELSE IF DA_ORCODE_E{I} = 7 THEN DA_HR_E{I} = 9.5; *9-10 HOURS*;
		ELSE IF DA_ORCODE_E{I} = 8 THEN DA_HR_E{I} = 11; *11+ HOURS*;
		ELSE DA_HR_E{I}=DA_ORCODE_E{I}; *MISSINGS*;
	END;
END;

END;

**************************;
*WEEKEND/WEEKDAY WARRIORS*;
**************************;

*EXERCISE/PHYSICAL ACTIVITY*;
IF EXERWDAYHR_E = .M AND EXERWENDHR_E NOT IN (.U,.M) THEN EXERWDAYHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF EXERWDAYHR_E NOT IN (.U,.M) AND EXERWENDHR_E = .M THEN EXERWENDHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;

*SITTING WHILE WATCHING TV*;
IF SITTVWDAYHR_E = .M AND SITTVWENDHR_E NOT IN (.U,.M) THEN SITTVWDAYHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF SITTVWDAYHR_E NOT IN (.U,.M) AND SITTVWENDHR_E = .M THEN SITTVWENDHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;

*OTHER SITTING*;
IF OTHSITWDAYHR_E = .M AND OTHSITWENDHR_E NOT IN (.U,.M) THEN OTHSITWDAYHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKEND BUT DIDNT MARK ANYTHING FOR WEEKDAYS*;
ELSE IF OTHSITWDAYHR_E NOT IN (.U,.M) AND OTHSITWENDHR_E = .M THEN OTHSITWENDHR_E = 0; *SETTING MISSINGS TO 0 IF PEOPLE DID ACTIVITY ON WEEKDAY BUT DIDNT MARK ANYTHING FOR WEEKENDS*;

ARRAY DA_FINAL_E {*} SLEEP_DE EXER_DE SITTV_DE SITOTH_DE STAND_DE; 
ARRAY DA_WDAY_E {*} SLEEPWDAYHR_E EXERWDAYHR_E SITTVWDAYHR_E OTHSITWDAYHR_E STNDWDAYHR_E; 
ARRAY DA_WEND_E {*} SLEEPWENDHR_E EXERWENDHR_E SITTVWENDHR_E OTHSITWENDHR_E STNDWENDHR_E; 

*ARRAY WITH FORMULA*;
DO I=1 TO DIM(DA_FINAL_E);
	IF DA_WDAY_E{I}=.U OR DA_WEND_E{I}=.U THEN DA_FINAL_E{I}=.U;
	ELSE IF DA_WDAY_E{I}=.N AND DA_WEND_E{I}=.N THEN DA_FINAL_E{I}=.N;
	ELSE IF DA_WDAY_E{I}=.S AND DA_WEND_E{I}=.S THEN DA_FINAL_E{I}=.S;
	ELSE IF DA_WDAY_E{I}=.M OR DA_WEND_E{I}=.M THEN DA_FINAL_E{I}=.M;
	ELSE DA_FINAL_E{I}=ROUND(((DA_WDAY_E{I}*5)+(DA_WEND_E{I}*2))/7,.01);	
END;

*****************************************************************************************************************************************************************************;

**************************;
**PHYSICAL ACTIVITY GRID**;
**************************;
*ON BASELINE ONLY - ON EVERY SURVEY*;
*ASSUMPTION: IF NOT FILLED OUT ON INTERNET SURVEY THEN IT IS ASSUMED TO BE NO (NOT SECTION MISSING)*;
*TREATING INTERNET VERSION SAME AS PAPER VERSION: NOT USING INDICATOR VARIABLES, EG. IF THEY CHECKED THAT THEY DID AND ACTIVITY BUT DIDNT FILL OUT HOURS/MONTHS THEN STILL COUNTING AS MISSING*;
*IF SOMEONE CHECKED NONE FOR HOURS BUT THEN CHECKED MONTHS/YEAR THEIR DERIVED VARIABLE WILL=0*;

*INDICATOR VARIABLE FOR PHYSICAL ACTIVITY GRID - Q67*;
ARRAY PA_B {*} BL_WALKHR BL_WALKMO BL_JOGHR BL_JOGMO BL_RUNHR BL_RUNMO BL_BIKEHR BL_BIKEMO BL_TENHR BL_TENMO BL_SWIMHR BL_SWIMMO BL_AERHR BL_AERMO BL_ELLHR BL_ELLMO BL_SPOHR BL_SPOMO
BL_DANCEHR BL_DANCEMO BL_OAERHR BL_OAERMO BL_CALHR BL_CALMO BL_YOGAHR BL_YOGAMO BL_WGTTRHR BL_WGTTRMO BL_YARDHR BL_YARDMO;

*CREATING INDICATOR VARIABLE FOR SECTION MISSING*;
IF VERSION_BL NOT IN (' ','2007I') THEN DO;
COUNT_PA_MISS=0;
	DO I=1 TO DIM(PA_B);
	IF PA_B{I} NOT IN (' ') THEN COUNT_PA_MISS+1;
	END;
IF COUNT_PA_MISS=0 THEN PA_MISS_B=1;
ELSE IF COUNT_PA_MISS GE 1 THEN PA_MISS_B=0;
END;

*NOT MAKING A SECTION MISSING VARIABLE FOR INTERNET - ASSUMING IF THEY DIDNT FILL OUT THEN THEY DIDNT DO THOSE ACTIVITIES*;
IF VERSION_BL='2007I' THEN PA_MISS_B=0;

*METS VALUES FROM ALPA;

WALK_METS = 3.5; *GENERIC METS VALUE WHEN WALKING PACE WAS NOT ENTERED*;
JOG_METS = 7.0;
RUN_METS = 9.8;
BIKE_METS = 4.5;
TENNIS_METS = 6.0;
SWIM_METS = 5.8;
AERO_METS = 5.5;
ELL_METS = 5.0;
SPORT_METS = 6.0;
DANCE_METS = 5.0;
OTHAERO_METS = 4.5;
CAL_METS = 2.9;
YOGA_METS = 2.8;
WGT_METS = 3.5;
YARD_METS = 3.0;
MOD_METS = 3.5;
STREN_METS=6.0;

*METS VALUES FOR 2006 MODERATE/STRENUOUS EXERCISE ACTIVITY GRID*;
*TO SEE HOW THESE NUMBERS WERE CALCULATED SEE BOTTOM OF PROGRAM*;
METS_2YR=4.37;
METS_HS=4.5;
METS_18=4.45;
METS_25=4.44;
METS_30=4.42;
METS_40=4.38;
METS_50=4.29;

*ORIGINAL VARIABLES*;
ARRAY PAHR_ORIG {*} BL_WALKHR BL_JOGHR BL_RUNHR BL_BIKEHR BL_TENHR BL_SWIMHR BL_AERHR BL_ELLHR BL_SPOHR BL_DANCEHR BL_OAERHR BL_CALHR BL_YOGAHR BL_WGTTRHR BL_YARDHR;
ARRAY PAMO_ORIG {*} BL_WALKMO BL_JOGMO BL_RUNMO BL_BIKEMO BL_TENMO BL_SWIMMO BL_AERMO BL_ELLMO BL_SPOMO BL_DANCEMO BL_OAERMO BL_CALMO BL_YOGAMO BL_WGTTRMO BL_YARDMO;
ARRAY PAYN_ORIG {*} BL_WALK BL_JOG BL_RUN BL_BIKE BL_TEN BL_SWIM BL_AER BL_ELL BL_SPO BL_DANCE BL_OAER BL_CAL BL_YOGA BL_WGTTR BL_YARD; *THESE ARE ONLY ON INTERNET VERSION*;

*ORIGINAL VARIABLE RECODES*;
ARRAY PAHR_ORCODE {*} WALKHR_B JOGHR_B RUNHR_B BIKEHR_B TENNISHR_B SWIMHR_B AEROHR_B ELLHR_B SPORTHR_B DANCEHR_B OTHAEROHR_B CALHR_B YOGAHR_B WGTHR_B YARDHR_B;
ARRAY PAMO_ORCODE {*} WALKMO_B JOGMO_B RUNMO_B BIKEMO_B TENNISMO_B SWIMMO_B AEROMO_B ELLMO_B SPORTMO_B DANCEMO_B OTHAEROMO_B CALMO_B YOGAMO_B WGTMO_B YARDMO_B;
ARRAY PAYN_ORCODE {*} WALKYN_B JOGYN_B RUNYN_B BIKEYN_B TENYN_B SWIMYN_B AEROYN_B ELLYN_B SPORTYN_B DANCEYN_B OTHAEROYN_B CALYN_B YOGAYN_B WGTYN_B YARDYN_B;

*VARIABLES FOR CALCULATING TOTAL METS*;
ARRAY PAHR_CALC {*} WALKHR_CALC JOGHR_CALC RUNHR_CALC BIKEHR_CALC TENNISHR_CALC SWIMHR_CALC AEROHR_CALC ELLHR_CALC SPORTHR_CALC DANCEHR_CALC OTHAEROHR_CALC CALHR_CALC YOGAHR_CALC WGTHR_CALC YARDHR_CALC;
ARRAY PAMO_CALC {*} WALKMO_CALC JOGMO_CALC RUNMO_CALC BIKEMO_CALC TENNISMO_CALC SWIMMO_CALC AEROMO_CALC ELLMO_CALC SPORTMO_CALC DANCEMO_CALC OTHAEROMO_CALC CALMO_CALC YOGAMO_CALC WGTMO_CALC YARDMO_CALC;

*LEAVING WALK VARIABLES OUT SINCE DOING THOSE SEPERATLEY*;
ARRAY METS {*} WALK_METS JOG_METS RUN_METS BIKE_METS TENNIS_METS SWIM_METS AERO_METS ELL_METS SPORT_METS DANCE_METS OTHAERO_METS CAL_METS YOGA_METS WGT_METS YARD_METS;
ARRAY PA_TOTAL {*} WALK_DB JOG_DB RUN_DB BIKE_DB TENNIS_DB SWIM_DB AERO_DB ELL_DB SPORT_DB DANCE_DB OTHAERO_DB CAL_DB YOGA_DB WGT_DB YARD_DB;

*PARTICIPANTS WHO DID THE PAPER SURVEY BUT LEFT THE ENTIRE PHYSICAL ACTIVITY SECTION MISSING*;
*MAKE SURE SURVEY_MISS CODE IS CORRECT*;
IF PA_MISS_B=1 THEN DO; *IF BASELINE SURVEY WAS COMPLETED AND THE ENTIRE PA GRID WAS MISSING*;
	DO I = 1 TO 15;
		PAHR_ORCODE{I} = .S;
		PAMO_ORCODE{I} = .S;
		PAHR_CALC{I} = .S;
		PAMO_CALC{I} = .S;
	END;
END;


ELSE IF PA_MISS_B=0 THEN DO; *PHYSICAL ACTIVITY GRID NOT MISSING*;
	DO I = 1 TO 15;
		*RECODING ORIGINAL PHYSICAL ACTIVITY HOURS/WEEK*;
		PAHR_ORCODE{I}=(INPUT(PAHR_ORIG{I}, ?? 1.))+1; 
		IF PAHR_ORIG{I}='*' THEN PAHR_ORCODE{I}=.U;
		ELSE IF PAHR_ORIG{I}=' ' THEN PAHR_ORCODE{I}=.M; 

		*RECODING ORIGINAL PHYSICAL ACTIVITY MONTHS/YEAR*;
		PAMO_ORCODE{I}=INPUT(PAMO_ORIG{I}, ?? 1.); 
		IF PAMO_ORIG{I}='*' THEN PAMO_ORCODE{I}=.U;
		ELSE IF PAMO_ORIG{I}=' ' THEN PAMO_ORCODE{I}=.M; 

		IF PAHR_ORCODE{I} = 1 THEN PAHR_CALC{I} = 0;	*NONE*;
		ELSE IF PAHR_ORCODE{I} = 2 THEN PAHR_CALC{I} = 0.5; *<1 HOUR*;
		ELSE IF PAHR_ORCODE{I} = 3 THEN PAHR_CALC{I} = 1.5; *1-2 HOURS*;
		ELSE IF PAHR_ORCODE{I} = 4 THEN PAHR_CALC{I} = 3; *3 HOURS*;
		ELSE IF PAHR_ORCODE{I} = 5 THEN PAHR_CALC{I} = 5; *4-6 HOURS*;
		ELSE IF PAHR_ORCODE{I} = 6 THEN PAHR_CALC{I} = 7; *7+ HOURS*;
		ELSE PAHR_CALC{I}=PAHR_ORCODE{I}; *MISSINGS*;

   	 	IF PAMO_ORCODE{I} = 1 THEN PAMO_CALC{I} = 0.25; *1-3 MONTHS*;
		ELSE IF PAMO_ORCODE{I} = 2 THEN PAMO_CALC{I} = 0.5; *4-6 HOURS*;
		ELSE IF PAMO_ORCODE{I} = 3 THEN PAMO_CALC{I} = 0.75; *7-9 MONTHS*;
		ELSE IF PAMO_ORCODE{I} = 4 THEN PAMO_CALC{I} = 1; *10-12 MONTHS*;
		ELSE PAMO_CALC{I}=PAMO_ORCODE{I}; *MISSINGS*;

		*ENTIRE ROW BLANK BUT OTHER ROWS FILLED IN --> CHANGING IT TO 0 - ASSUMING THEY DIDN'T DO THAT ACTIVITY*;
		IF PAHR_ORCODE{I}=.M AND PAMO_ORCODE{I} = .M THEN DO; 
			PAHR_CALC{I} = 0; 
			PAMO_CALC{I} = 0;
		END;
	END;
END;

*RECODING INTERNET INDICATOR VARIABLES*;
*IF THEY TOOK A PAPER VERSION OF THE SURVEY MARKING AS NOT ASKED (.N)*;

IF VERSION_BL IN ('2006P','2007P','2010P') THEN DO;
	DO I=1 TO DIM(PAYN_ORCODE);
		PAYN_ORCODE{I}=.N;
	END;
END;

ELSE IF VERSION_BL IN ('2007I') THEN DO;
	DO I=1 TO DIM(PAYN_ORCODE);
		PAYN_ORCODE{I}=INPUT(PAYN_ORIG{I}, ?? 1.);
		IF PAYN_ORIG{I}=' ' THEN PAYN_ORCODE{I}=.M;
	END;
END;

*CODE WALKING SEPERATELY DEPENDING ON WHETHER THEY ANSWERED THE WALK PACE QUESTION*; 
*IF PARTICIPANT SAID THEY WALK AND ANSWERED THE WALKPACE QUESTION*;

IF WALKPACE_B NOT IN (.,.M,.U,5) THEN DO;
	IF WALKPACE_B=1 THEN DO;
	 	WALK_DB=WALKHR_CALC*WALKMO_CALC*2.0;
	END;
	IF WALKPACE_B=2 THEN DO;
	 	WALK_DB=WALKHR_CALC*WALKMO_CALC*3.0;
	END;
	IF WALKPACE_B=3 THEN DO;
	 	WALK_DB=WALKHR_CALC*WALKMO_CALC*4.3;
	END;
	IF WALKPACE_B=4 THEN DO;
	 	WALK_DB=WALKHR_CALC*WALKMO_CALC*5.0;
	END;
END;
	
*IF WALKPACE IS MISSING BUT THEY SAID THEY WALKED ON THE GRID THEN ASSIGN WALKING GENERIC METS VALUE*;
ELSE DO;
	WALK_DB=WALKHR_CALC*WALKMO_CALC*WALK_METS; 
END;

*RECODING DERIVED WALKING VARIABLE*;
IF (WALKHR_CALC=0) AND (WALKMO_CALC=.M) THEN WALK_DB=0; *MARKED NONE FOR HOURS AND DIDNT MARK ANYTHING FOR MONTHS*;
*RECODING MISSINGS FOR FINAL PA VARIABLES*;
ELSE IF WALKHR_CALC=.S AND WALKMO_CALC=.S THEN WALK_DB=.S;
ELSE IF WALKHR_CALC=.U OR WALKMO_CALC=.U THEN WALK_DB=.U;
ELSE IF WALKHR_CALC=.M OR WALKMO_CALC=.M THEN WALK_DB=.M;	

*CREATING WALK FLAG FOR PEOPLE WHO SAID THEY WERE UNABLE TO WALK ON WALK PACE QUESTION BUT THEN SAID THEY WALKED ON PA GRID*;
IF WALKPACE_B=5 AND WALK_DB NOT IN (0,.M,.S,.U) THEN WALK_FLAG=1;

*FORMULA FOR ALL OTHER PA VARIABLES BESIDES WALKING*;
DO I=2 TO DIM(PA_TOTAL);
	PA_TOTAL{I}=(PAHR_CALC{I})*(PAMO_CALC{I})*(METS{I}); *AVERAGE MET HOURS/WEEK*;	
	IF (PAHR_CALC{I}=0) AND (PAMO_CALC{I}=.M) THEN PA_TOTAL{I}=0; *MARKED NONE FOR HOURS AND DIDNT MARK ANYTHING FOR MONTHS*;
	*RECODING MISSINGS FOR FINAL PA VARIABLES*;
	ELSE IF PAHR_CALC{I}=.S AND PAMO_CALC{I}=.S THEN PA_TOTAL{I}=.S;
	ELSE IF PAHR_CALC{I}=.U OR PAMO_CALC{I}=.U THEN PA_TOTAL{I}=.U;
	ELSE IF PAHR_CALC{I}=.M OR PAMO_CALC{I}=.M THEN PA_TOTAL{I}=.M;	
END;

*SUMMARY PHYSICAL ACTIVITY VARIABLES*;
AEROTOT_DB=WALK_DB+JOG_DB+RUN_DB+BIKE_DB+TENNIS_DB+SWIM_DB+AERO_DB+ELL_DB+SPORT_DB+DANCE_DB+OTHAERO_DB;
STRENSTRCHTOT_DB=CAL_DB+YOGA_DB+WGT_DB;
PATOT_DB=WALK_DB+JOG_DB+RUN_DB+BIKE_DB+TENNIS_DB+SWIM_DB+AERO_DB+ELL_DB+SPORT_DB+DANCE_DB+OTHAERO_DB+CAL_DB+YOGA_DB+WGT_DB+YARD_DB;


ARRAY AEROBIC {*} WALK_DB JOG_DB RUN_DB BIKE_DB TENNIS_DB SWIM_DB AERO_DB ELL_DB SPORT_DB DANCE_DB OTHAERO_DB;
ARRAY SS {*} CAL_DB YOGA_DB WGT_DB;

*RECODING MISSINGS FOR FINAL AEROBICS TOTAL VARIABLE*;
DO I=1 TO DIM(AEROBIC);
	IF AEROBIC{I}=.S THEN AEROTOT_DB=.S;
	ELSE IF AEROBIC{I}=.U THEN AEROTOT_DB=.U;
	ELSE IF AEROBIC{I}=.M THEN AEROTOT_DB=.M;
END;

*RECODING MISSINGS FOR FINAL STRENGTH/STRETCH TOTAL VARIABLE*;
DO I=1 TO DIM(SS);
	IF SS{I}=.S THEN STRENSTRCHTOT_DB=.S;
	ELSE IF SS{I}=.U THEN STRENSTRCHTOT_DB=.U;
	ELSE IF SS{I}=.M THEN STRENSTRCHTOT_DB=.M;
END;

*RECODING MISSINGS FOR ALL PA TOTAL VARIABLE*;
DO I=1 TO DIM(PA_TOTAL);
	IF PA_TOTAL{I}=.S THEN PATOT_DB=.S;
	ELSE IF PA_TOTAL{I}=.U THEN PATOT_DB=.U;
	ELSE IF PA_TOTAL{I}=.M THEN PATOT_DB=.M;
END;

*****************;
**WORK ACTIVITY**;
*****************;

*INDICATOR VARIABLE FOR WORK ACTIVITY GRID - Q71 ON BASELINE*;
ARRAY WA_B {*} BL_WORK2YRS BL_WORKLT18 BL_WORK18 BL_WORK25 BL_WORK30 BL_WORK40 BL_WORK50; 
ARRAY WA_ORCODE_B {*} WORKACT2YR_B WORKACTHS_B WORKACT18_B WORKACT25_B WORKACT30_B WORKACT40_B WORKACT50_B;

*SECTION MISSING VARIABLE*;
IF VERSION_BL NE (' ') THEN DO;
COUNT_WA_MISS=0;
	DO I=1 TO DIM(WA_B);
	IF WA_B{I} NOT IN (' ') THEN COUNT_WA_MISS+1;
	END;
IF COUNT_WA_MISS=0 THEN WA_MISS_B=1;
ELSE IF COUNT_WA_MISS GE 1 THEN WA_MISS_B=0;
END;

IF WA_MISS_B=1 THEN DO;
	DO I = 1 TO DIM(WA_ORCODE_B);
		WA_ORCODE_B{I} = .S;
	END;
END;

ELSE IF WA_MISS_B=0 THEN DO;
	DO I = 1 TO DIM(WA_ORCODE_B);
		WA_ORCODE_B{I}=INPUT(WA_B{I}, ?? 1.); 
		IF WA_B{I}='*' THEN WA_ORCODE_B{I}=.U;
		ELSE IF WA_B{I}=' ' THEN WA_ORCODE_B{I}=.M; 
	END;
END;



*********************;
**MODERATE EXERCISE**;
*********************;

*INDICATOR VARIABLE FOR MODERATE EXERCISE/SPORTS GRID - Q69 ON BASELINE*;
ARRAY MA_B {*} BL_MOD2YRSHR BL_MOD2YRSMO BL_MODLT18HR BL_MODLT18MO BL_MOD18HR BL_MOD18MO BL_MOD25HR BL_MOD25MO BL_MOD30HR BL_MOD30MO BL_MOD40HR BL_MOD40MO BL_MOD50HR BL_MOD50MO;

*MODERATE ACTIVITY GRID MISSING INDICATOR*;
IF VERSION_BL NOT IN (' ','2006P') THEN DO;
COUNT_MA_MISS=0;
	DO I=1 TO DIM(MA_B);
	IF MA_B{I} NOT IN (' ') THEN COUNT_MA_MISS+1;
	END;
IF COUNT_MA_MISS=0 THEN MA_MISS_B=1;
ELSE IF COUNT_MA_MISS GE 1 THEN MA_MISS_B=0;
END;

*ORIGINAL VARIABLES*;
ARRAY MODHR_ORIG {*} BL_MOD2YRSHR BL_MODLT18HR BL_MOD18HR BL_MOD25HR BL_MOD30HR BL_MOD40HR BL_MOD50HR;
ARRAY MODMO_ORIG {*} BL_MOD2YRSMO BL_MODLT18MO BL_MOD18MO BL_MOD25MO BL_MOD30MO BL_MOD40MO BL_MOD50MO;

*ORIGINAL VARIABLE RECODES*;
ARRAY MODHR_ORCODE {*} MODHR2YR_B MODHRHS_B MODHR18_B MODHR25_B MODHR30_B MODHR40_B MODHR50_B;
ARRAY MODMO_ORCODE {*} MODMO2YR_B MODMOHS_B MODMO18_B MODMO25_B MODMO30_B MODMO40_B MODMO50_B;

*VARIABLES FOR CALCULATING TOTAL METS*;
ARRAY MODHR_CALC {*} MODHR2YR_CALC MODHRHS_CALC MODHR18_CALC MODHR25_CALC MODHR30_CALC MODHR40_CALC MODHR50_CALC;
ARRAY MODMO_CALC {*} MODMO2YR_CALC MODMOHS_CALC MODMO18_CALC MODMO25_CALC MODMO30_CALC MODMO40_CALC MODMO50_CALC;

*DERIVED VARIABLES*;
ARRAY MOD_TOTAL {*} MOD2YR_DB MODHS_DB MOD18_DB MOD25_DB MOD30_DB MOD40_DB MOD50_DB;

*QUESTION ASKED DIFFERENTLY ON 2006 SURVEY - CODED AS A DIFFERENT VARIABLE*;
IF VERSION_BL IN ('2006P') THEN DO;
	DO I=1 TO 7;
		MODHR_ORCODE{I}=.N;
		MODMO_ORCODE{I}=.N;
		MODHR_CALC{I} = .N;
		MODMO_CALC{I} = .N;
	END;
END;

ELSE IF VERSION_BL IN ('2007P','2007I','2010P') THEN DO;
IF MA_MISS_B=1 THEN DO; *IF BASELINE SURVEY WAS COMPLETED AND THE ENTIRE MA GRID WAS MISSING*;
	DO I = 1 TO 7;
		MODHR_ORCODE{I} = .S;
		MODMO_ORCODE{I} = .S;
		MODHR_CALC{I} = .S;
		MODMO_CALC{I} = .S;
	END;
END;

ELSE IF MA_MISS_B=0 THEN DO; *IF MODERATE ACTIVITY GRID IS NOT MISSING*;
	DO I = 1 TO 7;
		MODHR_ORCODE{I}=(INPUT(MODHR_ORIG{I}, ?? 1.))+1; *CODING FOR HOURS STARTS AT 0 AND TO KEEP WITH CODING SCHEME FOR MULTI-LEVEL CATEGORICAL VARIABLES CHANGING TO START AT 1*;
		IF MODHR_ORIG{I}='*' THEN MODHR_ORCODE{I}=.U;
		ELSE IF MODHR_ORIG{I}=' ' THEN MODHR_ORCODE{I}=.M; 

		MODMO_ORCODE{I}=INPUT(MODMO_ORIG{I}, ?? 1.); 
		IF MODMO_ORIG{I}='*' THEN MODMO_ORCODE{I}=.U;
		ELSE IF MODMO_ORIG{I}=' ' THEN MODMO_ORCODE{I}=.M; 

		IF MODHR_ORCODE{I} = 1 THEN MODHR_CALC{I} = 0;	*NONE*;
		ELSE IF MODHR_ORCODE{I} = 2 THEN MODHR_CALC{I} = 0.5; *<1 HOUR*;
		ELSE IF MODHR_ORCODE{I} = 3 THEN MODHR_CALC{I} = 1.5; *1-2 HOURS*;
		ELSE IF MODHR_ORCODE{I} = 4 THEN MODHR_CALC{I} = 3; *3 HOURS*;
		ELSE IF MODHR_ORCODE{I} = 5 THEN MODHR_CALC{I} = 5; *4-6 HOURS*;
		ELSE IF MODHR_ORCODE{I} = 6 THEN MODHR_CALC{I} = 7; *7+ HOURS*;
		ELSE MODHR_CALC{I}=MODHR_ORCODE{I}; *MISSINGS*;

   	 	IF MODMO_ORCODE{I} = 1 THEN MODMO_CALC{I} = 0.25; *1-3 MONTHS*;
		ELSE IF MODMO_ORCODE{I} = 2 THEN MODMO_CALC{I} = 0.5; *4-6 HOURS*;
		ELSE IF MODMO_ORCODE{I} = 3 THEN MODMO_CALC{I} = 0.75; *7-9 MONTHS*;
		ELSE IF MODMO_ORCODE{I} = 4 THEN MODMO_CALC{I} = 1; *10-12 MONTHS*;
		ELSE MODMO_CALC{I}=MODMO_ORCODE{I}; *MISSINGS*;

	END;
END;

END;

*METS FORMULA*;
DO I=1 TO DIM(MOD_TOTAL);
	MOD_TOTAL{I}=(MODHR_CALC{I})*(MODMO_CALC{I})*(MOD_METS); *AVERAGE MET HOURS/WEEK*;	
	IF (MODHR_CALC{I}=0) AND (MODMO_CALC{I}=.M) THEN MOD_TOTAL{I}=0; *MARKED NONE FOR HOURS AND DIDNT MARK ANYTHING FOR MONTHS*;
	*RECODING MISSINGS FOR FINAL MODERATE VARIABLES*;
	ELSE IF MODHR_CALC{I}=.N AND MODMO_CALC{I}=.N THEN MOD_TOTAL{I}=.N;
	ELSE IF MODHR_CALC{I}=.S AND MODMO_CALC{I}=.S THEN MOD_TOTAL{I}=.S;
	ELSE IF MODHR_CALC{I}=.U OR MODMO_CALC{I}=.U THEN MOD_TOTAL{I}=.U;
	ELSE IF MODHR_CALC{I}=.M OR MODMO_CALC{I}=.M THEN MOD_TOTAL{I}=.M;
END;

********************;
*STRENUOUS EXERCISE*;
********************;

*INDICATOR VARIABLE FOR STRENUOUS EXERCISE/SPORTS GRID - Q70 ON BASELINE*;
ARRAY SA_B {*} BL_STREN2YRSHR BL_STREN2YRSMO BL_STRENLT18HR BL_STRENLT18MO BL_STREN18HR BL_STREN18MO BL_STREN25HR BL_STREN25MO BL_STREN30HR BL_STREN30MO BL_STREN40HR BL_STREN40MO 
BL_STREN50HR BL_STREN50MO;

*STRENUOUS ACTIVITY GRID MISSING INDICATOR*;
IF VERSION_BL NOT IN (' ','2006P') THEN DO;
COUNT_SA_MISS=0;
	DO I=1 TO DIM(SA_B);
	IF SA_B{I} NOT IN (' ') THEN COUNT_SA_MISS+1;
	END;
IF COUNT_SA_MISS=0 THEN SA_MISS_B=1;
ELSE IF COUNT_SA_MISS GE 1 THEN SA_MISS_B=0;
END;

*ORIGINAL VARIABLES*;
ARRAY STRENHR_ORIG {*} BL_STREN2YRSHR BL_STRENLT18HR BL_STREN18HR BL_STREN25HR BL_STREN30HR BL_STREN40HR BL_STREN50HR;
ARRAY STRENMO_ORIG {*} BL_STREN2YRSMO BL_STRENLT18MO BL_STREN18MO BL_STREN25MO BL_STREN30MO BL_STREN40MO BL_STREN50MO;

*ORIGINAL VARIABLE RECODES*;
ARRAY STRENHR_ORCODE {*} STRENHR2YR_B STRENHRHS_B STRENHR18_B STRENHR25_B STRENHR30_B STRENHR40_B STRENHR50_B;
ARRAY STRENMO_ORCODE {*} STRENMO2YR_B STRENMOHS_B STRENMO18_B STRENMO25_B STRENMO30_B STRENMO40_B STRENMO50_B;

*VARIABLES FOR CALCULATING TOTAL METS*;
ARRAY STRENHR_CALC {*} STRENHR2YR_CALC STRENHRHS_CALC STRENHR18_CALC STRENHR25_CALC STRENHR30_CALC STRENHR40_CALC STRENHR50_CALC;
ARRAY STRENMO_CALC {*} STRENMO2YR_CALC STRENMOHS_CALC STRENMO18_CALC STRENMO25_CALC STRENMO30_CALC STRENMO40_CALC STRENMO50_CALC;

*DERIVED VARIABLES*;
ARRAY STREN_TOTAL {*} STREN2YR_DB STRENHS_DB STREN18_DB STREN25_DB STREN30_DB STREN40_DB STREN50_DB;

*QUESTION ASKED DIFFERENTLY ON 2006 SURVEY - CODED AS A DIFFERENT VARIABLE*;
IF VERSION_BL IN ('2006P') THEN DO;
	DO I=1 TO 7;
		STRENHR_ORCODE{I}=.N;
		STRENMO_ORCODE{I}=.N;
		STRENHR_CALC{I} = .N;
		STRENMO_CALC{I} = .N;
	END;
END;

ELSE IF VERSION_BL IN ('2007P','2007I','2010P') THEN DO;
IF SA_MISS_B=1 THEN DO; *IF BASELINE SURVEY WAS COMPLETED AND THE ENTIRE SA GRID WAS MISSING*;
	DO I = 1 TO 7;
		STRENHR_ORCODE{I} = .S;
		STRENMO_ORCODE{I} = .S;
		STRENHR_CALC{I} = .S;
		STRENMO_CALC{I} = .S;
	END;
END;

ELSE IF SA_MISS_B=0 THEN DO; *IF STRENUOUS ACTIVITY GRID IS NOT MISSING*;
	DO I = 1 TO 7;
		STRENHR_ORCODE{I}=(INPUT(STRENHR_ORIG{I}, ?? 1.))+1; *CODING FOR HOURS STARTS AT 0 AND TO KEEP WITH CODING SCHEME FOR MULTI-LEVEL CATEGORICAL VARIABLES CHANGING TO START AT 1*;
		IF STRENHR_ORIG{I}='*' THEN STRENHR_ORCODE{I}=.U;
		ELSE IF STRENHR_ORIG{I}=' ' THEN STRENHR_ORCODE{I}=.M; 

		STRENMO_ORCODE{I}=INPUT(STRENMO_ORIG{I}, ?? 1.); 
		IF STRENMO_ORIG{I}='*' THEN STRENMO_ORCODE{I}=.U;
		ELSE IF STRENMO_ORIG{I}=' ' THEN STRENMO_ORCODE{I}=.M; 

		IF STRENHR_ORCODE{I} = 1 THEN STRENHR_CALC{I} = 0;	*NONE*;
		ELSE IF STRENHR_ORCODE{I} = 2 THEN STRENHR_CALC{I} = 0.5; *<1 HOUR*;
		ELSE IF STRENHR_ORCODE{I} = 3 THEN STRENHR_CALC{I} = 1.5; *1-2 HOURS*;
		ELSE IF STRENHR_ORCODE{I} = 4 THEN STRENHR_CALC{I} = 3; *3 HOURS*;
		ELSE IF STRENHR_ORCODE{I} = 5 THEN STRENHR_CALC{I} = 5; *4-6 HOURS*;
		ELSE IF STRENHR_ORCODE{I} = 6 THEN STRENHR_CALC{I} = 7; *7+ HOURS*;
		ELSE STRENHR_CALC{I}=STRENHR_ORCODE{I}; *MISSINGS*;

   	 	IF STRENMO_ORCODE{I} = 1 THEN STRENMO_CALC{I} = 0.25; *1-3 MONTHS*;
		ELSE IF STRENMO_ORCODE{I} = 2 THEN STRENMO_CALC{I} = 0.5; *4-6 HOURS*;
		ELSE IF STRENMO_ORCODE{I} = 3 THEN STRENMO_CALC{I} = 0.75; *7-9 MONTHS*;
		ELSE IF STRENMO_ORCODE{I} = 4 THEN STRENMO_CALC{I} = 1; *10-12 MONTHS*;
		ELSE STRENMO_CALC{I}=STRENMO_ORCODE{I}; *MISSINGS*;

	END;
END;

END;

*METS FORMULA*;
DO I=1 TO DIM(STREN_TOTAL);
	STREN_TOTAL{I}=(STRENHR_CALC{I})*(STRENMO_CALC{I})*(STREN_METS); *AVERAGE MET HOURS/WEEK;		
	IF (STRENHR_CALC{I}=0) AND (STRENMO_CALC{I}=.M) THEN STREN_TOTAL{I}=0; *MARKED NONE FOR HOURS AND DIDNT MARK ANYTHING FOR MONTHS*;
	*RECODING MISSINGS FOR FINAL STRENUOUS VARIABLES*;
	ELSE IF STRENHR_CALC{I}=.N AND STRENMO_CALC{I}=.N THEN STREN_TOTAL{I}=.N;
	ELSE IF STRENHR_CALC{I}=.S AND STRENMO_CALC{I}=.S THEN STREN_TOTAL{I}=.S;
	ELSE IF STRENHR_CALC{I}=.U OR STRENMO_CALC{I}=.U THEN STREN_TOTAL{I}=.U;
	ELSE IF STRENHR_CALC{I}=.M OR STRENMO_CALC{I}=.M THEN STREN_TOTAL{I}=.M;
END;

*CALCULATING WEIGHTED AVERAGE OF MODERATE AND STRENUOUS GRIDS FOR 2006 MODERATE/STRENUOUS VARIABLE*;

ARRAY MOD_WEIGHT {*} MOD2YR_WT MODHS_WT MOD18_WT MOD25_WT MOD30_WT MOD40_WT MOD50_WT;
ARRAY STREN_WEIGHT {*} STREN2YR_WT STRENHS_WT STREN18_WT STREN25_WT STREN30_WT STREN40_WT STREN50_WT;
ARRAY MOD_PROP {*} MOD2YR_PROP MODHS_PROP MOD18_PROP MOD25_PROP MOD30_PROP MOD40_PROP MOD50_PROP;
ARRAY DENOM {*} DENOM_2YR DENOM_HS DENOM_18 DENOM_25 DENOM_30 DENOM_40 DENOM_50;

DO I=1 TO DIM(MOD_WEIGHT);
	MOD_WEIGHT{I}=(MODHR_CALC{I})*(MODMO_CALC{I}); *CALCULATING WITHOUT THE METS VALUE TO GET THE PROPORTION*;
	STREN_WEIGHT{I}=(STRENHR_CALC{I})*(STRENMO_CALC{I}); *CALCULATING WITHOUT THE METS VALUE TO GET THE PROPORTION*;
	DENOM{I}=MOD_WEIGHT{I}+STREN_WEIGHT{I};
	IF DENOM{I} NOT IN (.,0) THEN DO;
		MOD_PROP{I}=MOD_WEIGHT{I}/DENOM{I};
	END;
END;

**********************************;
*2006 MODERATE/STRENUOUS EXERCISE*;
**********************************;
*PER ALPA - LOOK AT THE PROPORTIONS OF MODERATE/STRENUOUS EXERCISE IN THE 2007-2013 SURVEYS FOR THE MOST RECENT CATEGORY (2 YRS CATEGORY). USE THAT PROPOTION WHEN 
APPLYING THE METS VALUES.E.G. IF ITS A 50% THEN USE 4.75 AS THE METS VALUES BC ITS HALF WAY BETWEEN 3.5 AND 6*; 
*SEE CODE AT VERY END OF PROGRAM FOR THESE MET VALUE CALCULATIONS*;

ARRAY MOD_STREN {*} BL_2YRSHR BL_2YRSMO BL_LT18HR BL_LT18MO BL_18HR BL_18MO BL_25HR BL_25MO BL_30HR BL_30MO BL_40HR BL_40MO BL_50HR BL_50MO;

*2006 MODERATE/STRENUOUS ACTIVITY GRID MISSING INDICATOR*;
IF VERSION_BL IN ('2006P') THEN DO;
COUNT_MS_MISS=0;
	DO I=1 TO DIM(MOD_STREN);
	IF MOD_STREN{I} NOT IN (' ') THEN COUNT_MS_MISS+1;
	END;
IF COUNT_MS_MISS=0 THEN MS_MISS_B=1;
ELSE IF COUNT_MS_MISS GE 1 THEN MS_MISS_B=0;
END;

*ORIGINAL VARIABLES*;
ARRAY MSHR_ORIG {*} BL_2YRSHR BL_LT18HR BL_18HR BL_25HR BL_30HR BL_40HR BL_50HR;
ARRAY MSMO_ORIG {*} BL_2YRSMO BL_LT18MO BL_18MO BL_25MO BL_30MO BL_40MO BL_50MO;

*ORIGINAL VARIABLE RECODES*;
ARRAY MSHR_ORCODE {*} MODSTRENHR2YR_B MODSTRENHRHS_B MODSTRENHR18_B MODSTRENHR25_B MODSTRENHR30_B MODSTRENHR40_B MODSTRENHR50_B;
ARRAY MSMO_ORCODE {*} MODSTRENMO2YR_B MODSTRENMOHS_B MODSTRENMO18_B MODSTRENMO25_B MODSTRENMO30_B MODSTRENMO40_B MODSTRENMO50_B;

*VARIABLES FOR CALCULATING TOTAL METS*;
ARRAY MSHR_CALC {*} MSHR2YR_CALC MSHRHS_CALC MSHR18_CALC MSHR25_CALC MSHR30_CALC MSHR40_CALC MSHR50_CALC;
ARRAY MSMO_CALC {*} MSMO2YR_CALC MSMOHS_CALC MSMO18_CALC MSMO25_CALC MSMO30_CALC MSMO40_CALC MSMO50_CALC;

*DERIVED VARIABLES*;
ARRAY MS_TOTAL {*} MODSTREN2YR_DB MODSTRENHS_DB MODSTREN18_DB MODSTREN25_DB MODSTREN30_DB MODSTREN40_DB MODSTREN50_DB;

*MET VALUES ARRAY*;
ARRAY MS_METS {*} METS_2YR METS_HS METS_18 METS_25 METS_30 METS_40 METS_50;

*QUESTION ASKED DIFFERENTLY ON 2007-2013 SURVEYS - CODED AS A DIFFERENT VARIABLE*;
IF VERSION_BL NOT IN (' ','2006P') THEN DO;
	DO I=1 TO 7;
		MSHR_ORCODE{I}=.N;
		MSMO_ORCODE{I}=.N;
		MSHR_CALC{I} = .N;
		MSMO_CALC{I} = .N;
	END;
END;

ELSE IF VERSION_BL IN ('2006P') THEN DO;
IF MS_MISS_B=1 THEN DO; *IF BASELINE SURVEY WAS COMPLETED AND THE ENTIRE MA GRID WAS MISSING*;
	DO I = 1 TO 7;
		MSHR_ORCODE{I}=.S;
		MSMO_ORCODE{I}=.S;
		MSHR_CALC{I} = .S;
		MSMO_CALC{I} = .S;
	END;
END;

ELSE IF MS_MISS_B=0 THEN DO; *IF MODERATE ACTIVITY GRID IS NOT MISSING*;
	DO I = 1 TO 7;
		MSHR_ORCODE{I}=(INPUT(MSHR_ORIG{I}, ?? 1.))+1; *CODING FOR HOURS STARTS AT 0 AND TO KEEP WITH CODING SCHEME FOR MULTI-LEVEL CATEGORICAL VARIABLES CHANGING TO START AT 1*;
		IF MSHR_ORIG{I}='*' THEN MSHR_ORCODE{I}=.U;
		ELSE IF MSHR_ORIG{I}=' ' THEN MSHR_ORCODE{I}=.M; 

		MSMO_ORCODE{I}=INPUT(MSMO_ORIG{I}, ?? 1.); 
		IF MSMO_ORIG{I}='*' THEN MSMO_ORCODE{I}=.U;
		ELSE IF MSMO_ORIG{I}=' ' THEN MSMO_ORCODE{I}=.M; 

		IF MSHR_ORCODE{I} = 1 THEN MSHR_CALC{I} = 0;	*NONE*;
		ELSE IF MSHR_ORCODE{I} = 2 THEN MSHR_CALC{I} = 0.5; *<1 HOUR*;
		ELSE IF MSHR_ORCODE{I} = 3 THEN MSHR_CALC{I} = 1.5; *1-2 HOURS*;
		ELSE IF MSHR_ORCODE{I} = 4 THEN MSHR_CALC{I} = 3; *3 HOURS*;
		ELSE IF MSHR_ORCODE{I} = 5 THEN MSHR_CALC{I} = 5; *4-6 HOURS*;
		ELSE IF MSHR_ORCODE{I} = 6 THEN MSHR_CALC{I} = 7; *7+ HOURS*;
		ELSE MSHR_CALC{I}=MSHR_ORCODE{I}; *MISSINGS*;

   	 	IF MSMO_ORCODE{I} = 1 THEN MSMO_CALC{I} = 0.25; *1-3 MONTHS*;
		ELSE IF MSMO_ORCODE{I} = 2 THEN MSMO_CALC{I} = 0.5; *4-6 HOURS*;
		ELSE IF MSMO_ORCODE{I} = 3 THEN MSMO_CALC{I} = 0.75; *7-9 MONTHS*;
		ELSE IF MSMO_ORCODE{I} = 4 THEN MSMO_CALC{I} = 1; *10-12 MONTHS*;
		ELSE MSMO_CALC{I}=MSMO_ORCODE{I}; *MISSINGS*;

	END;
END;

END;

*METS FORMULA*;
DO I=1 TO DIM(MS_TOTAL);
	MS_TOTAL{I}=(MSHR_CALC{I})*(MSMO_CALC{I})*(MS_METS{I}); *AVERAGE MET HOURS/WEEK*;	
	IF (MSHR_CALC{I}=0) AND (MSMO_CALC{I}=.M) THEN MS_TOTAL{I}=0; *MARKED NONE FOR HOURS AND DIDNT MARK ANYTHING FOR MONTHS*;
	*RECODING MISSINGS FOR FINAL MODERATE/STRENUOUS VARIABLES*;
	ELSE IF MSHR_CALC{I}=.N AND MSMO_CALC{I}=.N THEN MS_TOTAL{I}=.N;
	ELSE IF MSHR_CALC{I}=.S AND MSMO_CALC{I}=.S THEN MS_TOTAL{I}=.S;
	ELSE IF MSHR_CALC{I}=.U OR MSMO_CALC{I}=.U THEN MS_TOTAL{I}=.U;
	ELSE IF MSHR_CALC{I}=.M OR MSMO_CALC{I}=.M THEN MS_TOTAL{I}=.M;
END;

****************;
**USUAL WEIGHT**;
****************;

*SECTION MISSING VARIABLE*;
IF VERSION_BL NE (' ') THEN DO;
	IF WT20_B = WT30_B = WT40_B = WT50_B = Q7C1 = Q7D1 = ' ' THEN WT_MISS_B=1;
	ELSE WT_MISS_B=0;
END;

*ORIGINAL VARIABLES*;
ARRAY NOTAGE_ORIG {*} Q7C1 Q7D1;

*RECODED ORIGINAL VARIABLES*;
ARRAY USUALWT_ORCODE {*} WT20_B WT30_B WT40_B WT50_B;
ARRAY NOTAGE_ORCODE {*} NOT40_B NOT50_B;

*FOR DERIVED VARIABLES COMPARE TO AGE*;
ARRAY USUALWTDER {*} WT20_DB WT30_DB WT40_DB WT50_DB;
ARRAY NOTAGEDER {*} NOT40_DB NOT50_DB;

*ORIGINAL VARIABLE RECODE FORAND DERIVED VARIABLE CODING*;
IF VERSION_BL NE ' ' THEN DO;

DO I=1 TO DIM(USUALWT_ORCODE);

	*DERIVED VARIABLE*;
	USUALWTDER{I}=INPUT(USUALWT_ORCODE{I}, ?? 3.); 
	IF NOTDIGIT(STRIP(USUALWT_ORCODE{I})) GE 1 THEN USUALWTDER{I}=.U;
	ELSE IF WT_MISS_B=1 THEN USUALWTDER{I}=.S;
	ELSE IF USUALWT_ORCODE{I} = ' ' THEN USUALWTDER{I}=.M; 
END;

DO I=1 TO DIM(NOTAGE_ORCODE);
	*ORIGINAL VARIABLE RECODE*;
	NOTAGE_ORCODE{I}=INPUT(NOTAGE_ORIG{I}, ?? 1.);
	IF WT_MISS_B=1 THEN NOTAGE_ORCODE{I}=.S;
	ELSE IF NOTAGE_ORIG{I}= ' ' THEN NOTAGE_ORCODE{I}=.M;

	*DERIVED VARIABLE - CORRECTED USING AGE AT INTERVIEW*;
	NOTAGEDER{I}=NOTAGE_ORCODE{I};
END;

*CORRECTING NOTAGE AND WEIGHT DERIVED VARIABLES ACCORDING TO AGE AT INTERVIEW*; 
*KEEPING THE .S'S FOR SECTION MISSING AND RECODING ALL OTHERS ACCORDING TO AGE AT INTERVIEW*;
IF WT_MISS_B=0 THEN DO; 

	IF .<AGE_INTB<50 THEN DO;
		WT50_DB=.M; NOT50_DB=1;
	END;
	IF .<AGE_INTB<40 THEN DO;
		WT40_DB=.M; NOT40_DB=1; 
	END;
	IF .<AGE_INTB<30 THEN DO;
		WT30_DB=.M; 
	END;

*CORRECTING PEOPLE THAT ARE IN THEIR 40S/50S WHO CHECKED THAT THEY WEREN'T IN THEIR 40S/50S*;
	IF AGE_INTB GE 50 THEN NOT50_DB=.M;
	IF AGE_INTB GE 40 THEN NOT40_DB=.M;

END;

*MANUAL CORRECTIONS*;
	IF WT20_B='13O' THEN WT20_DB=130; *FIXING TYPO IN THE DERIVED VARIABLE*; 
END;

********************************;
*WEIGHT GAIN/LOSS IN PAST 3 MOS*;
********************************;
*ENROLLMENT*;

*IF SOMEONE SAID NO AND THEN MARKED THAT THEY GAINED OR LOST WEIGHT, MARKING AS .U*;
*COLLAPSING INTO 1 VARIABLE FOR DERIVED VARIABLE*; 

ARRAY WT3MO_ORIG {*} WT10NO WT10LOSS WT10GAIN;
ARRAY WT3MO_ORCODE {*} WT3MONO_E WT3MOLOSS_E WT3MOGAIN_E; 

IF VERSION_E NE ' ' THEN DO;
	*MAKING A 'SECTION MISSING' VARIABLE FOR WHEN THE WHOLE QUESTION WAS LEFT BLANK*;
	IF WT10NO = WT10LOSS = WT10GAIN = ' ' THEN WT3MO_MISS=1; 

DO I=1 TO DIM(WT3MO_ORCODE);
	WT3MO_ORCODE{I}=INPUT(WT3MO_ORIG{I}, ?? 1.); 
	IF WT3MO_MISS=1 THEN WT3MO_ORCODE{I}=.S;
	ELSE IF WT3MO_ORIG{I}= ' ' THEN WT3MO_ORCODE{I}=.M;
END;

*COMBINING TO 1 DERIVED VARIABLE*;

IF WT3MO_MISS=1 THEN WT3MO_DE=.M; *DIDN'T ANSWER THE QUESTION (SAME AS .S ABOVE BUT I DIDNT HAVE A BETTER WAY TO SIGNIFY IT FOR ORIGINAL VARIABLE RECODE SINCE IT WAS BROKEN
	INTO 3 QUESTIONS)*;
ELSE IF (WT3MONO_E=1) AND (WT3MOLOSS_E NE 1) AND (WT3MOGAIN_E NE 1) THEN WT3MO_DE=1; *NO WEIGHT GAIN OR LOSS*;
ELSE IF (WT3MONO_E NE 1) AND (WT3MOLOSS_E=1) AND (WT3MOGAIN_E NE 1) THEN WT3MO_DE=2; *LOST WEIGHT ONLY*;
ELSE IF (WT3MONO_E NE 1) AND (WT3MOLOSS_E NE 1) AND (WT3MOGAIN_E=1) THEN WT3MO_DE=3; *GAINED WEIGHT ONLY*;
ELSE IF (WT3MONO_E NE 1) AND (WT3MOLOSS_E=1) AND (WT3MOGAIN_E=1) THEN WT3MO_DE=4; *GAINED AND LOST WEIGHT*;
ELSE WT3MO_DE=.U; *SAID NO AND GAINED/LOST*;

END;


LABEL SLEEPWDAY_B='SLEEP-WEEKDAY BASELINE (HR/DAY)'
	  SLEEPWEND_B='SLEEP-WEEKEND BASELINE (HR/DAY)'
	  EXERWDAY_B='EXERCISE-WEEKDAY BASELINE (HR/DAY)'
	  EXERWEND_B='EXERCISE-WEEKEND BASELINE (HR/DAY)'
	  SITTVWDAY_B='SITTING TV-WEEKDAY BASELINE (HR/DAY)'
	  SITTVWEND_B='SITTING TV-WEEKEND BASELINE (HR/DAY)'
	  OTHSITWDAY_B='OTHER SITTING-WEEKDAY BASELINE (HR/DAY)'
	  OTHSITWEND_B='OTHER SITTING-WEEKEND BASELINE (HR/DAY)'
	  STNDWDAY_B='STANDING-WEEKDAY BASELINE (HR/DAY)'
	  STNDWEND_B='STANDING-WEEKEND BASELINE (HR/DAY)'

	  SLEEP_DB='AVERAGE SLEEP-BASELINE(HR/WEEK)'  
	  EXER_DB='AVERAGE EXERCISE-BASELINE(HR/WEEK)'
	  SITTV_DB='AVERAGE SITTING TV-BASELINE(HR/WEEK)'
	  SITOTH_DB='AVERAGE OTHER SITTING-BASELINE(HR/WEEK)'
	  STAND_DB='AVERAGE STANDING-BASELINE(HR/WEEK)'

	  SLEEPWDAY_E='SLEEP-WEEKDAY ENROLLMENT (HR/DAY)'
	  SLEEPWEND_E='SLEEP-WEEKEND ENROLLMENT (HR/DAY)'
	  EXERWDAY_E='EXERCISE-WEEKDAY ENROLLMENT (HR/DAY)'
	  EXERWEND_E='EXERCISE-WEEKEND ENROLLMENT (HR/DAY)'
	  SITTVWDAY_E='SITTING TV-WEEKDAY ENROLLMENT (HR/DAY)'
	  SITTVWEND_E='SITTING TV-WEEKEND ENROLLMENT (HR/DAY)'
	  OTHSITWDAY_E='OTHER SITTING-WEEKDAY ENROLLMENT (HR/DAY)'
	  OTHSITWEND_E='OTHER SITTING-WEEKEND ENROLLMENT (HR/DAY)'
	  STNDWDAY_E='STANDING-WEEKDAY ENROLLMENT (HR/DAY)'
	  STNDWEND_E='STANDING-WEEKEND ENROLLMENT (HR/DAY)'

	  SLEEP_DE='AVERAGE SLEEP-ENROLLMENT(HR/WEEK)'  
	  EXER_DE='AVERAGE EXERCISE-ENROLLMENT(HR/WEEK)'
	  SITTV_DE='AVERAGE SITTING TV-ENROLLMENT(HR/WEEK)'
	  SITOTH_DE='AVERAGE OTHER SITTING-ENROLLMENT(HR/WEEK)'
	  STAND_DE='AVERAGE STANDING-ENROLLMENT(HR/WEEK)'

	  WALKHR_B='WALKING-BASELINE (HR/WEEK)'
	  JOGHR_B='JOGGING-BASELINE (HR/WEEK)'
 	  RUNHR_B='RUNNING-BASELINE (HR/WEEK)'
	  BIKEHR_B='BIKING-BASELINE (HR/WEEK)'
	  TENNISHR_B='TENNIS-BASELINE (HR/WEEK)'
	  SWIMHR_B='SWIMMING-BASELINE (HR/WEEK)'
	  AEROHR_B='AEROBICS-BASELINE (HR/WEEK)'
	  ELLHR_B='ELLIPTICAL-BASELINE (HR/WEEK)'
 	  SPORTHR_B='SPORTS ACTIVITIES-BASELINE (HR/WEEK)'
	  DANCEHR_B='DANCING-BASELINE (HR/WEEK)'
	  OTHAEROHR_B='OTHER AEROBICS-BASELINE (HR/WEEK)'
	  CALHR_B='CALISTHENICS-BASELINE (HR/WEEK)'
	  YOGAHR_B='YOGA-BASELINE (HR/WEEK)'
	  WGTHR_B='WEIGHT TRAINING-BASELINE (HR/WEEK)'
	  YARDHR_B='YARD WORK-BASELINE (HR/WEEK)'

	  WALKMO_B='WALKING-BASELINE (MO/YR)'
	  JOGMO_B='JOGGING-BASELINE (MO/YR)'
 	  RUNMO_B='RUNNING-BASELINE (MO/YR)'
	  BIKEMO_B='BIKING-BASELINE (MO/YR)'
	  TENNISMO_B='TENNIS-BASELINE (MO/YR)'
	  SWIMMO_B='SWIMMING-BASELINE (MO/YR)'
	  AEROMO_B='AEROBICS-BASELINE (MO/YR)'
	  ELLMO_B='ELLIPTICAL-BASELINE (MO/YR)'
 	  SPORTMO_B='SPORTS ACTIVITIES-BASELINE (MO/YR)'
	  DANCEMO_B='DANCING-BASELINE (MO/YR)'
	  OTHAEROMO_B='OTHER AEROBICS-BASELINE (MO/YR)'
	  CALMO_B='CALISTHENICS-BASELINE (MO/YR)'
	  YOGAMO_B='YOGA-BASELINE (MO/YR)'
	  WGTMO_B='WEIGHT TRAINING-BASELINE (MO/YR)'
	  YARDMO_B='YARD WORK-BASELINE (MO/YR)'

	  WALKYN_B='WALKING-INTERNET BASELINE ONLY (YES/NO)'
	  JOGYN_B='JOGGING-INTERNET BASELINE ONLY (YES/NO)'
 	  RUNYN_B='RUNNING-INTERNET BASELINE ONLY (YES/NO)'
	  BIKEYN_B='BIKING-INTERNET BASELINE ONLY (YES/NO)'
	  TENYN_B='TENNIS-INTERNET BASELINE ONLY (YES/NO)'
	  SWIMYN_B='SWIMMING-INTERNET BASELINE ONLY (YES/NO)'
	  AEROYN_B='AEROBICS-INTERNET BASELINE ONLY (YES/NO)'
	  ELLYN_B='ELLIPTICAL-INTERNET BASELINE ONLY (YES/NO)'
 	  SPORTYN_B='SPORTS ACTIVITIES-INTERNET BASELINE ONLY (YES/NO)'
	  DANCEYN_B='DANCING-INTERNET BASELINE ONLY (YES/NO)'
	  OTHAEROYN_B='OTHER AEROBICS-INTERNET BASELINE ONLY (YES/NO)'
	  CALYN_B='CALISTHENICS-INTERNET BASELINE ONLY (YES/NO)'
	  YOGAYN_B='YOGA-INTERNET BASELINE ONLY (YES/NO)'
	  WGTYN_B='WEIGHT TRAINING-INTERNET BASELINE ONLY (YES/NO)'
	  YARDYN_B='YARD WORK-INTERNET BASELINE ONLY (YES/NO)'

	  WALK_DB='AVERAGE WALKING - BASELINE (MET HRS/WEEK)'
	  JOG_DB='AVERAGE JOGGING - BASELINE (MET HRS/WEEK)'
	  RUN_DB='AVERAGE RUNNING - BASELINE (MET HRS/WEEK)'
	  BIKE_DB='AVERAGE BIKING - BASELINE (MET HRS/WEEK)'
	  TENNIS_DB='AVERAGE TENNIS - BASELINE (MET HRS/WEEK)'
	  SWIM_DB='AVERAGE SWIMING - BASELINE (MET HRS/WEEK)'
	  AERO_DB='AVERAGE AEROBICS - BASELINE (MET HRS/WEEK)'
	  ELL_DB='AVERAGE ELLIPTICAL - BASELINE (MET HRS/WEEK)'
	  SPORT_DB='AVERAGE SPORTS ACTIVITIES - BASELINE (MET HRS/WEEK)'
	  DANCE_DB='AVERAGE DANCING - BASELINE (MET HRS/WEEK)'
	  OTHAERO_DB='AVERAGE OTHER AEROBICS - BASELINE (MET HRS/WEEK)'
	  CAL_DB='AVERAGE CALISTHENICS - BASELINE (MET HRS/WEEK)'
	  YOGA_DB='AVERAGE YOGA - BASELINE (MET HRS/WEEK)'
	  WGT_DB='AVERAGE WEIGHT TRAINING - BASELINE (MET HRS/WEEK)'
	  YARD_DB='AVERAGE YARD WORK - BASELINE (MET HRS/WEEK)'

	  AEROTOT_DB='TOTAL AVERAGE AEROBIC ACTIVITY-BASELINE (MET HRS/WEEK)' 
	  STRENSTRCHTOT_DB='TOTAL AVERAGE STRENGTH/STRETCHING ACTIVITY-BASELINE (MET HRS/WEEK)'
	  PATOT_DB='TOTAL AVERAGE PHYSICAL ACTIVITY-BASELINE (MET HRS/WEEK)'

	  MODHR2YR_B='MODERATE EXERCISE, PAST 2 YEARS-BASELINE (HR/WK)'
	  MODHRHS_B='MODERATE EXERCISE, HIGH SCHOOL-BASELINE (HR/WK)'
	  MODHR18_B='MODERATE EXERCISE, AGES 18-24-BASELINE (HR/WK)'
	  MODHR25_B='MODERATE EXERCISE, AGES 25-29-BASELINE (HR/WK)'
 	  MODHR30_B='MODERATE EXERCISE, AGES 30-39-BASELINE (HR/WK)'
	  MODHR40_B='MODERATE EXERCISE, AGES 40-49-BASELINE (HR/WK)'
	  MODHR50_B='MODERATE EXERCISE, AGE 50+-BASELINE (HR/WK)'
	  MODMO2YR_B='MODERATE EXERCISE, PAST 2 YEARS-BASELINE (MO/YR)'
	  MODMOHS_B='MODERATE EXERCISE, HIGH SCHOOL-BASELINE (MO/YR)'
	  MODMO18_B='MODERATE EXERCISE, AGES 18-24-BASELINE (MO/YR)'
	  MODMO25_B='MODERATE EXERCISE, AGES 25-29-BASELINE (MO/YR)'
	  MODMO30_B='MODERATE EXERCISE, AGES 30-39-BASELINE (MO/YR)'
	  MODMO40_B='MODERATE EXERCISE, AGES 40-49-BASELINE (MO/YR)'
	  MODMO50_B='MODERATE EXERCISE, AGE 50+-BASELINE (MO/YR)'

	  MOD2YR_DB='AVERAGE MODERATE EXERCISE, PAST 2 YEARS-BASELINE (MET HRS/WEEK)'  
	  MODHS_DB='AVERAGE MODERATE EXERCISE, HIGH SCHOOL-BASELINE (MET HRS/WEEK)'
	  MOD18_DB='AVERAGE MODERATE EXERCISE, AGES 18-24-BASELINE (MET HRS/WEEK)'
	  MOD25_DB='AVERAGE MODERATE EXERCISE, AGES 25-29-BASELINE (MET HRS/WEEK)'
	  MOD30_DB='AVERAGE MODERATE EXERCISE, AGES 30-39-BASELINE (MET HRS/WEEK)'
	  MOD40_DB='AVERAGE MODERATE EXERCISE, AGES 40-49-BASELINE (MET HRS/WEEK)'
	  MOD50_DB='AVERAGE MODERATE EXERCISE, AGES 50+-BASELINE (MET HRS/WEEK)'

	  STRENHR2YR_B='STRENUOUS EXERCISE, PAST 2 YEARS-BASELINE (HR/WK)'
	  STRENHRHS_B='STRENUOUS EXERCISE, HIGH SCHOOL-BASELINE (HR/WK)'
	  STRENHR18_B='STRENUOUS EXERCISE, AGES 18-24-BASELINE (HR/WK)'
	  STRENHR25_B='STRENUOUS EXERCISE, AGES 25-29-BASELINE (HR/WK)'
 	  STRENHR30_B='STRENUOUS EXERCISE, AGES 30-39-BASELINE (HR/WK)'
	  STRENHR40_B='STRENUOUS EXERCISE, AGES 40-49-BASELINE (HR/WK)'
	  STRENHR50_B='STRENUOUS EXERCISE, AGE 50+-BASELINE (HR/WK)'
	  STRENMO2YR_B='STRENUOUS EXERCISE, PAST 2 YEARS-BASELINE (MO/YR)'
	  STRENMOHS_B='STRENUOUS EXERCISE, HIGH SCHOOL-BASELINE (MO/YR)'
	  STRENMO18_B='STRENUOUS EXERCISE, AGES 18-24-BASELINE (MO/YR)'
	  STRENMO25_B='STRENUOUS EXERCISE, AGES 25-29-BASELINE (MO/YR)'
	  STRENMO30_B='STRENUOUS EXERCISE, AGES 30-39-BASELINE (MO/YR)'
	  STRENMO40_B='STRENUOUS EXERCISE, AGES 40-49-BASELINE (MO/YR)'
 	  STRENMO50_B='STRENUOUS EXERCISE, AGE 50+-BASELINE (MO/YR)'

	  STREN2YR_DB='AVERAGE STRENUOUS EXERCISE, PAST 2 YEARS-BASELINE (MET HRS/WEEK)'   
	  STRENHS_DB='AVERAGE STRENUOUS EXERCISE, HIGH SCHOOL-BASELINE (MET HRS/WEEK)'
	  STREN18_DB='AVERAGE STRENUOUS EXERCISE, AGES 18-24-BASELINE (MET HRS/WEEK)'
	  STREN25_DB='AVERAGE STRENUOUS EXERCISE, AGES 25-29-BASELINE (MET HRS/WEEK)'
	  STREN30_DB='AVERAGE STRENUOUS EXERCISE, AGES 30-39-BASELINE (MET HRS/WEEK)'
	  STREN40_DB='AVERAGE STRENUOUS EXERCISE, AGES 40-49-BASELINE (MET HRS/WEEK)'
	  STREN50_DB='AVERAGE STRENUOUS EXERCISE, AGES 50+-BASELINE (MET HRS/WEEK)'

	MODSTRENHR2YR_B='MODERATE/STRENUOUS EXERCISE, PAST 2 YEARS-2006 BASELINE (HR/WK)'
	MODSTRENHRHS_B='MODERATE/STRENUOUS EXERCISE, HIGH SCHOOL-2006 BASELINE (HR/WK)' 
	MODSTRENHR18_B='MODERATE/STRENUOUS EXERCISE, AGES 18-24 -2006 BASELINE (HR/WK)'
	MODSTRENHR25_B='MODERATE/STRENUOUS EXERCISE, AGES 25-29 -2006 BASELINE (HR/WK)'
	MODSTRENHR30_B='MODERATE/STRENUOUS EXERCISE, AGES 30-39 -2006 BASELINE (HR/WK)'
	MODSTRENHR40_B='MODERATE/STRENUOUS EXERCISE, AGES 40-49 -2006 BASELINE (HR/WK)'
	MODSTRENHR50_B='MODERATE/STRENUOUS EXERCISE, AGE 50+ -2006 BASELINE (HR/WK)'
 	MODSTRENMO2YR_B='MODERATE/STRENUOUS EXERCISE, PAST 2 YEARS- 2006 BASELINE (MO/YR)'
	MODSTRENMOHS_B='MODERATE/STRENUOUS EXERCISE, HIGH SCHOOL- 2006 BASELINE (MO/YR)' 
	MODSTRENMO18_B'MODERATE/STRENUOUS EXERCISE, AGES 18-24- 2006 BASELINE (MO/YR)'
	MODSTRENMO25_B='MODERATE/STRENUOUS EXERCISE, AGES 25-29- 2006 BASELINE (MO/YR)' 
	MODSTRENMO30_B='MODERATE/STRENUOUS EXERCISE, AGES 30-39- 2006 BASELINE (MO/YR)' 
	MODSTRENMO40_B='MODERATE/STRENUOUS EXERCISE, AGES 40-49- 2006 BASELINE (MO/YR)' 
	MODSTRENMO50_B='MODERATE/STRENUOUS EXERCISE, AGE 50+- 2006 BASELINE (MO/YR)' 

	MODSTREN2YR_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, PAST 2 YEARS- 2006 BASELINE (MET HRS/WEEK)'  
	MODSTRENHS_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, HIGH SCHOOL- 2006 BASELINE (MET HRS/WEEK)' 
	MODSTREN18_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, AGES 18-24- 2006 BASELINE (MET HRS/WEEK)' 
	MODSTREN25_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, AGES 25-29- 2006 BASELINE (MET HRS/WEEK)' 
	MODSTREN30_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, AGES 30-39- 2006 BASELINE (MET HRS/WEEK)' 
	MODSTREN40_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, AGES 40-49- 2006 BASELINE (MET HRS/WEEK)' 
	MODSTREN50_DB='AVERAGE MODERATE/STRENUOUS EXERCISE, AGES 50+- 2006 BASELINE (MET HRS/WEEK)'

	  WT20_B='USUAL WEIGHT IN 20S-BASELINE (LBS)'   
	  WT30_B='USUAL WEIGHT IN 30S-BASELINE (LBS)' 
	  WT40_B='USUAL WEIGHT IN 40S-BASELINE (LBS)' 
	  WT50_B='USUAL WEIGHT IN 50S-BASELINE (LBS)' 
	  NOT40_B='NOT YET IN 40S-BASELINE' 
	  NOT50_B='NOT YET IN 50S-BASELINE'

	  WT20_DB='USUAL WEIGHT IN 20S-BASELINE (LBS)'  
	  WT30_DB='USUAL WEIGHT IN 30S-BASELINE (LBS)'
	  WT40_DB='USUAL WEIGHT IN 40S-BASELINE(LBS)'
	  WT50_DB='USUAL WEIGHT IN 50S-BASELINE (LBS)'
	  NOT40_DB='NOT YET IN 40S-BASELINE' 
	  NOT50_DB='NOT YET IN 50S-BASELINE'

	  WORKACT2YR_B='WORK ACTIVITY, PAST 2 YEARS-BASELINE'
	  WORKACTHS_B='WORK ACTIVITY, HIGH SCHOOL-BASELINE'
	  WORKACT18_B='WORK ACTIVITY, AGES 18-24-BASELINE'
	  WORKACT25_B='WORK ACTIVITY, AGES 25-29-BASELINE'
	  WORKACT30_B='WORK ACTIVITY, AGES 30-39-BASELINE' 
	  WORKACT40_B='WORK ACTIVITY, AGES 40-49-BASELINE'
 	  WORKACT50_B='WORK ACTIVITY, AGES 50+-BASELINE'

	  WT3MONO_E='NOT GAINED 10+ LBS IN PAST 3 MONTHS-ENROLLMENT'
	  WT3MOLOSS_E='LOST 10+ LBS IN PAST 3 MONTHS-ENROLLMENT' 
	  WT3MOGAIN_E='GAINED 10+ LBS IN PAST 3 MONTHS-ENROLLMENT'

	  WT3MO_DE='WEIGHT GAIN/LOSS IN PAST 3 MONTHS-ENROLLMENT'

	  HEALTH_E='GENERAL PHYSICAL HEALTH -ENROLLMENT';

RUN;

*FINAL DATASET*;
/*DATA FINAL(KEEP=*/
/*HEIGHTFT_B */
/*HEIGHTIN_B */
/*HEIGHTAGE_B */
/*WTCURR_B */
/*WT18_B */
/*MOSTWT_B */
/*WTLOSS10_B */
/*HEALTH_B */
/*BODYSHAPE_B */
/*WTGAIN_B */
/*WALKPACE_B */
/*DISABILITY_B */
/*HEIGHTFT_E */
/*HEIGHTIN_E */
/*WTCURR_E */
/*HEIGHTAGE_E*/
/*WT18_E */
/*EATDRINK_E */
/*WALKED15_E */
/*HEALTH_E */
/*SLEEPWDAY_B */
/*SLEEPWEND_B */
/*EXERWDAY_B */
/*EXERWEND_B */
/*SITTVWDAY_B */
/*SITTVWEND_B */
/*OTHSITWDAY_B */
/*OTHSITWEND_B */
/*STNDWDAY_B */
/*STNDWEND_B*/
/*SLEEP_DB */
/*EXER_DB */
/*SITTV_DB */
/*SITOTH_DB */
/*STAND_DB */
/*SLEEPWDAY_E */
/*SLEEPWEND_E */
/*EXERWDAY_E */
/*EXERWEND_E */
/*SITTVWDAY_E */
/*SITTVWEND_E */
/*OTHSITWDAY_E */
/*OTHSITWEND_E */
/*STNDWDAY_E */
/*STNDWEND_E*/
/*SLEEP_DE */
/*EXER_DE */
/*SITTV_DE */
/*SITOTH_DE */
/*STAND_DE */
/*WALKHR_B */
/*JOGHR_B */
/*RUNHR_B */
/*BIKEHR_B */
/*TENNISHR_B */
/*SWIMHR_B */
/*AEROHR_B */
/*ELLHR_B */
/*SPORTHR_B */
/*DANCEHR_B */
/*OTHAEROHR_B */
/*CALHR_B */
/*YOGAHR_B */
/*WGTHR_B */
/*YARDHR_B */
/*WALKMO_B */
/*JOGMO_B */
/*RUNMO_B */
/*BIKEMO_B */
/*TENNISMO_B */
/*SWIMMO_B */
/*AEROMO_B */
/*ELLMO_B */
/*SPORTMO_B */
/*DANCEMO_B */
/*OTHAEROMO_B */
/*CALMO_B */
/*YOGAMO_B */
/*WGTMO_B */
/*YARDMO_B*/
/*WALKYN_B */
/*JOGYN_B */
/*RUNYN_B */
/*BIKEYN_B */
/*TENYN_B */
/*SWIMYN_B */
/*AEROYN_B */
/*ELLYN_B */
/*SPORTYN_B */
/*DANCEYN_B */
/*OTHAEROYN_B */
/*CALYN_B */
/*YOGAYN_B */
/*WGTYN_B */
/*YARDYN_B */
/*WALK_DB */
/*JOG_DB */
/*RUN_DB */
/*BIKE_DB */
/*TENNIS_DB */
/*SWIM_DB */
/*AERO_DB */
/*ELL_DB */
/*SPORT_DB */
/*DANCE_DB */
/*OTHAERO_DB */
/*CAL_DB */
/*YOGA_DB */
/*WGT_DB */
/*YARD_DB */
/*AEROTOT_DB */
/*STRENSTRCHTOT_DB */
/*PATOT_DB*/
/*WORKACT2YR_B */
/*WORKACTHS_B */
/*WORKACT18_B */
/*WORKACT25_B */
/*WORKACT30_B */
/*WORKACT40_B */
/*WORKACT50_B */
/*MODHR2YR_B */
/*MODHRHS_B */
/*MODHR18_B */
/*MODHR25_B */
/*MODHR30_B */
/*MODHR40_B */
/*MODHR50_B*/
/*MODMO2YR_B */
/*MODMOHS_B */
/*MODMO18_B */
/*MODMO25_B */
/*MODMO30_B */
/*MODMO40_B */
/*MODMO50_B */
/*MOD2YR_DB */
/*MODHS_DB */
/*MOD18_DB */
/*MOD25_DB */
/*MOD30_DB */
/*MOD40_DB */
/*MOD50_DB*/
/*STRENHR2YR_B */
/*STRENHRHS_B */
/*STRENHR18_B */
/*STRENHR25_B */
/*STRENHR30_B */
/*STRENHR40_B */
/*STRENHR50_B */
/*STRENMO2YR_B */
/*STRENMOHS_B */
/*STRENMO18_B */
/*STRENMO25_B */
/*STRENMO30_B */
/*STRENMO40_B */
/*STRENMO50_B*/
/*STREN2YR_DB */
/*STRENHS_DB */
/*STREN18_DB */
/*STREN25_DB */
/*STREN30_DB */
/*STREN40_DB */
/*STREN50_DB */
/*WT20_B */
/*WT30_B */
/*WT40_B */
/*WT50_B */
/*NOT40_B */
/*NOT50_B */
/*WT20_DB */
/*WT30_DB */
/*WT40_DB */
/*WT50_DB */
/*NOT40_DB */
/*NOT50_DB*/
/*WT3MONO_E */
/*WT3MOLOSS_E */
/*WT3MOGAIN_E */
/*WT3MO_DE*/
/*MODSTRENHR2YR_B */
/*MODSTRENHRHS_B */
/*MODSTRENHR18_B */
/*MODSTRENHR25_B */
/*MODSTRENHR30_B */
/*MODSTRENHR40_B */
/*MODSTRENHR50_B */
/*MODSTRENMO2YR_B */
/*MODSTRENMOHS_B */
/*MODSTRENMO18_B */
/*MODSTRENMO25_B */
/*MODSTRENMO30_B */
/*MODSTRENMO40_B */
/*MODSTRENMO50_B */
/*MODSTREN2YR_DB */
/*MODSTRENHS_DB */
/*MODSTREN18_DB */
/*MODSTREN25_DB */
/*MODSTREN30_DB */
/*MODSTREN40_DB */
/*MODSTREN50_DB;*/
/*);*/
/**/
/*SET ALL;*/
/*RUN;*/

*CALCULATIONS FOR 2006 MODERATE/STRENUOUS METS VALUES*;
ODS OUTPUT SUMMARY=MEANS_SUM;
PROC MEANS DATA=ALL;
VAR MOD2YR_PROP MODHS_PROP MOD18_PROP MOD25_PROP MOD30_PROP MOD40_PROP MOD50_PROP;
RUN;
ODS OUTPUT CLOSE;

DATA PROPS;
SET MEANS_SUM (KEEP=MOD2YR_PROP_Mean MOD18_PROP_Mean MOD25_PROP_Mean MOD30_PROP_Mean MOD40_PROP_Mean MOD50_PROP_Mean MODHS_PROP_Mean);

ARRAY MOD_MEANS {*} MOD2YR_PROP_Mean MODHS_PROP_Mean MOD18_PROP_Mean MOD25_PROP_Mean MOD30_PROP_Mean MOD40_PROP_Mean MOD50_PROP_Mean; *MEAN PROPORTION OF MODERATE ACTIVITY*;
ARRAY METS_CAT {*} METS_2YR METS_HS METS_18 METS_25 METS_30 METS_40 METS_50;

*SUBTRACTING THE MODERATE PROPORTION X DIFFERENCE IN THE STRENOUS MET VALUE-MODERATE MET VALUE FROM THE MAXIMUM MET VALUE IF 6*;
DO I=1 TO DIM(METS_CAT);
	METS_CAT{I}=ROUND(6-(MOD_MEANS{I}*2.5),.01); 
END;

RUN;

TITLE 'MET VALUES FOR 2006 MODERATE/STRENUOUS GRID';
PROC PRINT DATA=PROPS; VAR METS_2YR METS_HS METS_18 METS_25 METS_30 METS_40 METS_50; RUN;
