*********************************************************************************************************************;
*PROGRAM: S:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\PROGRAMS\Heme and Parents Age Analysis.SAS  *;
*PURPOSE: Entire analysis for: Parental Age at Birth and Risk of Hematologic Malignances in Older Adults 			*;                               
*CREATED:                                           *;
*MODIFIED: *;
*********************************************************************************************************************;

LIBNAME PAGE 'D:\USER\JBLASE\Hema Malignancies & Parents Age\DATA';
LIBNAME LIBRARY 'D:\USER\JBLASE'; 
OPTIONS  LINESIZE=132 MPRINT;

*****************;
*	ABSTRACT	*;
*****************;

*The paternal age association was exclusively observed in participants without siblings (p=0.03).*;

*4 CATEGORY PATERNAL AGE X SIBS INTERACTION*;

*REDUCED MODEL*;
ODS OUTPUT FitStatistics=FIT_REDUCED GLOBALTESTS = GLOBAL_REDC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA FAGEBTH_4CAT MAGEBTH_4CAT/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)=FAGEBTH_4CAT RACENEW EDUCA SEX_NEW MAGEBTH_4CAT SIBS;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;


DATA FIT_REDFC;
	SET FIT_REDUCED (KEEP = CRITERION WITHCOVARIATES);

WHERE Criterion='-2 LOG L';
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1";
RENAME WITHCOVARIATES = MODEL_R;

RUN;

DATA GLOBAL_REDFC; 
	SET GLOBAL_REDC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_R;

DATA REDUCEDC; 
	MERGE FIT_REDFC GLOBAL_REDFC; 

BY MERGEVAR; 

RUN;
PROC PRINT DATA = REDUCEDC; TITLE2 "Reduced Model Test Stats"; RUN;


ODS OUTPUT FITSTATISTICS = FIT_FULLC GLOBALTESTS = GLOBAL_FULLC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA FAGEBTH_4CAT MAGEBTH_4CAT/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)= FAGEBTH_4CAT SIBS MAGEBTH_4CAT SEX_NEW RACENEW EDUCA FAGEBTH_4CAT*SIBS/RL;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;

DATA FIT_FULLFC; 
	SET FIT_FULLC (KEEP = CRITERION WITHCOVARIATES); 

WHERE CRITERION = "-2 LOG L";
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1"; 
RENAME WITHCOVARIATES = MODEL_F;
RUN;

DATA GLOBAL_FULLFC; 
	SET GLOBAL_FULLC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_F;
RUN;

DATA FULLC; 
MERGE FIT_FULLFC GLOBAL_FULLFC; 
BY MERGEVAR; 
RUN;
PROC PRINT DATA = FULLC; TITLE2 "Full Model Test Stats"; RUN;


DATA CHITEST (KEEP = MERGEVAR MODEL_R MODEL_F CHIVAL PVAL P_VALUE DF_R DF_F DOF);
		MERGE REDUCEDC FULLC; BY MERGEVAR;
		CHIVAL = ABS(MODEL_F - MODEL_R);
		DOF = ABS(DF_F - DF_R);
		PVAL = 1 - PROBCHI(CHIVAL,DOF); P_VALUE = PUT(ROUND(PVAL,0.001),5.3); 
RUN;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\INTERACTION CATEGORICAL FATHERS AGE X SIBS - &SYSDATE..RTF";

TITLE '4 CATEGORY FATHERS AGE*SIBLINGS INTERACTION';
PROC PRINT DATA = CHITEST; RUN;

ODS RTF CLOSE;

*************;
*	METHODS	*;
*************;

*EXCLUSIONS (PG. 4)*;
ODS RTF FILE= "D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\METHODS STATISTICS - &SYSDATE..rtf";

TITLE 'ALL HEMA CANCERS BY EXCLUSION (PG. 4)';
PROC FREQ DATA=PAGE.INITIALCOHORT;
TABLES ALL_HEMA*EXCLUSN/MISSING;
FORMAT EXCLUSN EXCLUSN. ALL_HEMA NHL.;
RUN;

*FINAL COHORT N BY SEX (PG. 4)*;
TITLE 'SEX DISTRIBUTION (PG. 4)';
PROC FREQ DATA=PAGE.FINALCOHORT;
TABLES SEX_NEW;
FORMAT SEX_NEW GENDER.;
RUN;

*AGE RANGE AT BASELINE (PG. 4)/AVERAGE AGE AT BASELINE (PG. 6)*;
TITLE 'AGE RANGE AT BASELINE (PG. 4)/AVERAGE AGE AT BASELINE (PG. 6)';
PROC UNIVARIATE DATA=PAGE.FINALCOHORT;
VAR AGE92M;
RUN;

*INCIDENT CASES BY SEX (PG. 5)*; 
TITLE 'INCIDENT CASES BY SEX (PG. 5)';
PROC FREQ DATA=PAGE.FINALCOHORT;
TABLES ALL_HEMA*SEX_NEW;
FORMAT SEX_NEW GENDER. ALL_HEMA NHL.;
RUN;

*CASE ASCERTAINMENT (PG. 5)*;
TITLE 'CASE ASCERTAINMENT (PG. 5)';
PROC FREQ DATA=PAGE.FINALCOHORT;
TABLES ASCERTAIN/NOCUM NOPERCENT NOROW NOCOL;
RUN;

*HEME SUBTYPE FREQUENCIES (PG. 5-6)*;
TITLE 'HEME SUBTYPE FREQUENCIES (PG. 5-6)';
PROC FREQ DATA=PAGE.FINALCOHORT;
TABLES LYMPHOID_D DLBCL_D CLLSLL_D FOLLIC_D MYELOMA_D MYELUK_D AML_D ALL_OTHER;
FORMAT LYMPHOID_D DLBCL_D CLLSLL_D FOLLIC_D MYELOMA_D MYELUK_D AML_D ALL_OTHER NHL.;
RUN;

ODS RTF CLOSE;

TITLE;

*TOTAL PERSON-YEARS OF FOLLOW-UP (PG. 6)*; 
PROC MEANS DATA=PAGE.FINALCOHORT NOPRINT;
VAR FAILNEW;
OUTPUT OUT=RESULTS SUM=SUM_FAILNEW N=N_FAILNEW;
RUN;

ODS RTF FILE= "D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\RESULTS STATISTICS - &SYSDATE..rtf";
TITLE 'TOTAL PERSON-YEARS OF FOLLOW-UP (PG. 6)';
PROC PRINT DATA=RESULTS (OBS=15); RUN;

*MEDIAN FOLLOW-UP TIME (PG. 6)*;
TITLE 'MEDIAN FOLLOW-UP TIME (PG. 6)';
PROC UNIVARIATE DATA=PAGE.FINALCOHORT;
VAR FAILNEW;
RUN;

*MOTHER'S AND FATHER'S MEDIAN AGE AT BIRTH (PG. 6-7)*;
TITLE 'MOTHERS AND FATHERS MEDIAN AGE AT BIRTH (PG. 6-7)';
PROC UNIVARIATE DATA=PAGE.FINALCOHORT;
VAR FAGEBTH MAGEBTH;
RUN;

*PERCENTAGES OF PARENT'S AGE CATEGORIES (PG. 7)*;
TITLE 'PERCENTAGES OF PARENTS AGE CATEGORIES (PG. 7)';
PROC FREQ DATA=PAGE.FINALCOHORT;
TABLES FAGEBTH_4CAT MAGEBTH_4CAT/NOCUM;
RUN;

ODS RTF CLOSE;

*5 YEAR CONTINUOUS PATERNAL AGE X SEX INTERACTION (PG. 7)*;

*REDUCED MODEL*;
ODS OUTPUT FitStatistics=FIT_REDUCED GLOBALTESTS = GLOBAL_REDC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)=FAGEBTH_5YR RACENEW EDUCA SEX_NEW MAGEBTH_5YR SIBS;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;


DATA FIT_REDFC;
	SET FIT_REDUCED (KEEP = CRITERION WITHCOVARIATES);

WHERE Criterion='-2 LOG L';
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1";
RENAME WITHCOVARIATES = MODEL_R;

RUN;

DATA GLOBAL_REDFC; 
	SET GLOBAL_REDC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_R;

DATA REDUCEDC; 
	MERGE FIT_REDFC GLOBAL_REDFC; 

BY MERGEVAR; 

RUN;
PROC PRINT DATA = REDUCEDC; TITLE2 "Reduced Model Test Stats"; RUN;

ODS OUTPUT FITSTATISTICS = FIT_FULLC GLOBALTESTS = GLOBAL_FULLC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)= FAGEBTH_5YR SIBS MAGEBTH_5YR SEX_NEW RACENEW EDUCA FAGEBTH_5YR*SEX_NEW/RL;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;

DATA FIT_FULLFC; 
	SET FIT_FULLC (KEEP = CRITERION WITHCOVARIATES); 

WHERE CRITERION = "-2 LOG L";
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1"; 
RENAME WITHCOVARIATES = MODEL_F;
RUN;

DATA GLOBAL_FULLFC; 
	SET GLOBAL_FULLC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_F;
RUN;

DATA FULLC; 
MERGE FIT_FULLFC GLOBAL_FULLFC; 
BY MERGEVAR; 
RUN;
PROC PRINT DATA = FULLC; TITLE2 "Full Model Test Stats"; RUN;


DATA CHITEST (KEEP = MERGEVAR MODEL_R MODEL_F CHIVAL PVAL P_VALUE DF_R DF_F DOF);
		MERGE REDUCEDC FULLC; BY MERGEVAR;
		CHIVAL = ABS(MODEL_F - MODEL_R);
		DOF = ABS(DF_F - DF_R);
		PVAL = 1 - PROBCHI(CHIVAL,DOF); P_VALUE = PUT(ROUND(PVAL,0.001),5.3); 
RUN;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\INTERACTION FATHERS AGE X SEX - &SYSDATE..RTF";

TITLE 'CONTINUOUS (PER 5 YRS) FATHERS AGE*SEX INTERACTION';
PROC PRINT DATA = CHITEST; RUN;

ODS RTF CLOSE;

*SIBLING STATUS INTERACTION WITH 5YR PATERNAL AND MATERNAL AGE (PG. 7) - There was evidence of effect modification by number 
of siblings on the association between paternal age at birth – but not maternal age at birth – and risk of NHL *;

*REDUCED MODEL*;
ODS OUTPUT FitStatistics=FIT_REDUCED GLOBALTESTS = GLOBAL_REDC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)=FAGEBTH_5YR RACENEW EDUCA SEX_NEW MAGEBTH_5YR SIBS;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;


DATA FIT_REDFC;
	SET FIT_REDUCED (KEEP = CRITERION WITHCOVARIATES);

WHERE Criterion='-2 LOG L';
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1";
RENAME WITHCOVARIATES = MODEL_R;

RUN;

DATA GLOBAL_REDFC; 
	SET GLOBAL_REDC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_R;

DATA REDUCEDC; 
	MERGE FIT_REDFC GLOBAL_REDFC; 

BY MERGEVAR; 

RUN;
PROC PRINT DATA = REDUCEDC; TITLE2 "Reduced Model Test Stats"; RUN;

*PATERNAL X SIBS INTERACTION (P=0.003)*;

ODS OUTPUT FITSTATISTICS = FIT_FULLC GLOBALTESTS = GLOBAL_FULLC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)= FAGEBTH_5YR SIBS MAGEBTH_5YR SEX_NEW RACENEW EDUCA FAGEBTH_5YR*SIBS/RL;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;

DATA FIT_FULLFC; 
	SET FIT_FULLC (KEEP = CRITERION WITHCOVARIATES); 

WHERE CRITERION = "-2 LOG L";
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1"; 
RENAME WITHCOVARIATES = MODEL_F;
RUN;

DATA GLOBAL_FULLFC; 
	SET GLOBAL_FULLC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_F;
RUN;

DATA FULLC; 
MERGE FIT_FULLFC GLOBAL_FULLFC; 
BY MERGEVAR; 
RUN;
PROC PRINT DATA = FULLC; TITLE2 "Full Model Test Stats"; RUN;


DATA CHITEST (KEEP = MERGEVAR MODEL_R MODEL_F CHIVAL PVAL P_VALUE DF_R DF_F DOF);
		MERGE REDUCEDC FULLC; BY MERGEVAR;
		CHIVAL = ABS(MODEL_F - MODEL_R);
		DOF = ABS(DF_F - DF_R);
		PVAL = 1 - PROBCHI(CHIVAL,DOF); P_VALUE = PUT(ROUND(PVAL,0.001),5.3); 
RUN;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\INTERACTION FATHERS AGE X SIBS - &SYSDATE..RTF";

TITLE 'CONTINUOUS (PER 5 YRS) FATHERS AGE*SIBLINGS INTERACTION';
PROC PRINT DATA = CHITEST; RUN;

ODS RTF CLOSE;

*MATERNAL X SIBS INTERACTION (P=0.147)*;

ODS OUTPUT FITSTATISTICS = FIT_FULLC GLOBALTESTS = GLOBAL_FULLC;
PROC PHREG DATA=PAGE.FINALCOHORT;
CLASS RACENEW EDUCA/PARAM=REF REF=FIRST;
MODEL FAILNEW*ALL_HEMA(0)= FAGEBTH_5YR SIBS MAGEBTH_5YR SEX_NEW RACENEW EDUCA MAGEBTH_5YR*SIBS/RL;
STRATA AGE92M;
RUN;
ODS OUTPUT CLOSE;

DATA FIT_FULLFC; 
	SET FIT_FULLC (KEEP = CRITERION WITHCOVARIATES); 

WHERE CRITERION = "-2 LOG L";
IF CRITERION = "-2 LOG L" THEN MERGEVAR = "1"; 
RENAME WITHCOVARIATES = MODEL_F;
RUN;

DATA GLOBAL_FULLFC; 
	SET GLOBAL_FULLC (KEEP = TEST DF); 

WHERE TEST = "Likelihood Ratio";
IF TEST = "Likelihood Ratio" THEN MERGEVAR = "1"; 
RENAME DF = DF_F;
RUN;

DATA FULLC; 
MERGE FIT_FULLFC GLOBAL_FULLFC; 
BY MERGEVAR; 
RUN;
PROC PRINT DATA = FULLC; TITLE2 "Full Model Test Stats"; RUN;


DATA CHITEST (KEEP = MERGEVAR MODEL_R MODEL_F CHIVAL PVAL P_VALUE DF_R DF_F DOF);
		MERGE REDUCEDC FULLC; BY MERGEVAR;
		CHIVAL = ABS(MODEL_F - MODEL_R);
		DOF = ABS(DF_F - DF_R);
		PVAL = 1 - PROBCHI(CHIVAL,DOF); P_VALUE = PUT(ROUND(PVAL,0.001),5.3); 
RUN;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\INTERACTION MOTHERS AGE X SIBS - &SYSDATE..RTF";

TITLE 'CONTINUOUS (PER 5 YRS) MOTHERS AGE*SIBLINGS INTERACTION';
PROC PRINT DATA = CHITEST; RUN;

ODS RTF CLOSE;

*****************;
*	DISCUSSION	*;
*****************;
ODS RTF FILE= "D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\DISCUSSION STATISTICS - &SYSDATE..rtf";

*PROPORTION OF WOMEN VS MEN WHO HAVE SIBLINGS (PG. 8)*;
PROC FREQ DATA=PAGE.FINALCOHORT;
WHERE SIBS=1;
TABLES SEX_NEW/NOCUM;
FORMAT SEX_NEW GENDER.;
RUN;

ODS RTF CLOSE;

*****************;
*	TABLE 1		*;
*****************;
%INCLUDE 'D:\USER\JBLASE\Macros\DESCRIPTIVE_TBL.sas';

*DESCRIPTIVE TABLES & FREQUENCIES*;

*STRATIFIED BY PATERNAL AGE AT BIRTH*;
%DESCRIPTIVE_TBL (DAT= PAGE.FINALCOHORT, EXPOSURE=FAGEBTH_4CAT, COVCAT= AGE92_ENT SEX_NEW RACENEW ALC_BLK BMI EDUCA SMOKEV SIBS SIT,
                      COVCONT=, ORDER=FORMATTED, ROWCOL=COL,CHI=1,LIMIT=1,
				      PERDEC=0.1, CONTMEAS=MEANSD , PRINTOUT=0,TOTAL=0,COLWDTH=40,STARTLAB=,TITL= Paternal Age at Birth and Hema Malignancies Cohort,
				      ODSTYPE=RTF,ODSSTYLE=Minimal,ODSPATH= D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\Table1 Paternal &SYSDATE..RTF,
                      ORIENT=LANDSCAPE); 


*STRATIFIED BY MATERNAL AGE AT BIRTH*;
%DESCRIPTIVE_TBL (DAT= PAGE.FINALCOHORT, EXPOSURE=MAGEBTH_4CAT, COVCAT= AGE92_ENT SEX_NEW RACENEW ALC_BLK BMI EDUCA SMOKEV SIBS SIT,
                      COVCONT=, ORDER=FORMATTED, ROWCOL=COL,CHI=1,LIMIT=1,
				      PERDEC=0.1, CONTMEAS=MEANSD , PRINTOUT=0,TOTAL=0,COLWDTH=40,STARTLAB=,TITL= Maternal Age at Birth and Hema Malignancies Cohort,
				      ODSTYPE=RTF,ODSSTYLE=Minimal,ODSPATH= D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\Table1 Maternal &SYSDATE..RTF,
                      ORIENT=LANDSCAPE); 

*****************;
*	TABLE 2		*;
*****************;

*USING BRIAN'S COX MODELS MACRO*;
%INCLUDE 'D:\USER\JBLASE\From Other Analysts\BASIC MODELS MACRO - BRIAN.SAS';

***********************************;
*ALL HEME - MEN AND WOMEN COMBINED*;
***********************************;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW SIBS, 
		OUT=FAGE4_ALLHEME,STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=FAGEBTH_4CAT, FINAL=ALLHEME_FAGE4, MODELLABEL="ALL HEME, FAGE4", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW SIBS,
		OUT=MAGE4_ALLHEME,STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=MAGEBTH_4CAT, FINAL=ALLHEME_MAGE4, MODELLABEL="ALL HEME, MAGE4", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW SIBS, OUT=FAGE5YR_ALLHEME,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=FAGEBTH_5YR, FINAL=ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW SIBS, OUT=MAGE5YR_ALLHEME,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=MAGEBTH_5YR, FINAL=ALLHEME_MAGE5YR, MODELLABEL="ALL HEME, MAGE5YR", VARFORMAT=);

******************************;
*ALL HEME - STRATIFIED BY SEX*;
******************************;

*********;
*FEMALES*;
*********;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=FAGE_ALL_HEMA_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=1, VAR=FAGEBTH_4CAT, FINAL=FEM_FAGE_ALL_HEMA, MODELLABEL="FEM, FAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=MAGEBTH_4CAT FAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=MAGE_ALL_HEMA_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=1, VAR=MAGEBTH_4CAT, FINAL=FEM_MAGE_ALL_HEMA,MODELLABEL="FEM, MAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=FAGE5YR_ALLHEME_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=0, VAR=FAGEBTH_5YR, FINAL=FEM_ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=MAGE5YR_ALLHEME_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=0, VAR=MAGEBTH_5YR, FINAL=FEM_ALLHEME_MAGE5YR, MODELLABEL="ALL HEME, MAGE5YR", VARFORMAT=);


*******;
*MALES*;
*******;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=FAGE2_ALL_HEMA_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=1, VAR=FAGEBTH_4CAT, FINAL=MALE_FAGE_ALL_HEMA, MODELLABEL="MALE, FAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=MAGEBTH_4CAT FAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=MAGE2_ALL_HEMA_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=1, VAR=MAGEBTH_4CAT, FINAL=MALE_MAGE_ALL_HEMA,MODELLABEL="MALE, MAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=FAGE5YR_ALLHEME_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=0, VAR=FAGEBTH_5YR, FINAL=MALE_ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=MAGE5YR_ALLHEME_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=0, VAR=MAGEBTH_5YR, FINAL=MALE_ALLHEME_MAGE5YR, MODELLABEL="ALL HEME, MAGE5YR", VARFORMAT=);

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\TABLE 2 - ALL HEME - &SYSDATE..RTF";
TITLE 'ALL HEME - MEN AND WOMEN COMBINED';
PROC PRINT DATA=ALLHEME_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=ALLHEME_MAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=ALLHEME_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'ALL HEME - WOMEN ONLY';
PROC PRINT DATA=FEM_FAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEM_MAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEM_ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=FEM_ALLHEME_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'ALL HEME - MEN ONLY';
PROC PRINT DATA=MALE_FAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALE_MAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALE_ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=MALE_ALLHEME_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

ODS RTF CLOSE;

*RESULTS (PG. 7) - In models that did not mutually control for maternal age, associations with paternal age were slightly weaker and not 
statistically significant*;

***********************************;
*ALL HEME - MEN AND WOMEN COMBINED*;
***********************************;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT RACENEW EDUCA SEX_NEW SIBS, 
		OUT=FAGE4_ALLHEME,STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=FAGEBTH_4CAT, FINAL=ALLHEME_FAGE4, MODELLABEL="ALL HEME, FAGE4", VARFORMAT=PAGEBTH_4CAT.);
 
*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR RACENEW EDUCA SEX_NEW SIBS, OUT=FAGE5YR_ALLHEME,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=FAGEBTH_5YR, FINAL=ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);

******************************;
*ALL HEME - STRATIFIED BY SEX*;
******************************;

*********;
*FEMALES*;
*********;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=FAGE_ALL_HEMA_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=1, VAR=FAGEBTH_4CAT, FINAL=FEM_FAGE_ALL_HEMA, MODELLABEL="FEM, FAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR RACENEW EDUCA SIBS, OUT=FAGE5YR_ALLHEME_F,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=0, VAR=FAGEBTH_5YR, FINAL=FEM_ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);

*******;
*MALES*;
*******;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=FAGE2_ALL_HEMA_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=1, VAR=FAGEBTH_4CAT, FINAL=MALE_FAGE_ALL_HEMA, MODELLABEL="MALE, FAGE, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR RACENEW EDUCA SIBS, OUT=FAGE5YR_ALLHEME_M,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=0, VAR=FAGEBTH_5YR, FINAL=MALE_ALLHEME_FAGE5YR, MODELLABEL="ALL HEME, FAGE5YR", VARFORMAT=);


ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\NON-MUTUALLY ADJUSTED MODELS - &SYSDATE..RTF";
TITLE 'ALL HEME - MEN AND WOMEN COMBINED';
PROC PRINT DATA=ALLHEME_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'ALL HEME - WOMEN ONLY';
PROC PRINT DATA=FEM_FAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEM_ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'ALL HEME - MEN ONLY';
PROC PRINT DATA=MALE_FAGE_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALE_ALLHEME_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

ODS RTF CLOSE;


*****************;
*	TABLE 3		*;
*****************;

*	STRATIFIED BY SIBLING STATUS - ALL PARTICIPANTS, WOMEN AND MEN	*;

*************;
*NO SIBLINGS*;
*************;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW, OUT=FAGE4_NOSIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=0, CASES=1, VAR=FAGEBTH_4CAT, FINAL=NOSIBS_FAGE4_ALL_HEMA, MODELLABEL="NOSIBS, FAGE4, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW, OUT=MAGE4_NOSIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=0, CASES=1, VAR=MAGEBTH_4CAT, FINAL=NOSIBS_MAGE4_ALL_HEMA, MODELLABEL="NOSIBS, MAGE4, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW, OUT=FAGE5YR_NOSIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=0, CASES=0, VAR=FAGEBTH_5YR, FINAL=NOSIBS_FAGE5YR_ALL_HEMA, MODELLABEL="NOSIBS, FAGE5YR, ALL_HEMA", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW, OUT=MAGE5YR_NOSIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=0, CASES=0, VAR=MAGEBTH_5YR, FINAL=NOSIBS_MAGE5YR_ALL_HEMA, MODELLABEL="NOSIBS, MAGE5YR, ALL_HEMA", VARFORMAT=);

*************;
* SIBLINGS  *;
*************;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW, OUT=FAGE4_SIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=1, CASES=1, VAR=FAGEBTH_4CAT, FINAL=SIBS_FAGE4_ALL_HEMA, MODELLABEL="SIBS, FAGE4, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW, OUT=MAGE4_SIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=1, CASES=1, VAR=MAGEBTH_4CAT, FINAL=SIBS_MAGE4_ALL_HEMA, MODELLABEL="SIBS, MAGE4, ALL_HEMA", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW, OUT=FAGE5YR_SIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=1, CASES=0, VAR=FAGEBTH_5YR, FINAL=SIBS_FAGE5YR_ALL_HEMA, MODELLABEL="SIBS, FAGE5YR, ALL_HEMA", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW, OUT=MAGE5YR_SIBS_ALL_HEMA,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SIBS, WHERE=1, CASES=0, VAR=MAGEBTH_5YR, FINAL=SIBS_MAGE5YR_ALL_HEMA, MODELLABEL="SIBS, MAGE5YR, ALL_HEMA", VARFORMAT=);

*STRATIFIED BY SIBLINGS AND SEX*;

%MACRO SIBSEXSTRAT;

%LET DATALIST= PAGE.MALENOSIBS PAGE.FEMNOSIBS PAGE.MALESIBS PAGE.FEMSIBS;
	%DO A=1 %TO 4;
		%LET DATA=%SCAN(&DATALIST, &A, %STR( ));

*FAGEBTH_4CAT*;
%PHREG(DATA=&DATA,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA, OUT=FAGE4_%SUBSTR(&DATA,6),
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=FAGEBTH_4CAT, FINAL=%SUBSTR(&DATA,6)_FAGE4, MODELLABEL="%SUBSTR(&DATA., 6), FAGE4", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=&DATA,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA, OUT=MAGE4_%SUBSTR(&DATA,6),
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=MAGEBTH_4CAT, FINAL=%SUBSTR(&DATA,6)_MAGE4, MODELLABEL="%SUBSTR(&DATA., 6), MAGE4", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=&DATA,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA, OUT=FAGE5YR_%SUBSTR(&DATA,6),
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=FAGEBTH_5YR, FINAL=%SUBSTR(&DATA,6)_FAGE5YR, MODELLABEL="%SUBSTR(&DATA., 6), FAGE5YR", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=&DATA,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=ALL_HEMA, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA, OUT=MAGE5YR_%SUBSTR(&DATA,6),
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=MAGEBTH_5YR, FINAL=%SUBSTR(&DATA,6)_MAGE5YR, MODELLABEL="%SUBSTR(&DATA., 6), MAGE5YR", VARFORMAT=);

%END;

%MEND SIBSEXSTRAT;

%SIBSEXSTRAT;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\TABLE 3 MODELS STRATIFIED SIBLINGS - &SYSDATE..RTF";

TITLE 'ALL PARTICIPANTS, NO SIBLINGS';
PROC PRINT DATA=NOSIBS_FAGE4_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=NOSIBS_MAGE4_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=NOSIBS_FAGE5YR_ALL_HEMA; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=NOSIBS_MAGE5YR_ALL_HEMA; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'ALL PARTICIPANTS, WITH SIBLINGS';
PROC PRINT DATA=SIBS_FAGE4_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=SIBS_MAGE4_ALL_HEMA; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=SIBS_FAGE5YR_ALL_HEMA; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=SIBS_MAGE5YR_ALL_HEMA; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'MALES, NO SIBLINGS';
PROC PRINT DATA=MALENOSIBS_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALENOSIBS_MAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALENOSIBS_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=MALENOSIBS_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'FEMALES, NO SIBLINGS';
PROC PRINT DATA=FEMNOSIBS_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMNOSIBS_MAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMNOSIBS_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMNOSIBS_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'MALES, WITH SIBLINGS';
PROC PRINT DATA=MALESIBS_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALESIBS_MAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=MALESIBS_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=MALESIBS_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'FEMALES, WITH SIBLINGS';
PROC PRINT DATA=FEMSIBS_FAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMSIBS_MAGE4; VAR FREQUENCY MERGEVAR RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMSIBS_FAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=FEMSIBS_MAGE5YR; VAR FREQUENCY RR CI VARIABLE; RUN;

ODS RTF CLOSE;

*****************************;
*	SUPPLEMENTARY TABLE 1	*;
*****************************;

*SUBTYPES STRATIFIED BY SEX*;

%MACRO MODS;
	%LET CASELIST=LYMPHOID_D DLBCL_D FOLLIC_D CLLSLL_D MYELOMA_D MYELUK_D AML_D;
	%DO A=1 %TO 7;
		%LET EVENT=%SCAN(&CASELIST, &A, %STR( ));

****************;
*NON-STRATIFIED*;
****************;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW SIBS, OUT=TFAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=FAGEBTH_4CAT, FINAL=FAGE4_&EVENT, MODELLABEL="FAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SEX_NEW SIBS, OUT=TMAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=1, VAR=MAGEBTH_4CAT, FINAL=MAGE4_&EVENT, MODELLABEL="MAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW SIBS, OUT=TFAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=FAGEBTH_5YR, FINAL=FAGE5YR_&EVENT, MODELLABEL="FAGE5YR, &EVENT", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SEX_NEW SIBS, OUT=TMAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=0, WHEREVAR=, WHERE=, CASES=0, VAR=MAGEBTH_5YR, FINAL=MAGE5YR_&EVENT, MODELLABEL="MAGE5YR, &EVENT", VARFORMAT=);

*********;
**MALES**;
*********;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=PMFAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=1, VAR=FAGEBTH_4CAT, FINAL=MFAGE4_&EVENT, MODELLABEL="MALE, FAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=PMMAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=1, VAR=MAGEBTH_4CAT, FINAL=MMAGE4_&EVENT, MODELLABEL="MALE, MAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=PMFAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=0, VAR=FAGEBTH_5YR, FINAL=MFAGE5YR_&EVENT, MODELLABEL="MALE, FAGE5YR, &EVENT", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=PMMAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=0, CASES=0, VAR=MAGEBTH_5YR, FINAL=MMAGE5YR_&EVENT, MODELLABEL="MALE, MAGE5YR, &EVENT", VARFORMAT=);

***********;
**FEMALES**;
***********;

*FAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=PFFAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=1, VAR=FAGEBTH_4CAT, FINAL=FFAGE4_&EVENT, MODELLABEL="FEM, FAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*MAGEBTH_4CAT*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW FAGEBTH_4CAT MAGEBTH_4CAT, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_4CAT MAGEBTH_4CAT RACENEW EDUCA SIBS, OUT=PFMAGE4_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=1, VAR=MAGEBTH_4CAT, FINAL=FMAGE4_&EVENT, MODELLABEL="FEM, MAGE4, &EVENT", VARFORMAT=PAGEBTH_4CAT.);

*CONTINUOUS 5 YR - FAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=PFFAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=0, VAR=FAGEBTH_5YR, FINAL=FFAGE5YR_&EVENT, MODELLABEL="FEM, FAGE5YR, &EVENT", VARFORMAT=);

*CONTINUOUS 5 YR - MAGEBTH_5YR*;
%PHREG(DATA=PAGE.FINALCOHORT,CATEGORIES=1,CLASS=EDUCA RACENEW, FAIL=FAILNEW, EVENT=&EVENT, MODEL=FAGEBTH_5YR MAGEBTH_5YR RACENEW EDUCA SIBS, OUT=PFMAGE5YR_&EVENT,
	  STRATA=AGE92M, SUBSET=1, WHEREVAR=SEX_NEW, WHERE=1, CASES=0, VAR=MAGEBTH_5YR, FINAL=FMAGE5YR_&EVENT, MODELLABEL="FEM, MAGE5YR, &EVENT", VARFORMAT=);


%END;

ODS RTF FILE="D:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\SUPP TABLE 1 - SUBTYPES - &SYSDATE..RTF";

%LET CASELIST= LYMPHOID_D DLBCL_D FOLLIC_D CLLSLL_D MYELOMA_D MYELUK_D AML_D;
	%DO A=1 %TO 7;
		%LET EVENT=%SCAN(&CASELIST, &A, %STR( ));

TITLE 'NON-STRATIFIED';
PROC PRINT DATA=FAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=MAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=FAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=MAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'MALES';
PROC PRINT DATA=MFAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=MMAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=MFAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=MMAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;

TITLE 'FEMALES';
PROC PRINT DATA=FFAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=FMAGE4_&EVENT; VAR FREQUENCY MERGEVAR RR CI VARIABLE OUTCOME; RUN;
PROC PRINT DATA=FFAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;
PROC PRINT DATA=FMAGE5YR_&EVENT; VAR FREQUENCY RR CI VARIABLE; RUN;

%END;

ODS RTF CLOSE;


%MEND MODS;

%MODS;


***************;
*	SPLINES	  *;
***************;


*RUN SPLINES LOCALLY*;
%INCLUDE 'S:\USER\JBLASE\Macros\lgtphcurv9.sas';
%INCLUDE 'S:\USER\JBLASE\MACROS\Leukemia Groups.SAS';
LIBNAME LIBRARY 'S:\USER\JBLASE'; 
LIBNAME PAGE 'S:\USER\JBLASE\Hema Malignancies & Parents Age\DATA';
OPTIONS MPRINT;


*FIGURE 1 - FATHERS AGE SPLINE FOR NO SIBLINGS*;

ODS PDF FILE="S:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\SPLINES - FATHERS AGE AMONG NO SIBLINGS - &SYSDATE..PDF"; 
%lgtphcurv9(DATA=PAGE.NOSIBS, MODEL=COX, STRATA=AGE92M, TIME=FAILNEW, CASE=ALL_HEMA, EXPOSURE=FAGEBTH, ADJ=MAGEBTH RACE2 RACE3 EDUCA2 EDUCA3 EDUCA4 EDUCA5 SEX_NEW, 
            SELECT=1, REFVAL=MIN, CI=2, PLOT=2, HLABEL=%QUOTE(PATERNAL AGE AT BIRTH), FOOTER=NONE, KLINES=F, MODPRINT=F, PRINTCV=F, DISPLAYX=F, CUTOFF= 1 10, OUTPLOT=JPEG, 
			AXORDV=0 TO 7 BY 1, axordh=10 to 80 by 5, VLABEL=HAZARD RATIO FOR ALL HEMATOPOIETIC CANCERS, GRAPHTIT=NONE, PWHICH=LINEAR);
ODS PDF CLOSE;


*P-VALUE SPLINE FOR MEN WITH NO SIBLINGS (PG. 7)*;
*OUTPUT THIS SPLINE AS A WORD DOC BC WAS HAVING TROUBLE WITH PDF*;
ODS RTF FILE="S:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\SPLINES - FATHERS AGE AMONG MALES, NO SIBLINGS - &SYSDATE..RTF"; 
%lgtphcurv9(DATA=PAGE.MALENOSIBS, MODEL=COX, STRATA=AGE92M, TIME=FAILNEW, CASE=ALL_HEMA, EXPOSURE=FAGEBTH, ADJ=MAGEBTH RACE2 RACE3 EDUCA2 EDUCA3 EDUCA4 EDUCA5, 
            SELECT=1, REFVAL=MIN, CI=2, PLOT=2, HLABEL=%QUOTE(PATERNAL AGE AT BIRTH), FOOTER=NONE, KLINES=F, MODPRINT=F, PRINTCV=F, DISPLAYX=F, CUTOFF=1 10, OUTPLOT=JPEG, 
			PICTNAME=MALENOSIB.PS, AXORDV=0 TO 7 BY 1, VLABEL=HAZARD RATIO FOR ALL HEMATOPOIETIC CANCERS, GRAPHTIT=NONE);
ODS RTF CLOSE;


*P-VALUE SPLINE FOR WOMEN WITH NO SIBLINGS (PG. 7)*;

ODS PDF FILE="S:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\SPLINES FATHERS AGE AMONG FEMALES, NO SIBLINGS - &SYSDATE..PDF"; 
%lgtphcurv9(DATA=PAGE.FEMNOSIBS, MODEL=COX, STRATA=AGE92M, TIME=FAILNEW, CASE=ALL_HEMA, EXPOSURE=FAGEBTH, ADJ=MAGEBTH RACE2 RACE3 EDUCA2 EDUCA3 
			EDUCA4 EDUCA5, SELECT=1, REFVAL=MIN, CI=2, PLOT=2, HLABEL=%QUOTE(PATERNAL AGE AT BIRTH), FOOTER=NONE, KLINES=F, PRINTCV=F, DISPLAYX=F, CUTOFF=1 10, OUTPLOT=JPEG, 
			PICTNAME=FEMNOSIB.PS, AXORDV=0 TO 7 BY 1, VLABEL=HAZARD RATIO FOR ALL HEMATOPOIETIC CANCERS, GRAPHTIT=NONE);
ODS PDF CLOSE;



*********************;
*	P-HETEROGENEITY	*;
*********************;
*RUN META ANALYSIS FOR P-VALUE FOR HOMOGENEITY BETWEEN NHL SUBTYPES*;

OPTIONS EXTENDOBSCOUNTER=NO;

%INCLUDE "S:\USER\JBLASE\MACROS\poolrr.sas"; *POOLRR MACRO MODIFIED BY BRIAN*;
%INCLUDE "S:\USER\JBLASE\MACROS\forest.sas"; *FOREST MACRO MODIFIED BY BRIAN*;

DATA CATEGORICAL;
INPUT STUDY $ TYPE RR LL UL;
DATALINES;
DLBCL 0 1.29 0.86 1.94
FL 0 0.68 0.40 1.13
CLLSLL 0 1.10 0.75 1.61
MM     0 1.20 0.77 1.89 
AML    0 1.64 0.93 2.92
DLBCL  1 0.66 0.44 1.00
FL     1 0.87 0.50 1.50
CLLSLL 1 0.90 0.62 1.32
MM     1 0.95 0.62 1.46
AML    1 0.83 0.48 1.42
;
RUN;
PROC PRINT DATA=CATEGORICAL; RUN;


ODS RTF STYLE=JOURNAL FILE = "S:\USER\JBLASE\Hema Malignancies & Parents Age\PROGRAM REVIEW\OUTPUT\NHL SUBTYPES META - &sysdate..RTF";
*CATEGORICAL*;
%poolrr(data=CATEGORICAL,title=CATEGORICAL PATERNAL SUBTYPES,cat=(type=0),plot=1,msize=,msex=,mtype=);
%poolrr(data=CATEGORICAL,title=CATEGORICAL MATERNAL SUBTYPES,cat=(type=1),plot=1,msize=,msex=,mtype=);
ODS RTF CLOSE;

OPTIONS MPRINT;
