/*============================================================================================================
  Project Name     : NHL & POLYOMAVIRUS
  PI               : LAUREN TERAS
  Program Objective: QC CHECK FOR POLYOMAVIRUS ANTIGENS (BKV, JCV, WUV, KIV, MCV, HPy6, HPy7, LPV, TSV)
  Dataset used     : 
  Last update      : 12/3/13
  ===========================================================================================================*/
   
* NOTE: RUN THIS PROGRAM LOCALLY *;

options nodate center pageno=1 ls=85 ps=70 nofmterr MPRINT;

dm  'out; clear; log; clear;';        *----- CLEARING LOG & OUTPUT WINDOWS ; 

LIBNAME PLYMA 'S:\USER\JBLASE\NHL & Polyomavirus\Jenny\DATA';  
%INCLUDE 'S:\USER\JBLASE\MACROS\QC-Check-macro.sas';

*IMPORTING DATASET*;
PROC IMPORT   OUT= PLYMA.INFNHL1000
              DATAFILE= "S:\USER\JBLASE\NHL & Polyomavirus\Jenny\DATA\infect-nhl-1000dil.xls" 
              DBMS=EXCEL REPLACE;
			  RANGE = "A1:AY918"; 
RUN;

PROC SQL; 
SELECT  COUNT(DISTINCT PLATE), COUNT(DISTINCT BARCODE), COUNT(*) 
        INTO :NUMPLT, :NUMID, :NUMROW
FROM PLYMA.INFNHL1000
; 
QUIT; 

*CREATING A TEMPORARY DATASET FROM THE PERMANENT DATASET INFNHL1000*;

DATA INFNHL1000_TEMP;
	SET PLYMA.INFNHL1000;
RUN;

* QC SUBJECTS, NEED TO BE TAKE OUT FROM THE RECEIVED FILES AND RUN QC PROGRAM ON THEM; 
DATA PLYMA.QCS QCS; 
	SET PLYMA.shiplocs_batch_qcs_12mar12; 
RUN; 


PROC SQL; 
SELECT  COUNT(DISTINCT PLATE), COUNT(DISTINCT BARCODE), COUNT (DISTINCT SUBJID), COUNT(*) 
        INTO :NUMPLTQC, :NUMLABQC, :NUMIDQC, :NUMROWQC
FROM QCS
; 
QUIT; 

options nosource; 

	%put *======== DATA DESCRIPTION  =============*; 
	%PUT ===RECEIVED FILE ; 
	%PUT ---NUMBER OF PLATES = %LEFT(&NUMPLT) ; 
	%PUT ---NUMBER OF BARCODE= %LEFT(&NUMID) ; 
	%PUT ---NUMBER OF ROWS = %LEFT(&NUMROW) ; 
    %put                                    ; 
	%PUT ===QC FILE ; 
	%PUT ---NUMBER OF PLATES = %LEFT(&NUMPLTQC); 
	%PUT ---NUMBER OF BARCODE = %LEFT(&NUMLABQC); 
	%PUT ---NUMBER OF ID = %LEFT(&NUMIDQC); 
	%PUT ---NUMBER OF ROW = %LEFT(&NUMROWQC); 
	%PUT *========================================*; 

options source; 


*FROM RECEIVED FILE, SELECT SUBJECTS WITH SAME BARCODE IN THE QC FILE; 
*56 BARCODES; 

PROC SQL; 
CREATE TABLE QCFILE1000 AS 
SELECT INFNHL1000_TEMP.* , QCS.SUBJID
FROM INFNHL1000_TEMP, QCS
 WHERE  INFNHL1000_TEMP.BARCODE = QCS.BARCODE
; 
QUIT;   

TITLE2'POLYOMAVIRUS QC ANALYSIS'; 

PROC SORT DATA = QCFILE1000;
	BY SUBJID PLATE;
RUN;


*****POLYOMAVIRUS******;
**BKV**;	
DATA QCBKV;
	SET QCFILE1000;
	WHERE BK_VP1>1;
	LOG_BKV = LOG(BK_VP1); 
RUN;

PROC PRINT DATA=QCBKV;
	VAR subjid plate BK_VP1 LOG_BKV;
RUN;

**JCV**;
DATA QCJCV;
	SET QCFILE1000;
	WHERE JC_VP1>1;
	LOG_JCV = LOG(JC_VP1); 
RUN;

PROC PRINT DATA=QCJCV;
	VAR subjid plate JC_VP1 LOG_JCV;
RUN;

**WUV**;
DATA QCWUV;
	SET QCFILE1000;
	WHERE WU_VP1>1;
	LOG_WUV = LOG(WU_VP1); 
RUN;

PROC PRINT DATA=QCWUV; 
	VAR subjid plate WU_VP1 LOG_WUV;
RUN;

**KIV**;
DATA QCKIV;
	SET QCFILE1000;
	WHERE KI_VP1>1;
	LOG_KIV = LOG(KI_VP1); 
RUN;

PROC PRINT DATA=QCKIV;
	VAR subjid plate KI_VP1 LOG_KIV;
RUN;

**MCV**;
DATA QCMCV;
	SET QCFILE1000;
	WHERE MCV344_VP1>1;
	LOG_MCV = LOG(MCV344_VP1); 
RUN;

PROC PRINT DATA=QCMCV;
	VAR subjid plate MCV344_VP1 LOG_MCV;
RUN;

**HPy6**;
DATA QCHPy6;
	SET QCFILE1000;
	WHERE HPyV6_VP1>1;
	LOG_HPy6 = LOG(HPyV6_VP1); 
RUN;

PROC PRINT DATA=QCHPy6;
	VAR subjid plate HPyV6_VP1 LOG_HPy6;
RUN;

**HPy7**;
DATA QCHPy7;
	SET QCFILE1000;
	WHERE HPyV7_VP1>1;
	LOG_HPy7 = LOG(HPyV7_VP1); 
RUN;

PROC PRINT DATA=QCHPy7;
	VAR subjid plate HPyV7_VP1 LOG_HPy7;
RUN;

**LPV**;
DATA QCLPV;
	SET QCFILE1000;
	WHERE LPV_VP1>1;
	LOG_LPV = LOG(LPV_VP1); 
RUN;

ODS RTF FILE="S:\USER\JBLASE\NHL & Polyomavirus\Jenny\OUTPUT\LPV QC.RTF"; 
PROC PRINT DATA=QCLPV;
	VAR subjid plate LPV_VP1 LOG_LPV;
RUN;
ODS RTF CLOSE;

**TSV**;
DATA QCTSV;
	SET QCFILE1000;
	WHERE TSV_VP1>1;
	LOG_TSV = LOG(TSV_VP1); 
RUN;

PROC PRINT DATA=QCTSV;
	VAR subjid plate TSV_VP1 LOG_TSV;
RUN;

*OUTPUTTING COEFFICIENTS OF VARIATION AND INTRACLASS CORRELATION COEFFICIENTS*;
ODS RTF STYLE=JOURNAL BODYTITLE FILE="S:\USER\JBLASE\NHL & Polyomavirus\Jenny\OUTPUT\LOG QC GRAPHS-&SYSDATE..RTF" STARTPAGE=NO;

%QCCHECK (QCBKV,LOG_BKV, PLATE); *BKV*;
%QCCHECK (QCJCV,LOG_JCV, PLATE); *JCV*;
%QCCHECK (QCWUV,LOG_WUV, PLATE); *WUV*;
%QCCHECK (QCKIV,LOG_KIV, PLATE); *KIV*;
%QCCHECK (QCMCV,LOG_MCV, PLATE); *MCV*;
%QCCHECK (QCHPy6,LOG_HPy6, PLATE); *HPy6*;
%QCCHECK (QCHPy7,LOG_HPy7, PLATE); *HPy7*;
%QCCHECK (QCLPV,LOG_LPV, PLATE); *LPV*;
%QCCHECK (QCTSV,LOG_TSV, PLATE); *TSV*;

ODS RTF CLOSE; 
